.drone.yml
[[JIRA](https://jira.mongodb.org/browse/DOCSP-4432)] Integrate Jest front-end testing with Drone. This PR adds two tasks to the `.drone.yml` file:
- `build`: build the front-end using npm
- `test`: execute `npm test` as specified in `package.json`
=> DOCSP-4432: Add front-end tests to Drone file

front-end/src/templates/index.js
A restructuring of the AST caused guides to not be properly parsed for the landing page. This PR properly renders the homepage, and finds guides by searching through `children` arrays of the AST rather than querying a specific index.
=> Bugfix: properly fetch guides for landing page

front-end/package-lock.json, front-end/package.json
This PR introduces a plugin that automatically converts Enzyme shallow mounted components to JSON, allowing them to be compared to snapshot files using Jest's `.toMatchSnapshot()`.
=> Bugfix: Allow enzyme shallow rendered components to match snapshots

front-end/package-lock.json, front-end/package.json, front-end/tests/Paragraph.test.js, front-end/tests/URIText.test.js
We have decided to go with [Enzyme](https://airbnb.io/enzyme/) for testing, so remove existing instances of `react-test-renderer` and replace with Enzyme.
=> Fix: Remove react-test-renderer and replace with enzyme

src/components/Tabs.js
Small improvement so that we don't show an empty `<ul>` in the place where a pillset would appear.
=> Fix: improve conditional render of tabsets

src/components/Tabs.js, src/constants.js, src/templates/guide.js
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5133)] This PR correctly sorts named tab/pillsets to match the order defined in `src/constants.js` (this order is based roughly on popularity).
There is a common case where an _anonymous_ tabset is used to create tabs for Windows/macOS/Linux rather than a `platforms` tabset. We will now sort these tabs to match the order defined by the `platforms` tabset.
This PR also adds Go as a language option.
=> DOCSP-5133: Sort named tabsets

src/components/ComponentFactory.js, src/components/TitleReference.js, tests/unit/TitleReference.test.js, tests/unit/__snapshots__/TitleReference.test.js.snap, tests/unit/data/TitleReference.test.json
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5250)] Adds `TitleReference` component, which places `<cite>` tags around text enclosed by backticks (`) in rST files.
=> DOCSP-5250: Add TitleReference component

src/components/Tabs.js, tests/unit/Tabs.test.js, tests/unit/data/Tabs-hidden.test.json
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5272)] Hides tabsets when rST file includes the `:hidden:` option. Content is still rendered conditionally using the active tab selected elsewhere on the page.
=> DOCSP-5272: Support hidden tabsets

src/components/Figure.js, src/components/Lightbox.js, tests/unit/Figure.test.js, tests/unit/Lightbox.test.js, tests/unit/__snapshots__/Figure.test.js.snap, tests/unit/__snapshots__/Lightbox.test.js.snap, tests/unit/data/FigureLightbox.test.json
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5132)] This PR adds a Lightbox to images that either:
- Specify `:lightbox:` as one of their options
- Are 10% larger than their container ([as is done currently](https://github.com/mongodb/docs-tools/blob/f6f48fb3876f4ed7b5131d00119755a25a09de7d/themes/mongodb/src/js/componentLightbox.js#L57))
=> DOCSP-5132: Add lightbox and tests

README.md, package-lock.json, package.json
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5382)]
- Add commands for `gatsby develop`, `build`, and `serve` to `package.json`'s `scripts` section
- Update README
- Remove some unused scripts from `package.json`
- Removes dependency on global installation of the Gatsby CLI
**Note:** While testing, the `npm run` process was sometimes killed randomly. This problem mostly seems to have gone away, but I'm not sure if it was due to my system config or a larger bug. Please pull this branch and run the commands a few times! If you run into problems, try running `gatsby clean` and see if they persist.
=> DOCSP-5382: Add npm scripts for running Gatsby

README.md, gatsby-config.js, gatsby-node.js, src/components/Figure.js, src/components/Lightbox.js, src/html.js, src/templates/guide.js, src/util.js
- Modify env vars so that we can use `SITE`, `USER`, and `BRANCH` variables independently within the front end.
- `STITCH_ID` renamed to `GATSBY_STITCH_ID` to expose it to the front end.
- `GATSBY_PREFIX` no longer required.
- It will be used if specified.
- If not, `production` environments will default to `/SITE/USER/BRANCH` and `development` environments will default to `/`.
- No longer set `NODE_ENV` in .env files, as this is a [reserved environment variable](https://www.gatsbyjs.org/docs/environment-variables/#reserved-environment-variables).
- Remove some deprecated GitHub fetch code.
=> Fix: Env Vars

src/components/ComponentFactory.js, src/components/Roles/Api.js, src/components/Roles/Class.js
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5425)] Add 3 missing roles:
- `java-sync-api`
- `csharp-api`
- `py:class`
Bonus fix: catches nodes of type `comment` and returns nothing.
=> DOCSP-5425: Add missing roles

src/components/Roles/Class.js, src/components/Roles/Doc.js
The `Class` role (updated in DOCSP-5425) does not require a `label.value` property, which was previously marked as required and lead to page render failure. If `label.value` is not specified, use the role's `target` property as the link text.
=> Fix: Remove required value property

src/components/Code.js
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5638)] [[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/guides/sophstad/DOCSP-5638/server/drivers)] Fix to render URI Writer strings in `<Highlight>` components.
=> DOCSP-5638: Correctly render URI strings in Highlight component

src/templates/guide.js
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5637)] [[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/guides/sophstad/DOCSP-5637/)] Fixes table of content scrolling in Safari and Firefox.
=> DOCSP-5637: Fix TOC scrolling in Safari and Firefox

src/components/GuideHeading.js, src/components/GuideSection.js, src/components/Heading.js, src/components/Step.js, src/components/TOC.js, src/constants.js, src/util.js, tests/unit/__snapshots__/Heading.test.js.snap, tests/unit/__snapshots__/Step.test.js.snap, tests/unit/data/Heading.test.json
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5701)] [[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/guides/sophstad/DOCSP-5701/cloud/migrate-from-aws-to-atlas#validate-your-aws-credentials-with-atlas-live-migration-service)]
- Use parser-generated IDs as `id` attributes and target links
- Stop generating `id` fields in front-end
- Statically define guide section ids, as they are not provided by the parser
- Update tests
- Remove invalid `PropTypes` check in `GuideSection` component
=> DOCSP-5701: Support new parser ID implementation

src/components/Tabs.js
[Staging link](https://docs-mongodborg-staging.corp.mongodb.com/guides/danielborowski/DOCSP-5643/)
Changes came from recommended [notes on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect#Notes).
=> DOCSP-5643: fix IE tab jumps

src/templates/guide.js
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5648)] [[Staging](https://docs-mongodborg-staging.corp.mongodb.com/guides/sophstad/DOCSP-5648/)] Fix "MongoDB Guides" breadcrumb link at the top of each guide. Tested in both `develop` and staging environments.
=> DOCSP-5648: Fix breadcrumb link

__mocks__/gatsby.js, jest.config.js, src/components/Figure.js, src/components/GuideBreadcrumbs.js, src/components/Lightbox.js, src/components/Roles/Doc.js, src/components/site-metadata.js, src/templates/guide.js, src/utils/__mocks__/get-path-prefix.js, src/utils/get-path-prefix.js, tests/unit/Figure.test.js, tests/unit/Lightbox.test.js, tests/unit/Role.test.js, tests/unit/__snapshots__/Role.test.js.snap
[[Staging](https://docs-mongodborg-staging.corp.mongodb.com/guides/sophstad/fix-get-path-prefix/)]
- Replace custom `getPathPrefix()` with Gatsby's (poorly documented) [`withPrefix()`](https://www.gatsbyjs.org/docs/gatsby-link/#add-the-path-prefix-to-paths-using-withprefix)
- Remove relevant mocks
- Update image src attributes and `<head>` links using this function
- Replace our one instance of an internal link with a Gatsby [`Link`](https://www.gatsbyjs.org/docs/gatsby-link/) component
- Fix tests
=> Fix path prefix

src/components/Pills.js, src/styles/pills.module.css, tests/unit/LandingPageCards.test.js, tests/unit/Pills.test.js, tests/unit/__snapshots__/Pills.test.js.snap
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5647)] [[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/guides/sophstad/DOCSP-5647/)]
- Adjust pills so that the entire pill is clickable, not just the text.
- Makes use of Gatsby's [CSS Modules](https://www.gatsbyjs.org/tutorial/part-two/#using-component-scoped-css) for component-scoped CSS.
=> DOCSP-5647: adjust padding of clickable element in pills

jest.config.js, package-lock.json, package.json, src/components/Code.js, src/components/GuideHeading.js, src/components/site-metadata.js, src/styles/code.module.css, tests/unit/__snapshots__/Code.test.js.snap, tests/unit/__snapshots__/Pills.test.js.snap
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5702)] [[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/guides/sophstad/DOCSP-5702/)]
- Dynamically set a page's `<title>` tag according to the `<h1>` title of the page
- Improve style override of our `Code` component by moving it out of the `<head>` and into a CSS module
=> DOCSP-5702: Dynamic page title

src/components/Admonition.js, src/components/ComponentFactory.js, src/components/Emphasis.js, src/components/Figure.js, src/components/GuideHeading.js, src/components/Include.js, src/components/LandingPage/Card.js, src/components/LandingPage/CardPills.js, src/components/LandingPage/LandingPageCards.js, src/components/Lightbox.js, src/components/ListTable.js, src/components/Literal.js, src/components/LiteralInclude.js, src/components/Reference.js, src/components/Roles/Class.js, src/components/Roles/Code.js, src/components/Roles/Doc.js, src/components/Roles/Manual.js, src/components/Roles/Program.js, src/components/Roles/Ref.js, src/components/Roles/Term.js, src/components/Section.js, src/components/Strong.js, src/components/Tabs.js, src/templates/guide.js, src/templates/index.js, src/utils/get-nested-value.js
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5843)] [[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/guides/sophstad/DOCSP-5843/)]
- Add new util function `getNestedValue()`
- Replace all instances of accessing nested values in objects with this function
- Ignore `default-domain` directive (per Andrew's recommendation)
=> DOCSP-5843: Fix nested object access

src/components/ComponentFactory.js, src/components/DefinitionList.js, src/components/DefinitionListItem.js, src/components/List.js, src/components/ListItem.js, src/templates/document.js, tests/unit/DefinitionList.test.js, tests/unit/List.test.js, tests/unit/__snapshots__/DefinitionList.test.js.snap, tests/unit/__snapshots__/List.test.js.snap, tests/unit/data/DefinitionList.test.json
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5910)] [[Staging](https://docs-mongodborg-staging.corp.mongodb.com/spark-connector/sophstad/DOCSP-5910/)] You can see an example of a definition list on the [/configuration](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/sophstad/DOCSP-5910/configuration) page.
- Add `DefinitionList` component
- Add tests
- Split lists into `List` and `ListItem` components
- Improves tests for lists so that raw HTML is rendered as snapshot
=> DOCSP-5910: Add definitionList

src/components/ComponentFactory.js, src/components/ListTable.js, src/components/Paragraph.js, src/components/Text.js, tests/unit/ListTable.test.js, tests/unit/__snapshots__/DefinitionList.test.js.snap, tests/unit/__snapshots__/List.test.js.snap, tests/unit/__snapshots__/ListTable.test.js.snap, tests/unit/__snapshots__/Paragraph.test.js.snap
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5911)] [[Staging](https://docs-mongodborg-staging.corp.mongodb.com/spark-connector/sophstad/DOCSP-5911/)]
- Add `Text` component
- Restructure `Paragraph` component so that it passes its children to the component factory
- Pass `ListItem` children to component factory
- Conditionally display text in `<p>` tag
- Don't use `<p>` tags in tables (unless there are multiple paragraphs)
- Improve tests so that list table outputs raw HTML
=> DOCSP-5911: Refactor listTable and Paragraph components

src/components/ComponentFactory.js, src/components/Transition.js
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5912)] [[Staging](https://docs-mongodborg-staging.corp.mongodb.com/spark-connector/sophstad/DOCSP-5912/)] Adds `Transition` component, which is a horizontal rule (`<hr/>`). It's visible on the index page.
=> DOCSP-5912: Add transition component

src/components/ComponentFactory.js, src/components/Include.js, src/templates/document.js, src/utils/find-all-key-value-pairs.js, src/utils/get-include-file.js
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5772)] [[Staging](https://docs-mongodborg-staging.corp.mongodb.com/spark-connector/sophstad/DOCSP-5772/)] Improvements are visible on the [`/java/aggregation`](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/sophstad/DOCSP-5772/java/aggregation) page.
- Parse page tree to find all `substitution_definition` nodes
- Parse all includes to find `substitution_definition` nodes
- Save these definitions in a `substitutions` map, which is passed as a prop to the `ComponentFactory`
- When the component factory encounters a `substitution_reference` node, replace it using the child nodes saved in the `substitutions` mapping
- Ignore `substitution_definition` nodes so they are not rendered on the page
=> DOCSP-5772: Implement replace functionality

jest.config.js, tests/regression/guides.test.js, tests/regression/spark-connector.test.js, tests/regression/util.js
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5882)]
- Move regression test helper functions into `tests/regression/util.js`
- Add tests for Spark Connector
=> DOCSP-5882: Configure regression tests for Spark Connector

src/components/Heading.js, src/components/Section.js, src/templates/document.js, src/templates/guide.js, tests/unit/Heading.test.js, tests/unit/__snapshots__/Heading.test.js.snap, tests/unit/__snapshots__/Include.test.js.snap, tests/unit/__snapshots__/Section.test.js.snap
[[JIRA](https://jira.mongodb.org/browse/DOCSP-6037)] [[Guides Staging](https://docs-mongodbcom-staging.corp.mongodb.com/guides/sophstad/DOCSP-6037/)] [[Spark Connector Staging](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/sophstad/DOCSP-6037)]
- Compute which level heading tag to use based on the section depth
- Add missing spacing `<div>` to document template so that page titles are properly formatted
- Update tests and snapshots
=> DOCSP-6037: Dynamic heading hierarchy

package.json
Changed script in `package.json` to run `./node_modules/.bin/eslint src/ tests/`.
=> DOCSP-6185: Change lint script to run from local node module

package-lock.json
Fix package vulnerabilities introduced by indirect dependencies (specifically [#1065](https://www.npmjs.com/advisories/1065) and [#1066](https://www.npmjs.com/advisories/1066)).
Running `npm audit` now returns 0 vulnerabilities.
=> Security update: fix package vulnerabilities

gatsby-node.js, src/components/layout.js
[[JIRA](https://jira.mongodb.org/browse/DOCSP-6902)] [[Manual Staging](https://docs-mongodbcom-staging.corp.mongodb.com/manual/sophstad/DOCSP-6902/core/index-multikey)]
- Fix images added by the `include` directive
- Clean up miscellaneous code in `gatsby-node.js`
=> DOCSP-6902: Fix image includes

.babelrc, HACKING.md, gatsby-node.js, package-lock.json, package.json, preview-start.js, preview/preview-setup.js, src/components/Image.js, src/templates/guide.js, src/utils/browser-storage.js, webpack.config.js
[Jira Ticket](https://jira.mongodb.org/browse/DOCSP-7109)
[Guides staging link](https://docs-mongodbcom-staging.corp.mongodb.com/guides/raymundrodriguez/DOCSP-7109/)
To prepare the snooty frontend to be used as a submodule for the snooty extension to create the bundle file, some of the original preview files had to be updated.
Things to note about this PR:
* `npm run preview` is no longer available as its own script.
* `page-ast.json` is a file generated by Snooty on VS Code. (Submodule will be added to snooty-vscode when [DOCSP-6886](https://jira.mongodb.org/browse/DOCSP-6886) is pushed)
=> DOCSP-7109: Update Snooty Preview files to work within VS Code

.gitignore, gatsby-node.js, package-lock.json, preview-start.js, preview/preview-setup.js, src/utils/get-template.js, webpack.config.js
[JIRA Ticket](https://jira.mongodb.org/browse/DOCSP-7186)
[Compass Staging](https://docs-mongodborg-staging.corp.mongodb.com/compass/raymundrodriguez/DOCSP-7186/)
This PR introduces changes to the preview files on the frontend. These changes will allow the VS Code extension to preview pages that use templates other than just `Guide`.
`process.env.GATSBY_SITE` is reimplemented into the webpack config but instead of obtaining it from `.env.development`, it is passed as a variable from within the Snooty extension.
Note: Since the VS Code extension requires these frontend changes to present in the submodule, this PR needs to be pushed before changes to the extension are pushed. (Extension's branch can be found [here](https://github.com/mongodb/snooty-vscode/tree/DOCSP-7186))
=> DOCSP-7186: Update preview files to support all templates

__mocks__/gatsby.js, src/components/TOCNode.js, src/components/TableOfContents.js, tests/unit/TableOfContents.test.js, tests/unit/__snapshots__/TableOfContents.test.js.snap
_The base branch for this is the TOC component main branch_
This PR adds `Gatsby Link` to the TOC to improve performance for Nodes with a `slug`. Unit tests were also augmented to mock the `Link`.
If Gatsby is being removed, the logic for these components can remain the same, and instead of importing `Link` from `gatsby`, you can import `Link` from the new navigational framework (like `react-router`)
=> UP-2657 (Add Gatsby Link)

package.json, src/components/Image.js, src/components/Lightbox.js, webpack.config.js
[Jira Ticket](https://jira.mongodb.org/browse/DOCSP-6887)
[Compass Staging](https://docs-mongodbcom-staging.corp.mongodb.com/compass/raymundrodriguez/DOCSP-6887/)
This PR introduces the use of full paths for images when running Snooty Preview on VS Code. Images still rely on base64 data pulled from Stitch when using Snooty Preview on CLI. Images still use `withPrefix()` on Gatsby.
This PR must be merged before the VS Code PR for [DOCSP-6887](https://github.com/mongodb/snooty-vscode/pull/8). Update the snooty-frontend submodule on VS Code after merging this.
=> DOCSP-6887: Image component can use vscode resources as a source

gatsby-node.js, src/components/TOCNode.js, src/templates/document.js, tests/unit/__snapshots__/TableOfContents.test.js.snap, tests/unit/data/Table-Of-Contents.test.json
[[JIRA](https://jira.mongodb.org/browse/DOCSP-7708)] [[Manual Staging](https://docs-mongodbcom-staging.corp.mongodb.com/manual/sophstad/DOCSP-7708/)]
- Snooty fetches toctree from Atlas in order to render TOC sidebar on all sites
- Update data JSON to match parser output
Known limitations:
- Formatted text doesn't render correctly in TOC sidebar
=> DOCSP-7708: Render TOC on all sites

gatsby-node.js, src/utils/format-text.js
Only files with the extension `.txt` should be rendered as pages. Fix this oversight.
Additionally, improve safety of a string modification utility function.
=> Bugfix: Only render .txt files as pages

gatsby-node.js, preview/preview-setup-cli.js, preview/preview-setup-vscode.js, src/components/LandingPage/Card.js, src/components/LandingPage/LandingPageCards.js, src/components/Roles/Doc.js, src/templates/document.js, src/templates/guide.js, src/templates/guides-index.js, src/utils/get-guide-metadata.js, tests/unit/Card.test.js, tests/unit/LandingPageCards.test.js, tests/unit/Role.test.js, tests/unit/__snapshots__/LandingPageCards.test.js.snap, tests/unit/__snapshots__/Role.test.js.snap
[[JIRA](https://jira.mongodb.org/browse/DOCSP-7939)] [[Guides Staging](https://docs-mongodbcom-staging.corp.mongodb.com/guides/ubuntu/DOCSP-7939/)]
- Stop populating includes as this is now done in the parser as of https://github.com/mongodb/snooty-parser/pull/74
- Replace `pageMetadata` with `guidesMetadata` to more accurately reflect usage
- Only parse for guides metadata when building guides
- Remove usage of `pageMetadata` in Roles, as this will be handled by the parser
=> DOCSP-7939: Populate includes in parser

src/components/Tabs.js, tests/unit/Tabs.test.js
[[JIRA](https://jira.mongodb.org/browse/DOCSP-8134)] [[Ecosystem Staging](https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/ubuntu/master/use-cases/client-side-field-level-encryption-guide)] [[Guides Staging](https://docs-mongodbcom-staging.corp.mongodb.com/guides/ubuntu/master/)] Fixed bug where `drivers` tabsets were not rendering in Ecosystem docs.
In Guides, certain tabsets are rendered as pills at the top of the page, not inline. This PR adds a check of which site is being built to determine whether to render tabs or pills.
Eventually, we will add better directives for defining pillsets.
=> DOCSP-8134: Fix tabset rendering in ecosystem

package-lock.json, package.json, preview-start.js, preview/preview-setup-cli.js, preview/preview-setup-vscode.js, src/components/DocumentBody.js, src/templates/document.js, webpack.config.js
Fix preview mode bugs:
- Fix Babel
- Install missing dependencies
- Reintroduce config in `webpack.config.js`
- Don't render components that require sitewide information in non-guides sites (TOC, Breadcrumbs, internal page nav)
- `DocumentBody` is now its own component
=> Fix preview mode

src/components/ComponentFactory.js, src/utils/generate-path-prefix.js
[[JIRA](https://jira.mongodb.org/browse/DOCSP-7862)] [[Node Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/node/ubuntu/DOCSP-7862/)] [[Ecosystem Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/ecosystem/ubuntu/DOCSP-7862/)]
- Ignore `toctree` directive in AST in order to suppress error message `==Not implemented:directive,toctree ==`.
- Fixes bug in path prefix caused by using an incorrectly named environment variable.
- Fixes block quote mapping in component factory
=> DOCSP-7862: Ignore toctree directive

CHANGELOG.md, Makefile, gatsby-node.js, package.json, src/utils/generate-path-prefix.js
[[JIRA](https://jira.mongodb.org/browse/DOCSP-8385)] [[Ecosystem Staging](https://docs-mongodbcom-staging.corp.mongodb.com/123/master/ecosystem/ubuntu/DOCSP-8385/)]
- Query for documents based on `COMMIT_HASH` and `PATCH_ID` environment variables
- Prepend `pathPrefix` with commit hash/patch ID, if specified
- Edit Makefile to allow for Snooty developers to easily stage sites
=> DOCSP-8385: Render commit-based builds

src/components/dev-hub/layout.js, src/components/dev-hub/text/index.js, src/components/dev-hub/text/text.js, src/pages/dev-hub/community.js, src/pages/dev-hub/index.js, src/pages/dev-hub/learn.js, src/pages/dev-hub/storybook.js
This PR:
- Adds text components (H1, etc) and adds fonts from mockup to global styles in layouts
- Uses ^ on existing layout pages
- Updates storybook styling and adds text components to it
=> Add text components, update storybook styling

src/components/DocumentBody.js
Switches `PropTypes.oneOf` to `PropTypes.oneOfType`.
See https://jaketrent.com/post/react-oneof-vs-oneoftype/ for details
=> Fix failed PropType warning in DocumentBody

.github/workflows/release.yml, Makefile, gatsby-config.js, package-lock.json, package.json, scripts/ensure-master.js, src/html.js, src/utils/get-git-branch.js
[[JIRA](https://jira.mongodb.org/browse/DOCSP-8882)] General release workflow:
1. Call `npm version <major/minor/patch>` to kick off [`npm-version`](https://docs.npmjs.com/cli/version). Three scripts are then called:
1. `preversion`: ensures master branch, runs standard lint/format/unit tests
2. `version`: auto-generates changelog using git history and [`auto-changelog`](https://www.npmjs.com/package/auto-changelog). `npm-version` then adds a commit here.
3. `postversion`: push with tags
2. GitHub Action invoked: release is created, then an artifact is built and attached to said release.
I also did some simplification of our git submodule. Right now `snooty.zip` is around 58M. So close! Also, do let me know if you know of any approach for testing the GitHub Action. Thanks!
=> DOCSP-8882: Add release workflow

package.json
[[JIRA](https://jira.mongodb.org/browse/DOCSP-8973)]
- Adds production build target that does not prefix paths
- Bonus: Adds small improvement to automatic versioning workflow
I can't exactly provide a staging link since `mut` prefixes the site with `user` and `branch` 😂 but I successfully tested `npm run build:prod && npm run serve:prod` on an EC2 instance!
=> DOCSP-8973: Add production build target

src/components/Literal.js, src/components/Target.js, tests/unit/Target.test.js, tests/unit/__snapshots__/DefinitionList.test.js.snap, tests/unit/__snapshots__/Literal.test.js.snap, tests/unit/__snapshots__/Target.test.js.snap, tests/unit/data/Target.test.json
[[JIRA](https://jira.mongodb.org/browse/DOP-632)] [[Ecosystem Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/ecosystem/sophstad/DOP-632/)] [[BI Connector Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/bi-connector/sophstad/DOP-632/reference/mongosqld)]
- Correctly render targets:
- If present, render the directive argument with target ID attached.
- Otherwise, render empty `<span>` tags.
- Added snapshot test to verify both cases above
- Simplified `Literal` component in order to correctly render dictionary lists associated with targets.
- Provided staging link to a BI Connector page that has heavy use of `:option:`
=> DOP-632: Render options

gatsby-node.js, src/components/layout.js, src/components/site-metadata.js, src/styles/landing.module.css, src/templates/document.js, src/templates/ecosystem-index.js, src/templates/guide.js, src/templates/landing.js, src/utils/get-plaintext.js, src/utils/get-template.js
[[JIRA](https://jira.mongodb.org/browse/DOP-958)] [[Drivers Staging](https://docs-mongodbcom-staging.corp.mongodb.com/DOP-958/drivers/sophstad/DOP-958/)]
- Change `getTemplate()` function to use `template` field specified in page rST
- Add landing template
- Handle page title in `Layout` component to avoid duplicate code
- Set title in `SiteMetadata`
- Remove former title implementation
=> DOP-958: landing template

src/components/VersionDropdown.js
[[Node Staging](https://docs-mongodbcom-staging.corp.mongodb.com/27a5b68/dop919/node/sophstad/bugfix-version-dropdown/)] Fixes bug where sites were failing to build if the content branch was not specified in the repo's `published-branches.yaml`. This should not be the case: users must be able to build branches in development and _then_ merge them into a branch specified in the YAML file.
As such, add a fallback to the component so that users can build development branches using Snooty.
=> Bugfix: add fallback branch to version dropdown

gatsby-node.js, src/utils/setup/save-asset-files.js
[[JIRA](https://jira.mongodb.org/browse/DOP-1078)] [[Drivers Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/drivers/sophstad/DOP-1078/)]
- Write `buffer` field of the binary data to fix intersphinx inventories.
- Fix async/await implementation.
=> DOP-1078: Correctly write intersphinx inventory

src/components/Heading.js, src/components/Widgets/FeedbackWidget/FeedbackHeading.js, src/components/Widgets/FeedbackWidget/context.js, src/components/Widgets/index.js, src/components/layout.js, src/utils/get-nested-value.js, tests/unit/FeedbackWidget.test.js, tests/unit/__snapshots__/Heading.test.js.snap
[[Drivers Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/drivers/sophstad/hide-feedback-header/)] When this line is included in a file's page options, hide the feedback widget's star header component on mobile:
```
:hidefeedback: header
```
On the staging link, you can see that the star rating appears at the bottom of the page, but not in the header title. On other pages, the stars appear in the header.
=> Support configuration to hide feedback widget header

src/components/ComponentFactory.js, src/components/landing/ComponentFactory.js
[[JIRA](https://jira.mongodb.org/browse/DOP-1190)] [[Charts Staging](https://docs-mongodbcom-staging.corp.mongodb.com/snooty-config/charts/sophstad/DOP-1190/)]
Logs before:
```role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet implemented
role not yet …
```
=> DOP-1190: Improve missing component warning

src/components/LiteralInclude.js, tests/unit/__snapshots__/LiteralInclude.test.js.snap, tests/unit/data/LiteralInclude.test.json
Reverts mongodb/snooty#207 — reintroduces literal include render changes.
=> Revert "Revert "DOP-877: Properly render literal includes""

jest.config.js, src/utils/generate-path-prefix.js, src/utils/site-metadata.js, tests/unit/utils/generate-path-prefix.test.js
[[JIRA](https://jira.mongodb.org/browse/DOP-1017)] Accept `PATH_PREFIX` env variable and use as [Gatsby’s path prefix](https://www.gatsbyjs.org/docs/path-prefix/), if specified. Otherwise, generate path prefix using `/project/user/branch` as before.
=> DOP-1017: Use PATH_PREFIX env variable

src/components/Heading.js, tests/unit/FeedbackWidget.test.js, tests/unit/__snapshots__/Heading.test.js.snap
[[JIRA](https://jira.mongodb.org/browse/DOP-1046)] [[Homepage Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/landing/sophstad/DOP-1046/)] [[Charts Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/charts/sophstad/DOP-1046/)] Expected behavior:
- Feedback widget stars render on mobile: `<h1>` tags are surrounded by heading container `<div>`
- Homepage does _not_ render star widget, by design
- All other `<hN>` tags are _not_ surrounded by heading container `<div>` (mobile and desktop)
=> DOP-1046: Hide feedback widget heading container for non-title headings

src/components/ListTable.js, tests/unit/ListTable.test.js, tests/unit/__snapshots__/ListTable.test.js.snap
[[DOP-1012]](https://jira.mongodb.org/browse/DOP-1012) [[BI-Connector]](https://docs-mongodbcom-staging.corp.mongodb.com/master/bi-connector/claire/DOP-1012/reference/drdl)
- Add a `CellTag` variable to dynamically tag stub columns
- Add a corresponding test
- Simplify `CSSWrapper` code
=> DOP-1012: Change <td> to <th> for stub columns

src/components/ComponentFactory.js, src/components/Roles/Icon.js
Allison's first React PR. Oooh, aaah. And it seems to work!
~~For reasons that confound me, some pages seem to be having trouble remaining rendered -- for example, https://docs-mongodbcom-staging.corp.mongodb.com/snooty-setup/charts/allison/icons/data-source-permissions seems to navigate itself away as soon as you click on it. There content is there, it's just hiding? I have no idea why. It doesn't appear to be specific to icons, because https://docs-mongodbcom-staging.corp.mongodb.com/snooty-setup/charts/allison/icons/embedded-chart-options is doing it as well and there are no icons on that page.~~ Claire has sorted that out! Yay!
Staging (Charts): https://docs-mongodbcom-staging.corp.mongodb.com/snooty-setup/charts/allison/icons/view-export-chart-data
Hopefully we'll be able to replace …
=> DOP-1165: add front-end support for font awesome and mms/charts-specific icons

src/components/ComponentFactory.js, src/components/Roles/Icon.js
I missed one of the icon roles, so here's it is!
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/atlas-links/datalake/allison/icon-fa5-brands/tutorial/connect#add-the-mongo-shell-to-your-system-path
=> DOP-1165: adds support for the icon-fa5-brands, which was missed

src/components/ComponentFactory.js
[[JIRA](https://jira.mongodb.org/browse/DOP-1227)] [[MongoCLI Staging](https://docs.mongodb.com/mongocli/stable/reference/atlas/cluster-create/#output)] Adds support for the `:sub:` and `:sup:` aliases of `:subscript:` and `:superscript:`.
=> DOP-1227: Add subscript and superscript support

package-lock.json, package.json, src/components/Navbar.js, src/components/Searchbar.js, src/components/Searchbar/SearchDropdown.js, src/components/Searchbar/Searchbar.js, src/components/Searchbar/index.js, tests/unit/__snapshots__/Navbar.test.js.snap
[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/guides/jordanstapinski/searchbar/)
(The target branch is the feature branch for the project, also the addition to package/lock.json has been approved)
This PR adds in a basic searchbar (not mobile-responsive, desktop only) which uses LeafyGreen components. Locally I disabled the navbar in docs-tools, but this will show up even without doing so.
I updated the `tabindex` but also noticed this is a bit odd on Safari so will continue to look into that
Curious how the CSS style is compared to what the team traditionally does, so feedback there would be helpful!
=> [DOP-1219] Searchbar Part 1: Desktop Searchbar UI

package-lock.json, package.json
[Changelog](https://github.com/mongodb/leafygreen-ui/blob/master/packages/text-input/CHANGELOG.md)
Fixes the aria-labelledby casing on the TextInput (which I also was noticing in the console). Didn't think this one needed to be staged :)
=> Upgrade Leafy Text Input to 3.0.1

src/components/CSSWrapper.js, src/components/VersionDropdown.js, src/hooks/use-site-metadata.js, src/utils/site-metadata.js
[[JIRA](https://jira.mongodb.org/browse/DOP-1212)] I wasn't able to generate a staging link demonstrating this functionality because mut “places each stage under a unique namespace computed from an arbitrary username and branch” ([source](https://github.com/mongodb/mut/blob/master/mut/stage.py#L567-L568)). However, you can test this by building on your machine:
1. Configure your `.env.production` file:
```
GATSBY_SITE=bi-connector
GATSBY_PARSER_USER=sophstad
GATSBY_PARSER_BRANCH=master
GATSBY_SNOOTY_DEV=true
PATH_PREFIX=bi-connector/v2.13
```
2. `npm run build && npm run serve`
3. Inspect the URLs present in the version selector dropdown. They should include the prefix and the new version to navigate to.
Note that I also included a small bug fix in the `CSSWrapper` component.
=> DOP-1212: Correctly generate version URLs for production deploys

tests/testSetup.js, tests/unit/Searchbar.test.js, tests/unit/__snapshots__/Navbar.test.js.snap, tests/unit/__snapshots__/Searchbar.test.js.snap
This PR adds some simple unit snapshot tests for the Searchbar (closed vs open state) and augment the existing Navbar snapshot based on where #228 is going. For the `useMedia` hook I had to create a simple mock for it in `testSetup`.
=> [DOP-1219] Searchbar Part 3: Testing

src/components/Searchbar/Pagination.js, src/components/Searchbar/SearchDropdown.js, tests/unit/Pagination.test.js, tests/unit/__snapshots__/Pagination.test.js.snap
[Staging Guides](https://docs-mongodbcom-staging.corp.mongodb.com/master/guides/jordanstapinski/pagination-component/)
[Staging Ecosystem](https://docs-mongodbcom-staging.corp.mongodb.com/master/ecosystem/jordanstapinski/pagination-component/)
^ For these I just left the dropdown open for easier inspection. That is not a change made in this PR.
This PR adds a generic `Pagination` component to be used with search results. I also added interaction and snapshot testing for it. This component lets a parent component control the current page and enables/disables actions accordingly.
=> DOP-1220 Search Results Part 1: Generic Pagination

src/components/ComponentFactory.js, src/components/Roles/Abbr.js, src/components/Rubric.js
[[JIRA](https://jira.mongodb.org/browse/DOP-1256)] [[Atlas Staging](https://docs-mongodbcom-staging.corp.mongodb.com/snooty-setup/cloud-docs/sophstad/DOP-1256/reference/api/apiKeys-orgs-get-one)] <— [source](https://github.com/schmalliso/cloud-docs/blob/snooty-setup/source/includes/api/base-api-uri.rst)
- Support `rubric` directive
- Bonus: add error handling to `:abbr:` role component
=> DOP-1256: Implement Rubric directive

src/components/Navbar.js, src/components/Searchbar/Pagination.js, src/components/Searchbar/SearchDropdown.js, src/components/Searchbar/SearchResult.js, src/components/Searchbar/SearchResults.js, src/components/Searchbar/Searchbar.js, src/hooks/use-click-outside.js, src/utils/search-params-to-url.js
[Ecosystem Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/ecosystem/jordanstapinski/fetch-results/)
[Guides Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/guides/jordanstapinski/fetch-results/)
This PR adds the ability to pull results from Marian and display (specifically for Desktop) in the searchbar. One idea to note is Deepak wants us to abstract Marian-specific details out of the component if possible for future re-use. As such I decided to move Marian references into utils (such as `searchParamsToUtil`) and will continue to expand on that as I continue to work on this ticket.
Highlighting relevant text, mobile responsiveness, and abstracting the marian result/removing property will come in separate PRs, this one is large enough :)
=> DOP-1220 Search Results Part 2: Desktop Search Results

jest.config.js, src/components/Navbar.js, src/components/Searchbar/Searchbar.js, src/utils/get-searchbar-results-from-json.js, tests/unit/__snapshots__/Navbar.test.js.snap, tests/unit/__snapshots__/Pagination.test.js.snap, tests/unit/__snapshots__/Searchbar.test.js.snap, tests/utils/get-searchbar-results-from-json.test.js
[Ecosystem Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/ecosystem/jordanstapinski/abstract-marian/)
[Guides Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/guides/jordanstapinski/abstract-marian/)
This PR pulls the property out of the search title and abstracts out data postprocessing after fetching the search results to a helper function called `getSearchbarResultsFromJSON`. This function adds the ability to pull the property title out as well as optionally limit the number of returned results. We also will use this on the dedicated search page.
Allison would like us to limit dropdown results to at most 9 (3 pages), so this helper function gives us that functionality (with tests!).
I also updated the relevant snapshots since I did not do so in the …
=> DOP-1220 Part 3: Abstract Marian Result Parsing, Limit Results

src/components/Searchbar/CondensedSearchbar.js, src/components/Searchbar/ExpandedSearchbar.js, src/components/Searchbar/SearchTextInput.js, src/components/Searchbar/Searchbar.js
[Ecosystem Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/ecosystem/jordanstapinski/refactor-search-component/)
[Prior Branch Ecosystem Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/ecosystem/jordanstapinski/mobile-results/)
[Guides Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/guides/jordanstapinski/refactor-search-component/)
This PR eliminates some building technical debt by splitting the `Searchbar` component into four components:
- The main `Searchbar` parent which acts as an overall controller of the experience
- `CondensedSearchbar` which is the magnifying glass to pop-open the searchbar
- `ExpandedSearchbar` which is the searchbar open
- `SearchTextInput` which is the custom LeafyGreen text input
These were all in one …
=> Refactor Searchbar into Smaller Components

src/components/Navbar.js, src/components/Searchbar/SearchContext.js, src/components/Searchbar/SearchResult.js, src/components/Searchbar/SearchTextInput.js, src/components/Searchbar/Searchbar.js
[Ecosystem Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/ecosystem/jordanstapinski/selectively-autofocus/)
This PR adds a new prop to the `Searchbar` to control when `autofocus` is enabled. Previously we would `autofocus` all the time on the searchbar, but this PR chnages the behavior a bit for a good UX:
- If the searchbar is expanded by default (desktop), then we do not autofocus the searchbar
- If the searchbar is condensed by default (mobile/~1200px), when the user clicks the magnifying glass to open the searchbar then we do autofocus, since they should be able to type right away.
Using the SearchContext this was easy to add without prop drilling.
Here is what should happen in the "condensed --> expanded" action. This way the user already has the intent to search, …
=> Selectively Autofocus Search Input

src/components/Searchbar/AdvancedFiltersPane.js, src/components/Searchbar/SearchDropdown.js, src/components/Searchbar/SearchResults.js
[Ecosystem Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/ecosystem/jordanstapinski/filter-navigation/)
[Guides Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/guides/jordanstapinski/filter-navigation/)
This PR sets up a simple navigation between the results pane and a new `AdvancedFiltersPane` which will be used to display the advanced filters.
- Adds the Advanced Filters button in the results pane footer
- Adds an empty new `AdvancedFiltersPane`
- Adds logic for navigating back to the original results pane (easy to split the handler from the cancel vs apply search criteria buttons)
=> DOP-1221 Part 1: Basic Filter Pane Navigation

src/components/Select.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/DOP-909/landing/jordanstapinski/select-updates/legacy)
This PR fixes a few issues with the `Select` component:
1. Fixes the focus border so it again appears normally and does not appear on dropdown elements (we have a hover state here already)
2. Adds max-height/scroll for > 160px (discussed with Allison)
3. Fixes text overflow ellipsis to actually work by using display block :) 
4. Fixes size of element changing when open vs closed
5. Removes disabled selects from the taborder
=> Update misc select component styling

src/components/ComponentFactory.js, src/components/Field.js, src/components/FieldList.js, src/components/Paragraph.js, tests/unit/Field.test.js, tests/unit/FieldList.test.js, tests/unit/__snapshots__/Field.test.js.snap, tests/unit/__snapshots__/FieldList.test.js.snap, tests/unit/data/FieldList.test.json
[[JIRA](https://jira.mongodb.org/browse/DOP-1296)] [[Realm Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/sophstad/DOP-1296/functions/utilities)] [[Manual Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/manual/sophstad/DOP-1296/reference/method/db.collection.aggregate)] 
- Render directive fields as tables.
- Front-end component of https://github.com/mongodb/snooty-parser/pull/187.
- Tip: Search for "returns" on the staging link pages to find the `:returns:` field in action
=> DOP-1296: Render Fields

src/components/Searchbar/AdvancedFiltersPane.js, src/components/Searchbar/SearchDropdown.js, src/components/Searchbar/SearchFilters.js, src/components/Searchbar/Searchbar.js, src/hooks/use-marian-manifests.js, src/utils/search-params-to-url.js
[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/ecosystem/jordanstapinski/advanced-filters-redux/)
[Updated Relevant Invision](https://mongodb.invisionapp.com/d/#/console/19596736/417891823/preview)
This PR adds the UI for filtering search results. I was additionally going to include the logic to actually filter here as well but after speaking with Elle and Allison I want to change my approach there so I figured this could be split into two PRs. This PR does the following:
1. Flips footer button ordering of pagination and "Advanced Filters" by request from Allison
2. Adds a `reset` button on the advanced filter pane (that does not do anything yet)
3. Adds the search dropdowns to the advanced filter pane, with logic to control enabled/disabled
4. Adds a custom hook …
=> DOP-1312 Actually Filtering Part 1 (UI only/non-functional)

src/components/Searchbar/Searchbar.js
[JIRA](https://jira.mongodb.org/browse/DOP-1340)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/ecosystem/jordanstapinski/search-instrumentation-focus/)
Adding Elle to verify reporting structure/needs (these were a bit less defined)
This PR adds two more reporting metrics for the search experience:
- `SearchFocus` reports when the searchbar was clicked into and is focused. It does not report any additional information
- `SearchBlur` reports when the searchbar was clicked out of. It also reports the existing query the user has tried searching for
Similar to Part 1 you can see the reports in the network tab. Here is one:
=> DOP-1340 Part 2: Focus/Blur Instrumentation

src/components/SearchResults/SearchResults.js
[JIRA](https://jira.mongodb.org/browse/DOP-1339)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/DOP-1337/landing/jordanstapinski/hover-issue/search?q=stitch) (Search something then check out the results page)
This PR fixes the previous hover issue where placing a cursor between two rows on the search results page would just opaque out all results/ The solution here was to place a transparent pseudoelement over the entire new row height.
=> DOP-1339: Fix Search Results Hover Gaps

src/components/SearchResults/EmptyResults.js, src/components/SearchResults/SearchResults.js
[JIRA](https://jira.mongodb.org/browse/DOP-1339)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/DOP-1337/landing/jordanstapinski/results-empty-state/search)
[InVision](https://mongodb.invisionapp.com/d/#/console/19596736/422509204/preview)
This PR adds the empty state for search results centered vertically on the page. Positioning was a bit wonky so super open to suggestions there.
I spoke to Allison and we will be keeping the footer, so the blank template still is fine.
=> DOP-1339 Part 3: Search Results Empty State

src/components/SearchResults/EmptyResults.js, src/components/Searchbar/ExpandedSearchbar.js, src/components/Searchbar/SearchResult.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/DOP-1337/landing/jordanstapinski/focus-text-search/search)
This PR addresses a comment from #260 involving making the empty state magnifying glass clickable. In addition, we also made the magnifying glass in the expanded searchbar clickable.
I also found a bug where using arrow keys with empty search results threw an error so I added the quick fix for that here as well.
=> Add onClick for magnifying glasses

gatsby-ssr.js
[[JIRA](https://jira.mongodb.org/browse/DOP-1407)] [[Datalake Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/datalake/sophstad/master/)] Populate `<title>` tag during Server-Side Rendering so that Marian can access it.
To test, open the staging link and view page source. You can see that the `<title>` tag is no longer empty. [Here](https://docs-mongodbcom-staging.corp.mongodb.com/master/datalake/sophstad/master/reference/cli/stores/drop-store) is a page with monospace in the title. In its source:
```html
<title data-react-helmet="true">dropStore — MongoDB Atlas Data Lake</title>
```
=> DOP-1407: Populate page title on server

src/components/DocumentBody.js, src/components/Footnote.js, src/components/FootnoteReference.js, src/components/footnote-context.js, src/layouts/index.js
[[Cloud Staging](https://docs-mongodbcom-staging.corp.mongodb.com/snooty-setup/cloud-docs/sophstad/footnote-context/database-auditing#id2)] I noticed a bad case of [prop drilling](https://kentcdodds.com/blog/prop-drilling/) w.r.t. footnotes, so this PR adds a small [Context](https://reactjs.org/docs/context.html) to handle that data.
=> Use Context for footnotes

src/layouts/index.js, src/templates/blank.js, src/templates/document.js, src/templates/ecosystem-index.js, src/templates/guide.js, src/templates/guides-index.js, src/templates/landing.js
[DOP-1420] [[Datalake Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/datalake/sophstad/DOP-1420/)] [[Landing Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/landing/sophstad/DOP-1420/)] [[Guides Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/guides/sophstad/DOP-1420/)] [[Drivers Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/drivers/sophstad/DOP-1420/)] Render navbar in layout component instead of in each template. This mean that the same instance of the navbar is mounted no matter which template is in use.
Notice how in the Drivers staging link in #268, navigating from the landing page to a content page would result in the navbar re-rendering and the search bar re-animating. This PR fixes that!
=> DOP-1420: Render Navbar in layout component

src/components/SearchResults/SearchResults.js
[Landing Staging](https://docs-mongodborg-staging.corp.mongodb.com/DOP-1337/landing/jordanstapinski/area-found-from/)
[GA Doc](https://docs.google.com/document/d/1L5HTF5BV3_iuNm-vGKBubwYUCPyq7nIQGTCaJ8GTFq0/edit)
This short PR switches a typo instrumentation label from `areaFound` to `areaFrom` for the search results page.
=> Switch metric label from areaFound to areaFrom

src/components/Heading.js
Fixes #281; React requires use of `className` instead of `class` ([source](https://reactjs.org/docs/dom-elements.html#classname)).
=> fix: "class" -> "className"

src/components/ComponentFactory.js, src/components/Roles/Highlight.js
[DOP-1492] [[Manual Staging](https://docs-mongodbcom-staging.corp.mongodb.com/test2/docs/sophstad/DOP-1492/reference/map-reduce-to-aggregation-pipeline#map-reduce-to-aggregation-pipeline-translation-table)] Render the following roles:
- `:highlight-red:`
- `:highlight-yellow:`
- `:highlight-green:`
- `:highlight-blue:`
=> DOP-1492: Render highlight roles

src/components/Sidebar.js, src/components/TableOfContents.js, src/styles/sidebar.module.css, tests/unit/TableOfContents.test.js, tests/unit/__snapshots__/TableOfContents.test.js.snap
[DOP-1006] [[BI Connector Staging](https://docs-mongodbcom-staging.corp.mongodb.com/snooty/bi-connector/sophstad/DOP-1006/)] [[Manual Staging](https://docs-mongodbcom-staging.corp.mongodb.com/test2/docs/sophstad/DOP-1006/)] Fix title and version selector in the sidebar so that only the table of contents scrolls.
=> DOP-1006: Fix version selector and title in dropdown

src/components/VersionDropdown.js, src/utils/site-metadata.js, tests/unit/VersionDropdown.test.js
[DOP-1549] [[Charts Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/charts/sophstad/master/)] [[BI Connector Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/bi-connector/sophstad/DOP-1549/)] Use values from the [`git.branches.published` table](https://github.com/mongodb/docs-worker-pool/blob/meta/publishedbranches/docs-charts.yaml#L15-L18)  of the published-branches.yaml file. These are the values that correspond to the git branches of each version, and also to the slug that should appear in the URL. Previously, the component was using the values that appear in the `version.active` table, which understandably worked out badly!
=> DOP-1549: Fix version dropdown links

src/components/RightColumn.js, src/components/Select.js, src/components/TabSelectors.js, src/components/tab-context.js, src/layouts/index.js, src/templates/document.js
[DOP-1529] [[Atlas Staging](https://docs-mongodbcom-staging.corp.mongodb.com/snooty-setup/cloud-docs/sophstad/DOP-1529-selector/tutorial/connect-to-your-cluster)] Adds selector dropdown to pages that include `tabs-pillstrip` directives. The selected drivers tab should update whenever a dropdown option is selected, and vice versa.
**Note:** The dropdown only displays on laptop screens; tablet and mobile will be included in a forthcoming PR.
=> DOP-1529 (2): Add tab selector to non-mobile screens

src/components/DocumentBody.js, src/components/Heading.js, src/components/Select.js, src/components/TabSelectors.js, src/components/Widgets/FeedbackWidget/FeedbackHeading.js, src/components/Widgets/FeedbackWidget/components/StarRating.js, src/templates/guide.js, tests/unit/FeedbackWidget.test.js
[DOP-1529] [[Cloud Docs Staging](https://docs-mongodbcom-staging.corp.mongodb.com/snooty-setup/cloud-docs/sophstad/DOP-1529-mobile/tutorial/connect-to-your-cluster)]
- On mobile, replace feedback widget with a language selector (if the page has one)
- Remove more references to pillstrips, particularly in Guides
=> DOP-1529 (3): Add mobile support for tab selector

src/components/ComponentFactory.js, src/components/Root.js, src/components/Step.js, src/components/Steps.js
[DOP-1667] [[BI Connector Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/bi-connector/sophstad/DOP-1667/)]
- Render children of `root` nodes
- Render children of `steps` nodes
- Simplify `Include` component, which used to handle numbering of `Step` components
=> DOP-1667: Fix root and step components

src/components/Tabs.js, src/components/tab-context.js, tests/unit/Tabs.test.js
[DOP-1529] [[Atlas Staging](https://docs-mongodbcom-staging.corp.mongodb.com/snooty-setup/cloud-docs/sophstad/DOP-1529-hide/resilient-application)] Content should toggle on the staging link when a new language is selected in the dropdown (this is especially evident in the code blocks). Tabs that appear on pages without language selectors still render.
=> DOP-1529 (5): Auto hide tabs on page with selector

src/components/ComponentFactory.js, src/components/ListTable.js, src/components/MongoWebShell.js, tests/unit/MongoWebShell.test.js, tests/unit/Tabs.test.js, tests/unit/__snapshots__/MongoWebShell.test.js.snap, tests/unit/data/MongoWebShell-default.test.json, tests/unit/data/MongoWebShell-v4.2.test.json
[[JIRA Ticket](https://jira.mongodb.org/browse/DOP-1334)]
[[Server Staging Link: /tutorial/update-documents-with-aggregation-pipeline](https://docs-mongodbcom-staging.corp.mongodb.com/DOP-1334/manual/raymundrodriguez/DOP-1334/tutorial/update-documents-with-aggregation-pipeline)]
[[Server Staging Link: /tutorial/getting-started](https://docs-mongodbcom-staging.corp.mongodb.com/DOP-1334/manual/raymundrodriguez/DOP-1334/tutorial/getting-started)]
This PR allows the MongoDB Web Shell to be rendered on server docs. 
Staging link was built with a locally changed version of `docs`, using
```
.. mongo-web-shell::
:version: 4.2
```
instead of the `.. raw::` directive. Additionally, instances of `.. only:: website` were changed to `.. cond:: html` for the staging link page.
=> DOP-1334: Implement MongoWebShell component

src/components/ComponentFactory.js, src/components/Extract.js
[[Atlas Staging](https://docs-mongodborg-staging.corp.mongodb.com/snooty-setup/cloud-docs/sophstad/fix-extracts/)] Fix problem where extract nodes would block rendering. New build log indicates that these nodes are no longer throwing errors:
```
$ npm run build
> snooty@0.7.0 build /Users/sophstad/edu/snooty
> gatsby build --prefix-paths
success open and validate gatsby-configs - 0.094s
success load plugins - 0.708s
success onPreInit - 0.054s
success delete html and css files from previous builds - 0.009s
success initialize cache - 0.029s
success copy gatsby files - 0.110s
success onPreBootstrap - 0.041s
success createSchemaCustomization - 0.010s
success Checking for changed pages - 0.011s
success source and transform nodes - 27.968s
success building schema - 0.221s
info Total nodes: …
```
=> Dive into extract node children

src/components/Code.js
[[JIRA Ticket](https://jira.mongodb.org/browse/DOP-1660)]
[[Realm Staging: /functions/utilities](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/raymundrodriguez/DOP-1660/functions/utilities)]
[[Drivers Staging: /security/client-side-field-level-encryption-guide](https://docs-mongodbcom-staging.corp.mongodb.com/master/drivers/raymundrodriguez/DOP-1660/security/client-side-field-level-encryption-guide)]
Currently, a code block nested in a table results in the code block expanding to the max size of its longest row, and thus making the whole table and its contents widen with them. This PR makes code blocks fit within the width of a table but also gives them a minimum width (so blocks aren't too narrow if nested in an admonition in a table, for example).
Bonus:
- C++ language …
=> DOP-1660: Fix code blocks overflowing when nested in tables

.gitignore, src/html.js, static/scripts/segment.js
[[Datalake Staging](https://docs-mongodbcom-staging.corp.mongodb.com/DOP-1643/datalake/sophstad/segment-fix/)] Get rid of `Segment snippet included twice.` error as thrown by the GA plugin. GTM handles loading of Segment on its own.
=> Remove segment script

package-lock.json, package.json, src/components/Tabs.js, tests/unit/Tabs.test.js
[DOP-1014] [[Datalake Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/datalake/sophstad/DOP-1014/)] [[Atlas Staging](https://docs-mongodbcom-staging.corp.mongodb.com/snooty-setup-v0.7.2/cloud-docs/sophstad/DOP-1014/)] Implementation details borrow from DevHub: https://github.com/mongodb/devhub/pull/528
Note that the unexpected hover behavior (where the border does not become green after clicking) is a known limitation and a consequence of fixing a bug that Jordan explained [here](https://github.com/mongodb/devhub/pull/528#discussion_r502477433).
=> DOP-1014: Use LeafyGreen Tabs

src/components/ComponentFactory.js, src/components/Describe.js, src/components/Roles/Command.js
[DOP-1738] [[Database Tools Staging](https://docs-mongodbcom-staging.corp.mongodb.com/snooty-setup/database-tools/sophstad/DOP-1738/mongostat#fields)] Bonus: add support for `:command:`.
=> DOP-1738: Render describe directive

src/utils/parse-marian-manifests.js, tests/utils/data/parsed-marian-manifests.json
`Atlas Datalake` ➡️ `Atlas Data Lake`
=> DOP-1759: Fix typo

src/components/Widgets/FeedbackWidget/context.js, src/utils/segment.js
Fixes a bug where a tracker/ad blocker (specifically uBlock Origin in this case) blocks Segment and prevents the feedback widget from opening.
Given that a significant portion of developers use ad blockers, this may lead to an increase in feedback.
=> Allow users with adblockers to open the feedback widget

src/components/ComponentFactory.js, src/components/ReleaseSpecification.js, tests/unit/ReleaseSpecification.test.js, tests/unit/__snapshots__/ReleaseSpecification.test.js.snap, tests/unit/data/ReleaseSpecification.test.json
[[Jira Ticket](https://jira.mongodb.org/browse/DOP-1766)]
[[Server Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/manual/raymundrodriguez/DOP-1766/tutorial/install-mongodb-on-windows-unattended#run-the-windows-installer-from-the-windows-command-interpreter)]
[[Link to same server page in legacy](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows-unattended/#run-the-windows-installer-from-the-windows-command-interpreter)]
Instances of the `release_specification` directive seem to basically act as containers for code blocks. Using ComponentFactory here will allow for flexibility in case the directive acts as a container for other components in the future. Not sure if this should be stricter and we should instead only accept/expect code blocks
=> DOP-1766: Add frontend support for release_specification

src/components/ComponentFactory.js
[DOP-1900] [[Database Tools Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/database-tools/sophstad/DOP-1900/)] Ignore `named_reference` nodes introduced in https://github.com/mongodb/snooty-parser/pull/279.
=> DOP-1900: Ignore named_reference nodes

src/components/DefinitionListItem.js, src/components/Paragraph.js, src/components/Tabs.js, tests/unit/__snapshots__/DefinitionList.test.js.snap
[DOP-1825] [[BI Connector Staging](https://docs-mongodbcom-staging.corp.mongodb.com/483d743/v0.8.5-test/bi-connector/sophstad/DOP-1825/)] [[Manual Staging](https://docs-mongodbcom-staging.corp.mongodb.com/snooty-setup/docs/sophstad/DOP-1825/)] Omit `<p>` tags from dictionary list items with only one paragraph. If multiple paragraphs, ensure 0 margin between term and description.
Includes bonus fix to present non-`tab` nodes from rendering as children of `tabs` node.
=> DOP-1825: Fix definition list rendering

src/components/Sidebar.js, src/components/TableOfContents.js, src/components/toc-context.js, src/utils/ends-with.js, src/utils/is-active-toc-node.js, src/utils/is-current-page.js, src/utils/is-selected-toc-node.js, tests/unit/TableOfContents.test.js
[DOP-1943] [[Realm Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/sophstad/DOP-1943/tutorial/react-native)] Fix toctree bug where pages that ended with the same string were mistakenly both identified as active.
=> DOP-1943: Fix double active page bug

gatsby-node.js, src/components/DocumentBody.js, src/layouts/index.js, src/templates/document.js, src/templates/guide.js, src/templates/guides-index.js
[DOP-1962] [[BI Connector Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/bi-connector/sophstad/DOP-1962/) [[Landing Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/landing/sophstad/DOP-1962/)] [[Drivers Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/drivers/sophstad/DOP-1962/)] Reduce "static" data being written to `page-data.json` files:
- Only pass a document's `ast` field into each page's context (previously we were passing the entire document as returned by Realm)
- Ensure that the `static_files` field found in a property's metadata doc is also omitted from `page-data.json`
Included a few staging links to ensure that the various templates are still ingesting page data correctly.
=> DOP-1962: Reduce page-data.json bloat

src/components/Link.js, src/components/RefRole.js, tests/unit/Link.test.js, tests/unit/__snapshots__/Breadcrumbs.test.js.snap, tests/unit/__snapshots__/Card.test.js.snap, tests/unit/__snapshots__/InternalPageNav.test.js.snap, tests/unit/__snapshots__/Link.test.js.snap, tests/unit/__snapshots__/TableOfContents.test.js.snap, tests/unit/__snapshots__/Target.test.js.snap
[DOP-1985] [[Atlas Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/cloud-docs/sophstad/DOP-1965/)] Enforce trailing slashes across Snooty internal links.
=> DOP-1965: Enforce trailing slashes

src/components/Link.js, tests/unit/Link.test.js, tests/unit/__snapshots__/Link.test.js.snap
[DOP-1971] [[Cloud Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/cloud-docs/sophstad/DOP-1971/tutorial/delete-atlas-account/#email-atlas-support-to-finalize-deletion-process)] I couldn't think of any other special-case URL formats besides `mailto:` so I just went with the easiest approach... but if you can think of other use cases I'd be happy to reassess!
=> DOP-1971: Correctly handle mailto links

src/components/RefRole.js, tests/unit/__snapshots__/Target.test.js.snap
[DOP-1950] [[Data Lake Staging](https://docs-mongodbcom-staging.corp.mongodb.com/HEAD/datalake/sophstad/DOP-1950/tutorial/getting-started/)] Links to the index page were mistakenly being rendered as `<a href="/index#hash">`. They should be `<a href="/#hash">`. Check to see if we are dealing with a link to the index page and update the filename accordingly.
To test: visit the `/tutorial/getting-started` page and click on the "Billing" link in the note toward the bottom of the page. It should work!
=> DOP-1950: Fix handling of RefRole links to index page

src/layouts/index.js
[DOP-1977] [[Manual Staging](https://docs-mongodborg-staging.corp.mongodb.com/snooty-setup/docs/sophstad/DOP-1977/)] Override the `.hidden` class introduced in legacy CSS so that `display: none` is _not_ applied. This ensures that "hidden" elements will still appear in the DOM so that links to them are valid.
=> DOP-1977: Update hidden class

src/components/Navbar.js, src/components/RightColumn.js, src/components/SearchResults/SearchResults.js, src/components/Searchbar/SearchDropdown.js, src/components/Widgets/FeedbackWidget/FeedbackTab.js, src/templates/document.js, src/utils/display-none.js, tests/unit/FeedbackWidget.test.js
[[Jira Ticket](https://jira.mongodb.org/browse/DOP-1988)]
[[Node Driver Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/node/raymundrodriguez/DOP-1988/)]
**Changes:**
Added css media queries for `RightColumn` and `FeedbackTab` to prevent them from rendering on mobile load.
- On a mobile screen, go to any page on staging to see that neither components load before rendering properly. Desktop screen should load and look the same as deployed site.
- See that Cumulative Layout Shift (CLS) score is generally down (or around the same score depending on page) on staging when compared to deployed site. This can be checked manually by using the `Performance` tab in Chrome Dev Tools while on a mobile responsive screen size, or using the [PageSpeed …
=> DOP-1988: Prevent RightColumn and FeedbackTab from appearing on mobile first

src/components/ListTable.js, tests/unit/__snapshots__/ListTable.test.js.snap
We only want to remove a table header's styling if there isn't actually a header 😅 this PR fixes that!
=> Fix table unstyling

.husky/pre-commit, package-lock.json, package.json
- Move installation from `postinstall` to `prepare` as per https://github.com/typicode/husky/pull/890
- Fix double invocation of `lint-staged`
=> Fix Husky setup

src/components/ListTable.js, tests/unit/__snapshots__/ListTable.test.js.snap
[DOP-2023] [[BI Connector Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/bi-connector/sophstad/DOP-2023/reference/drdl/#field-types)]
- Apply light grey background to stub (`<th>`) cells
- Vertical align table contents to top
=> DOP-2023: LeafyGreen table fixes

src/components/ListTable.js, tests/unit/__snapshots__/ListTable.test.js.snap
[DOP-1914] [[Atlas Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/cloud-docs/sophstad/DOP-1914/reference/api/clusters-modify-one/#request-body-parameters)] Wrap table content to avoid unmanageable overflows.
=> DOP-1914: Wrap table content

src/components/VersionModified.js, tests/unit/__snapshots__/VersionModified.test.js.snap
[DOP-2021] [[Manual Staging](https://docs-mongodbcom-staging.corp.mongodb.com/snooty-setup/docs/sophstad/DOP-2021/reference/program/mongod/#std-option-mongod.--sslCertificateSelector)] Render all arguments of `versionchanged`, `versionadded`, and `deprecated` directives on same line as the version number. Also render the first child on this line. If there are multiple children (i.e. more than one paragraph), apply `<p>` tags as expected.
=> DOP-2021: Render versionmodified arguments on same line

src/components/VersionDropdown.js
Fix links generated when using a path prefix that contains a slash within it. Previously, we used to split up a `pathPrefix` by slashes to separate its project and its version—e.g. splitting `/bi-connector/v4.0` became `['', 'bi-connector', 'v4.0']`.
The node docs use a path prefix that contains an additional slash (`/drivers/node/v3.6`) which introduced a problem. Now, identify the version via the string that appears after the final slash.
Staging would be pretty useless here as the link would not adhere to the path used in production, but I did some logging to verify and will test later in the integration environment!
=> Fix version dropdown link generation

src/components/Tabs.js, tests/unit/Tabs.test.js
DOP-1947
https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/cassidy.schaufele/DOP-1947/sdk/ios/data-types/embedded-objects/
Replicates some of the logic from here: https://github.com/mongodb/docs-tools/blob/master/themes/mongodb/src/js/componentTabs.js#L94-L133
Also adds a minor delay on scroll to account for renders in anything dependent on `TabContext` propagation.
Utilizes an empty `<div/>` tag with a ref to anchor our scroll logic to the parent tabset clicked.
=> DOP-1947: Anchor scroll to clicked tab component

__mocks__/gatsby.js, gatsby-node.js, src/components/BreadcrumbSchema.js, src/components/Breadcrumbs.js, src/templates/document.js, src/utils/get-plaintext.js, src/utils/setup/transform-breadcrumbs.js, tests/unit/BreadcrumbSchema.test.js, tests/unit/Breadcrumbs.test.js, tests/unit/__snapshots__/BreadcrumbSchema.test.js.snap, tests/unit/__snapshots__/Breadcrumbs.test.js.snap, tests/unit/data/Breadcrumbs.test.json
DOP-1975
[Compass Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/compass/sophstad/DOP-1975/)
- Attach page titles (both rich & plaintext) in `gatsby-node.js` to minimize logic performed by the breadcrumb components
- Remove dependency on legacy `mongodb-docs.css` in breadcrumb render
- Will ask Croud team to perform acceptance testing before merging
=> DOP-1975: Add breadcrumb schema and simplify component

src/components/Contents.js, src/components/contents-context.js, src/hooks/useActiveHeading.js, src/layouts/index.js
DOP-2099
- [Compass](https://docs-mongodbcom-staging.corp.mongodb.com/master/compass/sophstad/DOP-2099/)
- [Realm](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/sophstad/DOP-2099/)
- Followup to https://github.com/mongodb/snooty-parser/pull/297
- Took Raymund's work from the `docs-nav` feature branch to leverage improved behavior via `IntersectionObserver` ([source](https://github.com/mongodb/snooty/blob/dfee59d6c9f0fe58e648bf47ec06de30ff4e1dc0/src/components/contents-context.js)). I can take care of merging this work into the feature branch!
- Move active heading logic into a separate custom hook
=> DOP-2099: Use parser data for "On this page" box

src/components/Searchbar/ExpandedSearchbar.js, src/components/Searchbar/Searchbar.js, tests/unit/__snapshots__/Searchbar.test.js.snap
DOP-2083
https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/cassidy.schaufele/DOP-2083/
The event listener for the keydown event was inexplicably triggering on page load - this is why arrow down navigation wasn't working until clicking into another element, or until clicking into and then out of the searchbar.
This changeset changes the event listener to only activate when the searchbar has focus, and passes `isFocused` into `ExpandedSearchbar`. We had the prop present in `ExpandedSearchbar` before, we just never drilled it down from `Searchbar`.
=> DOP-2083: Only keydown event listen on searchbar focus

src/components/ComponentFactory.js, src/components/landing/Card.js, src/components/landing/CardGroup.js
DOP-2113
- https://docs-mongodbcom-staging.corp.mongodb.com/nav/landing/sophstad/DOP-2113/
- https://docs-mongodbcom-staging.corp.mongodb.com/nav/landing/sophstad/DOP-2113/develop-applications/
- https://docs-mongodbcom-staging.corp.mongodb.com/nav/landing/sophstad/DOP-2113/view-analyze/
- https://docs-mongodbcom-staging.corp.mongodb.com/nav/landing/sophstad/DOP-2113/launch-manage/
- [docs-landing content branch](https://github.com/sophstad/docs-landing/tree/nav)
- Render new `extra-compact` cards that appear on docs-landing pages
- Stack (rather than carousel) these cards on mobile
- This branch has been opened against `master` rather than `docs-nav` so that it can be easily merged into PLP. Since we don't currently have any `extra-compact` cards in use, landing page render will continue …
=> DOP-2113: Render extra-compact cards

package-lock.json, package.json, src/components/Sidebar.js, src/components/VersionDropdown.js
DOP-2105 (updates #384)
- [BI Connector v2.14](https://docs-mongodbcom-staging.corp.mongodb.com/master/bi-connector/sophstad/DOP-2105-update/)
- [BI Connector v2.13](https://docs-mongodbcom-staging.corp.mongodb.com/v2.13/bi-connector/sophstad/DOP-2105-update/)
- [@leafygreen-ui/select@2.1.0](https://github.com/mongodb/leafygreen-ui/releases/tag/%40leafygreen-ui/select%402.1.0) adds support for `allowDeselect`, so we no longer have to hide this option ourselves 💯
=> DOP-2105: Use allowDeselect prop

src/components/Banner.js, src/components/BreadcrumbContainer.js, src/components/Breadcrumbs.js, src/components/EcosystemHomepageTiles.js, src/components/MainColumn.js, src/templates/document.js, src/templates/ecosystem-index.js, src/utils/stitch.js, tests/unit/Banner.test.js, tests/unit/BreadcrumbContainer.test.js, tests/unit/Breadcrumbs.test.js, tests/unit/__snapshots__/BreadcrumbContainer.test.js.snap, tests/unit/__snapshots__/Breadcrumbs.test.js.snap
DOP-1841
[Drivers Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/drivers/raymundrodriguez/DOP-1841/)
[Atlas Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/cloud-docs/raymundrodriguez/DOP-1841/)
[Landing Staging](https://docs-mongodbcom-staging.corp.mongodb.com/docs-nav/landing/raymundrodriguez/DOP-1841/view-analyze/)
* Separated `BreadcrumbContainer` into its own component so `BreadcrumbSchema` is added to page source.
* Created Realm function `fetchProjectParents` to return the parents of a given project.
* Re-added some code to `Document.js` that were removed during one of the merges from `master` to `docs-nav`.
=> DOP-1841: Update page breadcrumbs to fetch parents

src/components/Sidenav.js
DOP-2115
[Landing Staging](https://docs-mongodborg-staging.corp.mongodb.com/docs-nav/landing/raymundrodriguez/DOP-2115/
)
* Added additional links to the bottom of the new SideNav.
* I set one of the elements of LG SideNav to be a flex item so that we can have a child flex grow. Open to any better alternatives so that we don't have to modify the css of the SideNav!
=> DOP-2115: Add Additional Links to SideNav

package-lock.json, package.json, src/components/Banner.js, src/components/BreadcrumbContainer.js, src/components/BreadcrumbSchema.js, src/components/Breadcrumbs.js, src/components/Header.js, src/components/RootProvider.js, src/components/SidebarBack.js, src/components/Sidenav.js, src/components/navigation-context.js, src/layouts/index.js, src/templates/document.js, src/templates/ecosystem-index.js, src/templates/landing.js, src/utils/realm.js, src/utils/stitch.js, tests/unit/Banner.test.js, tests/unit/BreadcrumbContainer.test.js, tests/unit/__snapshots__/Breadcrumbs.test.js.snap
DOP-1840
- [BI Connector](https://docs-mongodbcom-staging.corp.mongodb.com/master/bi-connector/sophstad/DOP-1840/)
- [Landing](https://docs-mongodbcom-staging.corp.mongodb.com/nav/landing/sophstad/DOP-1840/)
- Use `realm-web` rather than `mongodb-stitch-browser-core` because the latter package was exhibiting some bugs when used with `@loadable/component`. Switching over was easy enough!
- Lift Realm `fetchProjectParents` call into context so that results are accessible to breadcrumbs and sidenav
- Move all providers into one component for the sake of tidiness
=> DOP-1840: Add Sidebar back link

src/components/Tabs.js, src/templates/product-landing.js
When I merged in changes from `master`, there were a few breakages around tabs. Namely: 
- `margin`s had to be removed from `tab-panels`
- `tab-button`s were not obeying the laws of physics on small screens
- Rewrite `Tabs` CSS to be compatible with changes from `master`
- Bonus: Rewrite large chunk of CSS in `Wrapper` in `product-landing.js`
- Bonus: Remove all instances of `:first-child` selector to avoid SSR warnings
My change: [Tabs-fix](https://docs-mongodbcom-staging.corp.mongodb.com/DOP-1979/compass/cgoecknerwald/tabs-fix/) 
Current [BROKEN PLP branch](https://docs-mongodbcom-staging.corp.mongodb.com/DOP-1979/compass/cgoecknerwald/plp/), so you can see what's happening right now
```
GATSBY_SITE=compass
GATSBY_PARSER_USER=cgoecknerwald
GATSBY_PARSER_BRANCH=DOP-1979 …
```
=> tabs-fix: Fix tab-button failures; change tab buttons to LG tab buttons

src/components/Tabs.js, src/components/landing/Procedure.js, src/templates/product-landing.js
[DOP-2095](https://jira.mongodb.org/browse/DOP-2095)
[Docs-compass](https://docs-mongodbcom-staging.corp.mongodb.com/DOP-1979/compass/cgoecknerwald/DOP-2095/)
There were some interesting design questions arising from the 2-column / 1-column layout boundary. Should the layout switch to 2 columns at **medium** (`max-width: 767px`), **large** (`max-width: 1023px`), or somewhere in-between at **medium-large** (`max-width: 895px`)?
(@allisonmui9: the current layout boundary options are [here](https://github.com/mongodb/snooty/blob/master/src/theme/docsTheme.js#L47-L58). "Medium-large" would need to be added.)
Currently, I have opted to have the layout change to 2 columns at  **large** (`max-width: 1023px`). The downside is that the hero image becomes very massive on slightly-under-large …
=> DOP-2095: Add Sidebar component into PLP

src/components/Heading.js, src/components/SearchResults/SearchResults.js, src/components/landing/CardGroup.js, src/components/landing/Introduction.js, src/templates/landing.js, src/theme/docsTheme.js
DOP-2135
[docs-landing branch](https://github.com/rayangler/docs-landing/tree/docs-nav)
[Landing Staging](https://docs-mongodbcom-staging.corp.mongodb.com/docs-nav/landing/raymundrodriguez/DOP-2135/)
* Added 2 new columns to `landing` template to allow for hero image to expand.
* Added classes to certain components such as `Introduction` and `CardGroup` to allow for landing-specific css.
* Added margins to `SearchResults` component to maintain layout when `search.txt` page has `landing` template.
=> DOP-2135: Update homepage layout

src/components/landing/CardGroup.js
[JIRA](https://jira.mongodb.org/browse/DOP-2117).
[Docs-landing PR](https://github.com/mongodb/docs-landing/pull/70).
[Snooty-parser PR](https://github.com/mongodb/snooty-parser/pull/311). [MERGED]
[Docs-landing](https://docs-mongodbcom-staging.corp.mongodb.com/master/landing/cgoecknerwald/DOP-2117/), which should perform identically to [docs.mongodb.com](docs.mongodb.com)
=> DOP-2117: Use layout option for isCarousel

src/components/landing/CardGroup.js
N/A
[Docs-compass](https://docs-mongodborg-staging.corp.mongodb.com/DOP-1979/compass/cgoecknerwald/no-unset/).
Since `verticalStyling` no longer inherits from `carouselStyling`, the `unset` became vestigial.
=> no-unset: Remove unnecessary unset

src/components/landing/Card.js
N/A - pre-UAT catch.
[Docs-compass](https://docs-mongodborg-staging.corp.mongodb.com/DOP-1979/compass/cgoecknerwald/link-hover-fix/)
- This will apply to `extra-compact` Cards as well, which is fine because A) they don't use CTAs, and B) if they did, it's approved behavior
=> Link-hover-fix: Add link hover state to Cards

src/components/EcosystemHomepageTiles.js
DOP-2104
[Drivers Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/drivers/sophstad/DOP-2104/)
- Convert Ruby and Node from paths to absolute URLs, as these pages are not contained within the `docs-ecosystem` property
=> DOP-2104: Remove Drivers 404s

src/components/Breadcrumbs.js, src/components/MainColumn.js, src/styles/mongodb-docs.css, src/templates/document.js
- [Landing](https://docs-mongodbcom-staging.corp.mongodb.com/nav/landing/sophstad/margin-fix/)
- [Drivers](https://docs-mongodbcom-staging.corp.mongodb.com/master/drivers/sophstad/margin-fix/)
- Standardizes margins so that `landing`, `document`, and `drivers-index` templates (i.e. all templates with sidebars) according to the docs nav Figma. They'll all have the same positioning in the top-left corner
- Remove `-24px` margin on `<h1>` elements because what was it doing there anyway? This allows breadcrumbs to render with the padding specified in design specs
=> Standardize Margins

src/styles/mongodb-docs.css
DOP-2138
[BI-Connector](https://docs-mongodbcom-staging.corp.mongodb.com/DOP-2138/bi-connector/raymundrodriguez/DOP-2138/reference/known-issues/)
* Added padding for a couple of extra levels in the old TOC.
* Stand by for related docs-tools PR to keep the css as similar as possible, and in case something like this were to happen with legacy or old gen docs. (https://github.com/mongodb/docs-tools/pull/506)
=> DOP-2138: Add padding for additional levels of TOC

src/components/landing/Kicker.js
[JIRA](https://jira.mongodb.org/browse/DOP-2177).
[Docs-compass, images removed](https://docs-mongodborg-staging.corp.mongodb.com/DOP-1979/compass/cgoecknerwald/DOP-2177/)
Thankfully a one-liner!
=> DOP-2177: Handle no hero images, and no tab images

src/components/Heading.js, src/styles/mongodb-docs.css, src/styles/sidebar.module.css
DOP-2208
[Realm Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/raymundrodriguez/DOP-2208/)
[BI-Connector Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/bi-connector/raymundrodriguez/DOP-2208/)
* Ever since the mongodb-docs css was forked, it has caused a `display` rule to be applied to our sidebar in a different order. This PR hopes to resolve that issue by making a different display important.
* Title headings seem to be cut off at the top of the page on mobile when there are no breadcrumbs present. Removing the negative top margin fixes this.
=> DOP-2208: Fix missing sidebar and cut-off title heading on mobile

src/styles/mongodb-docs.css
DOP-2210
[Realm Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/raymundrodriguez/DOP-2210/)
* Legacy css for the sidebar had the component's breakpoint at 1120px while [snooty's is 1024px](https://github.com/mongodb/snooty/blob/master/src/templates/document.js#L22). Changing the legacy css to match 1024px seems to solve this issue.
* To test, resize viewport to be between 1024px and 1120px. The left nav should be visible by default. Compare with the current live site for drivers ([link](https://docs.mongodb.com/drivers/c/)) and note that the sidebar no longer disappears.
=> DOP-2210: Match legacy sidebar breakpoint with snooty's

src/components/Image.js, src/components/Lightbox.js, tests/unit/__snapshots__/Lightbox.test.js.snap
DOP-1798
[Docs Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/docs/carolinao/DOP-1798/core/databases-and-collections/)
For some reason if you go directly to a page that has images you can click to enlarge, you can’t click on them. But if you’re on a different page, and then you go to a page with an image you can click, you can click on it (previous bug from the way it's in production right now) So to test it, it's needed to go to previous page and go to next one
- Problem was images weren't changing size after clicking on "Click to Enlarge". 
- Solved it by adding a new `isOpen` boolean prop in `Image` component that sets `width : 100%` if true
=> DOP-1798 - 'Click to enlarge' doesn't enlarge the image

src/components/Heading.js, src/components/Kicker.js, src/templates/product-landing.js
DOP-2198
[Realm PLP Design](https://www.figma.com/file/hPTwMb9uHOypYLckYDg072/Realm-PLP?node-id=2%3A965)
[New Realm PLP rst](https://github.com/rayangler/docs-realm/commit/31acd674a51bc12275b59b841a5c9c3676611838)
[Realm](https://docs-mongodbcom-staging.corp.mongodb.com/DOP-2198/realm/raymundrodriguez/DOP-2198/)
[Compass](https://docs-mongodbcom-staging.corp.mongodb.com/master/compass/raymundrodriguez/DOP-2198/)
* Had to get rid of the padding on the side and add additional grid columns to act as padding. This allows the large hero image to span the whole main column. The grid column for existing components were adjusted to compensate for the new columns. Positioning should be the same overall.
* Added a small fix for the `Contents` component appearing under every heading on mobile/tablet …
=> DOP-2198: Update PLP template to accommodate large hero image

src/components/Tabs.js
DOP-1728
[Ordered list example ](https://docs-mongodbcom-staging.corp.mongodb.com/master/cloud-docs/carolinao/DOP-1728/security-multi-factor-authentication/)
[Regular text example](https://docs-atlas-staging.mongodb.com/cloud-docs/docsworker-xlarge/snooty-setup/security-add-mongodb-users)
Simple CSS change added to `Tabs` component
=> DOP-1728 - [cloud-docs]: Increase padding above ordered lists in tabs

src/components/Card.js, src/components/CardGroup.js, src/components/Tabs.js, src/templates/product-landing.js, tests/unit/CardRef.test.js, tests/unit/__snapshots__/Card.test.js.snap, tests/unit/__snapshots__/CardGroup.test.js.snap, tests/unit/__snapshots__/CardRef.test.js.snap, tests/unit/data/CardRef.test.json
[DOP-2174](https://jira.mongodb.org/browse/DOP-2174)
[index.txt rST](https://github.com/mango-db/docs-realm/blob/master/source/index.txt)
[Figma](https://www.figma.com/file/hPTwMb9uHOypYLckYDg072/Realm-PLP?node-id=0%3A1)
[Docs-realm](https://docs-mongodborg-staging.corp.mongodb.com/master/realm/cgoecknerwald/DOP-2174/)
[Docs-compass](https://docs-mongodborg-staging.corp.mongodb.com/master/compass/cgoecknerwald/DOP-2174/
) for sanity check <- nothing should break, though the breakpoint for cards to switch to 2 columns is bumped up to ~1200px
[Cloud-docs 1](https://docs-mongodbcom-staging.corp.mongodb.com/master/cloud-docs/cgoecknerwald/DOP-2174/security-add-mongodb-users/#open-the-add-new-database-user-dialog) <- no changes expected
[Cloud-docs …
=> DOP-2174: Card-ref styling

src/components/EcosystemHomepageTiles.js
This is part of https://jira.mongodb.org/browse/DOCSP-17578. The Nav links to `/java-drivers/` but the Ecosystem/Drivers homepage links to `/java/`. By updating it to link to the same location as the toolbar, it allows us to remove a temporary workaround and reduce the amount of clicks needed to get to the new documentation for the synchronous Java driver.
DOP-NNNN
=> change java slug to /java-drivers/

src/components/TOCNode.js, tests/unit/__snapshots__/TableOfContents.test.js.snap
DOP-2351
[Docs staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/docs/raymundrodriguez/DOP-2351/tutorial/getting-started/)
* Use `to` prop instead of `href` to prevent relative path for TOC drawers.
* Go to an arbitrary page on staging and note that drawers now link to its page with the correct site prefix.
* Looked for other `Link` components throughout Snooty that use `href` and could not find any. Other uses of `a` tags use `href`s properly and intentionally, from what I could tell. (There were a lot of entries of both `Link` and `a` so apologies if I missed any 😄)
=> DOP-2351: Fix TOC drawers directing to incorrect page

src/components/Navbar.js, src/components/Sidebar.js
DOP-2385
N/A, meant to interact with autobuilder
related PR:
https://github.com/mongodb/docs-worker-pool/pull/475
Observed that feature flag wasn't functional in environments built with autobuilder (flag is additive - no regressions, only causes the old nav to render, which is desired production behavior currently). 
Cause seems isolated to the autobuilder itself (see related pr) but this is a precaution after referencing https://www.gatsbyjs.com/docs/how-to/local-development/environment-variables/.
Changes the feature flag in use to have `GATSBY_` as a prefix.
=> Append GATSBY_ prefix to existing nav feature flag

README.md
Added the following to help standardize + document release process:
- Be on master branch & run npm ci
- Keep snooty + snooty-parser minor versions consistent
- Keep pre-release checked until 1.0.0
=> readme-update: Update README.md to expand on release process

src/components/Header.js, src/components/Navbar.js, src/components/Sidenav/SidenavMobileMenuButton.js, src/components/Sidenav/SidenavMobileMenuDropdown.js, src/components/Sidenav/index.js
DOP-2380
[Realm staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/raymundrodriguez/DOP-2380/) - with consistent nav feature flag
[Realm staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/raymundrodriguez/DOP-2380-flag-off/) - with feature flag off
* Added a new component `SidenavMobileMenuDropdown` to allow users to open the new side nav with the new consistent nav on mobile screen sizes
* The current implementation of the consistent nav on the new docs-nav layout isn't perfect at the moment because of its compatibility with our grid layout. There should be an upcoming update to the consistent nav package that fixes this
=> DOP-2380: Add mobile support for the side nav with consistent nav enabled

src/components/SiteBanner.js, src/utils/realm.js, tests/unit/SiteBanner.test.js
DOP-2383
[Realm staging with site banner](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/raymundrodriguez/DOP-2383/) - regular build meant for snooty devs (no `SNOOTY_ENV` set)
[Realm staging without site banner](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/raymundrodriguez/DOP-2383-not-develop/) - with `SNOOTY_ENV !== 'development'` (emulates the autobuilder)
* More context on the issue could be found in the ticket description! Relevant Realm code can be found in our Realm `snooty` app's `getBanner` function, and `banner` value. For this PR, the `banner` value is set to have its new `isDev` bool set to true. This should allow the banner to be seen with local builds on snooty, but shouldn't be shown when using the autobuilder.
* `SNOOTY_ENV` is an env var …
=> DOP-2383: Use snootyEnv as a flag for Realm banner function

src/components/Sidenav/SidenavBackButton.js, src/components/navigation-context.js
DOP-2402
[Node staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/node/raymundrodriguez/DOP-2402/)
* The Node docs should have their side nav back button point to the Drivers site but is not being included here for the purpose of the PR (will update the navigation accordingly after this PR is merged).
=> DOP-2402: Add default side nav back button target

package-lock.json, package.json, src/components/Contents.js, src/components/DocumentBody.js, src/components/RightColumn.js, src/components/Widgets/index.js
DOP-2392
[Realm staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/raymundrodriguez/DOP-2392/) - with consistent nav feature flag on
[Realm staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/raymundrodriguez/DOP-2392-con-nav-off/) - without feature flag
* Adds `UnifiedFooter` to `DocumentBody`.
* Had to update the positioning of our `RightColumn` that hosts the "On This Page"/`Contents` component to avoid the component from overlapping with the new footer.
* Also updated some props for the `Contents` and `Widgets` files to avoid unnecessary prop errors.
=> DOP-2392: Add UnifiedFooter to docs-nav

.prettierignore, package.json, src/templates/document.js
DOP-2411
https://docs-mongodborg-staging.corp.mongodb.com/master/realm/cassidy.schaufele/DOP-2411/
https://docs-mongodbcom-staging.corp.mongodb.com/master/bi-connector/cassidy.schaufele/DOP-2411
- Adds a conditional style to our page layout to adjust top margins when the unified nav is turned on. This resolves a number of layout issues (sidnav having underflow when body content is shorter, improper spacing between top breadcrumbs, etc.)
- Ridealong that brokers a peace treaty between our warring `auto-semver` and `prettier`
- Ridealong that adds `build:clean:stage` for a single routine to build and stage after cleaning local artifacts
=> DOP-2411: Fix content margins for Unified Navigation

src/components/Sidebar.js, src/styles/sidebar.module.css
DOP-2418
BI Connector (current nav): https://docs-mongodborg-staging.corp.mongodb.com/master/bi-connector/cassidy.schaufele/DOP-2418/
Realm (with new nav): https://docs-mongodborg-staging.corp.mongodb.com/master/realm/cassidy.schaufele/DOP-2418/
Resolves an issue with nav cutoff due to viewport height being constricted.
I had a changeset similar to this that was stashed and never applied in the sticky nav branch - essentially, it just ensures that we set a height for the remaining viewport, offset by the margin that our content body uses to account for our top navbar.
=> DOP-2411: Fix cutoff sidenav

Makefile
Not a ticket
[Atlas Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/cloud-docs/raymundrodriguez/update-makefile/)
[Realm Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/raymundrodriguez/update-makefile/)
* Updates the S3 bucket we use for staging. I left 2 staging links just to double-check.
* Snooty devs should use the updated AWS credentials so mut can publish to the new bucket
=> Update Makefile to use new S3 staging bucket

src/templates/document.js
DOP-2440
[Atlas Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/cloud-docs/raymundrodriguez/DOP-2440/connect-to-database-deployment/)
* Removes an unnecessary css rule for grid template columns so that the right column doesn't squish the main column.
* Compare staging link with this [older one](https://docs-mongodbcom-staging.corp.mongodb.com/master/cloud-docs/raymundrodriguez/update-makefile/connect-to-database-deployment/).
=> DOP-2440: Fix Document template columns

src/components/Sidenav/TOCNode.js
DOP-2439
[Atlas Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/cloud-docs/raymundrodriguez/DOP-2439/getting-started/)
* Added a new css rule to toctree nodes to prevent LG's `text-transform: capitalize` styling.
* Alphabetized prop types for `TOCNode`
=> DOP-2439: Prevent text transform of nav TOC

src/components/Sidenav/Sidenav.js
[Landing Staging](https://docs-mongodbcom-staging.corp.mongodb.com/upstream-nav/landing/raymundrodriguez/fix-back-button/) - consistent nav off
[Landing Staging](https://docs-mongodbcom-staging.corp.mongodb.com/upstream-nav/landing/raymundrodriguez/fix-back-button-con-nav/) - consistent nav on
* The back button currently requires to pass in `project` and `slug` props since the back button has different behavior on docs-landing than other sites. However, the back button appears on the docs homepage as if this is a different docs site. Use this [staging link built on master](https://docs-mongodbcom-staging.corp.mongodb.com/upstream-nav/landing/raymundrodriguez/master/) for comparison with the staging links above.
* Included screenshots below of the docs-node site to validate that behavior …
=> Fix back button appearance on landing

src/components/MainColumn.js, src/components/Navbar.js, src/components/RightColumn.js, src/components/Sidenav/SidenavDocsLogo.js, src/layouts/index.js, src/templates/document.js
DOP-2450
[Docs Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/docs/raymundrodriguez/DOP-2450/installation/)
[Drivers Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/drivers/raymundrodriguez/DOP-2450/) - without consistent nav, for comparison
* Changes max width of content's main column div from 800px to 775px to match current production content width.
* Fixes spacing between the content column and the righthand TOC / `Contents` component for very large screens.
* Makes the docs logo clickable on the sidenav and on the (non-consistent nav) navbar.
* Re-adds footer overrides for `UnifiedFooter` that weren't merged in properly before.
=> DOP-2450: Fix spacing between content and TOC

src/components/ContentTransition.js, src/components/DocumentBody.js, src/templates/document.js, src/templates/product-landing.js
DOP-2461
**Landing:**
https://docs-mongodbcom-staging.corp.mongodb.com/master/landing/cassidy.schaufele/DOP-2461/develop-applications/
- Adds basic flexbox styles to our main `content` column, to ensure that any content (footer) is spaced to fill available screen space.
- Changes `overflow-x: scroll` to `auto` to remove empty horizontal scrollbars on non OSX devices.
**Production, portrait viewport**
**Staging, portrait viewport**
t
=> DOP-2461: Whitespace possible below Unified Footer

package-lock.json, package.json, src/components/DeprecatedVersionSelector.js, src/components/Introduction.js
DOP-2092
[Compass](https://docs-mongodbcom-staging.corp.mongodb.com/master/compass/raymundrodriguez/DOP-2092/)
[Landing - Legacy page](https://docs-mongodbcom-staging.corp.mongodb.com/master/landing/raymundrodriguez/DOP-2092/legacy/)
* Upgrades LG button to version 12.0.2 in hopes of resolving button/selector styling when working on DOP-2136.
* 12.0.2 is the version chosen for the LG button since versions 12.0.3+ use upgraded dependencies that require React 17.
* We only use disabled buttons in one place (the legacy docs landing page). I incorporated a workaround for the disabled button bug that is fixed in future versions of the LG button (see comment regarding the change).
=> DOP-2092: Upgrade LG button to version 12.0.2

src/components/Header.js
DOP-2495
*Landing, with Realm searchProperty*
https://docs-mongodbcom-staging.corp.mongodb.com/master/landing/cassidy.schaufele/DOP-2495/search/?q=&searchProperty=realm-master
*Landing, default*
https://docs-mongodbcom-staging.corp.mongodb.com/master/landing/cassidy.schaufele/DOP-2495/search
We can be assured that for the version of the consistent navigation component that we utilize, the `searchProperty` will have a value of `realm-master` when a search originates from Realm docs.
This change ensures that we will retain Realm search as the default property for the navigation when originating search from said Realm pages.
=> DOP-2495: Retain Realm Searchbar Context

package-lock.json, package.json, src/components/Code.js, src/components/TabSelectors.js, src/components/Tabs.js, src/components/code-context.js, src/components/icons/Shell.js, src/components/tab-context.js, tests/unit/Code.test.js, tests/unit/__snapshots__/Code.test.js.snap, tests/unit/__snapshots__/ReleaseSpecification.test.js.snap, tests/unit/data/Code.test.json
DOP-2136
[Server Docs](https://docs-mongodbcom-staging.corp.mongodb.com/master/docs/raymundrodriguez/DOP-2136/indexes/)
* Leverages LG's language switcher for code blocks to work alongside our `TabsSelector` component. If there is no `tabs-selector` directive on the page, and if the code block isn't nested under a tab from the drivers tabset, then the language switcher will not be rendered.
=> DOP-2136: Add LanguageSwitcher to code blocks

src/components/Header.js, src/components/SearchResults/EmptyResults.js
[Landing - Search](https://docs-mongodbcom-staging.corp.mongodb.com/master/landing/raymundrodriguez/master/search/)
* While creating a release, the `preversion` command printed out lint warnings. This PR should simply fix the lint warnings.
* I'll create a separate new ticket to look into adding an option in our pre-commit hooks to actually warn (or fail) on warnings.
=> Fix lint warnings

gatsby-browser.js, src/components/ContentTransition.js, src/components/Header.js, src/components/RightColumn.js, src/components/Sidenav/IATransition.js, src/components/Sidenav/Sidenav.js, src/components/Sidenav/SidenavMobileMenuDropdown.js, src/components/Sidenav/SidenavMobileTransition.js, src/components/Target.js, src/constants.js, src/hooks/useStickyTopValues.js, src/layouts/index.js, src/styles/mongodb-docs.css, src/theme/docsTheme.js, tests/unit/__snapshots__/Target.test.js.snap, tests/unit/useStickyTopValues.test.js
DOP-2485
[Realm Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/raymundrodriguez/DOP-2485-a/)
[Landing Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/landing/raymundrodriguez/DOP-2485-a/)
[Compass Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/compass/raymundrodriguez/DOP-2485-a/)
* Changes the side nav and header components (unified top nav, mobile docs menu/toctree) to be sticky.
* Brings back page scrolling, replacing the content scroll container.
* Arrow key scrolling works.
* Tab navigation works as expected (starts from the top).
=> DOP-2485: Fix page scrolling

Makefile
https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/compass/raymundrodriguez/update-staging-makefile/index.html
* With the change to our new S3 bucket for docs team staging, the staging site no longer points to our staging bucket. This PR updates the staging url to refer directly to the S3 bucket's url.
* Each page in our S3 bucket site requires `/index.html` to be included in the url when putting it into the address bar. I have included that in the echo of our final staging url.
=> Update staging url to use S3 site

package.json
DOP-2618
I tested this by importing an unused file inside of a component and committing the change.
```
$ git commit -m "Test pre-commit linting"
✔ Preparing...
⚠ Running tasks...
❯ npm run lint:fix [FAILED]
✔ npm run format:fix
✖ npm run lint:fix [FAILED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up...
✖ npm run lint:fix:
ESLint found too many warnings (maximum: 0).
```
=> DOP-2618: Prevent lint warnings during pre-commit hook

src/components/Chapters/Chapter.js, tests/unit/Chapter.test.js, tests/unit/__snapshots__/Chapter.test.js.snap
DOP-2601
[Guides Staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/test-guides/guides/raymundrodriguez/DOP-2601/index.html)
* The links in the chapter cards should have a background color of `#E7EEEC` on hover, which matches the background color of the side nav items on hover. Let me know if I should change this!
=> DOP-2601: Add hover background to chapters' guide links

Makefile, src/components/Chapters/Chapters.js
DOP-2722
[Guides Staging](https://docs-mongodbcom-integration.corp.mongodb.com/test-guides/guides/raymundrodriguez/DOP-2722/)
* Asserts trailing slash on guide slugs to prevent gallery cards from erroring on staging.
* Bonus: Uses old integration site url for S3 staging links.
=> DOP-2722: Fix card URLs in guides gallery view

gatsby-node.js, src/components/BreadcrumbSchema.js, src/components/Breadcrumbs.js, src/components/DriversIndexTiles.js, src/components/SEO.js, src/components/VersionDropdown.js, src/constants.js, src/html.js, src/templates/NotFound.js, src/templates/landing.js, src/utils/dotcom.js, src/utils/get-site-url.js, tests/unit/__snapshots__/Breadcrumbs.test.js.snap, tests/unit/utils/dotcom.test.js
DOP-2650
[Landing](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/cassidy.schaufele/DOP-2650/index.html)
[Realm](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/realm/cassidy.schaufele/DOP-2650/index.html)
This changeset adds a series of helpers for determining the `base url` that a front end website is deployed with.
It also utilizes these helpers throughout the frontend to ensure compatibility with tandem `dotcom` url scheme deployments, e.g. properties following `www.mongodb.com/docs` url patterns instead of `docs.*.mongodb.com` patterns.
This is implemented by first preferring the presence of a `GATSBY_BASE_URL` environment variable, then otherwise falling back on logic to determine if …
=> DOP-2650: The great url accommodation roundup

src/components/ListTable.js, tests/unit/__snapshots__/ListTable.test.js.snap
[DOP-2233](https://jira.mongodb.org/browse/DOP-2233)
[Compass Staging Link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/compass/grace.chong/DOP-2233/indexes/index.html#optional-specify-the-index-options)
This change makes the text in Tables 14px, including nested components.
=> DOP-2233: Make all text and components within tables 14px

src/components/Sidenav/Sidenav.js, src/components/Sidenav/SidenavMobileMenuDropdown.js, src/theme/docsTheme.js, src/utils/display-none.js, tests/unit/Sidenav.test.js, tests/unit/__snapshots__/CardGroup.test.js.snap, tests/unit/__snapshots__/CardRef.test.js.snap, tests/unit/__snapshots__/Operation.test.js.snap, tests/unit/__snapshots__/Procedure.test.js.snap, tests/unit/__snapshots__/QuizWidget.test.js.snap, tests/unit/__snapshots__/Step.test.js.snap
DOP-2741
[Datalake](https://docs-mongodbcom-integration.corp.mongodb.com/master/datalake/cassidy.schaufele/DOP-2741/)
Uses mobile nav view on tablet size screens.
Adjusts mobile breakpoints to 480px for widescreen phones.
=> DOP-2741: Use mobile nav on tablet view

src/components/GuideNext/read-guides-context.js
DOP-2764
[Guides staging](https://docs-mongodbcom-integration.corp.mongodb.com/test-guides/guides/raymundrodriguez/DOP-2764/cloud/account/)
* Feel free to compare above staging link with this [older staging link](https://docs-mongodbcom-integration.corp.mongodb.com/test-guides/guides/raymundrodriguez/master/cloud/account/). When clicking directly on the older staging link, the list of guides in the "What's Next" component at the bottom may not have the correct states from `localStorage`. The new staging link above should show the correct states (even if with a short delay)
=> DOP-2764: Re-render GuideNext component with localStorage

src/components/Chapters/RightColumn.js, src/components/Permalink.js, src/hooks/useActiveHeading.js, tests/unit/__snapshots__/Heading.test.js.snap, tests/unit/__snapshots__/Section.test.js.snap, tests/unit/__snapshots__/Target.test.js.snap
DOP-2720
[Guides Staging](https://docs-mongodbcom-integration.corp.mongodb.com/test-guides/guides/raymundrodriguez/DOP-2720/cloud/account/)
[Server Staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/docs/raymundrodriguez/DOP-2720/core/sharding-reshard-a-collection/) (ensure that the "On This Page" component more or less works the same on staging).
Compare the "On This Page" component here: server [staging page](https://docs-mongodbcom-integration.corp.mongodb.com/master/docs/raymundrodriguez/DOP-2720/tutorial/model-embedded-one-to-one-relationships-between-documents/) with [prod page](https://docs.mongodb.com/manual/tutorial/model-embedded-one-to-one-relationships-between-documents/).
The original problem was that if multiple headings were in the viewport at the same …
=> DOP-2720: Improve useActiveHeading hook accuracy

gatsby-node.js, src/utils/setup/construct-repos-filter.js
DOP-2780
[Server docs](https://docs-mongodbcom-integration.corp.mongodb.com/v5.0/docs/raymundrodriguez/DOP-2780/)
* For context: The internal docs repo may not be able to update the project name in their `snooty.toml` due to a script that syncs changes between the public and internal repos. This means that changing the project name for the internal docs will automatically change the project name for the public docs too, or else merge conflicts may occur.
* This solution adds an additional optional field to the filter when searching for branches. This will require the autobuilder Makefiles for `docs` and `docs-mongodb-internal` to pass in a new `REPO_NAME` env variable to the frontend's `.env.production` file to differentiate between two repos that share the same project name.
=> DOP-2780: Update filter to account for shared project name

src/utils/dotcom.js, tests/unit/utils/dotcom.test.js
DOP-2782
Mostly N/A - dependent on a variable which was never defined being undefined
https://docs-mongodbcom-integration.corp.mongodb.com/master/landing/cassidy.schaufele/DOP-2782/
This removes the ability to 'passthrough' the `GATSBY_BASE_URL` env var - on second thought, this is too vulnerable to passing garbage data directly throughout the frontend, and doesn't adequately account for `docs.mongodb`, `docs.atlas.mongodb`, etc. cases for pre-consolidated instances.
=> DOP-2782: Remove passthrough of GATSBY_BASE_URL

gatsby-node.js, src/components/DeprecatedVersionSelector.js, src/components/Header.js, src/constants.js, src/utils/dotcom.js, src/utils/get-site-url.js, tests/unit/utils/dotcom.test.js, tests/unit/utils/get-site-url.test.js
DOP-2819
**Nested Breadcrumbs (Cloud)**
https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/cassidy.schaufele/DOP-2819/choose-database-deployment-type/
**Legacy Selector (Landing)**
https://docs-mongodbcom-integration.corp.mongodb.com/master/landing/cassidy.schaufele/DOP-2819/legacy/
**Nested Breadcrumbs (Manual, dotcom, built via autobuilder)**
https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/upcoming/reference/insert-methods/
In environments higher than staging, the autobuilder prepends `docs-qa` as a prefix - this is causing our html breadcrumbs to have a duplicate `/docs-qa` in urls past the base breadcrumb.
This is also causing a discrepancy between canonicals at build time vs. at Gatsby …
=> DOP-2819: Remove duplicate prefix from HTML Breadcrumbs

src/utils/dotcom.js, tests/unit/utils/dotcom.test.js, tests/unit/utils/get-site-url.test.js
DOP-2807
*In Progress*
*In Progress*
Switches our prefix to `docs` from `docs-qa`.
This doesn't apply to path prefixes provided via `.env`.
=> DOP-2807: Get rid of -qa

src/utils/dotcom.js, tests/unit/utils/dotcom.test.js, tests/unit/utils/get-site-url.test.js
Fix to resolve behavior flagged in: https://github.com/mongodb/snooty/pull/583
Non desk-testable right now, sadly - dotcom domain is not applicable in staging links.
Behavior is relatively assured via unit tests, however.
see https://github.com/mongodb/snooty/pull/583 for context
=> DOP-2807: Map opsmanager to ops-manager in paths

src/utils/site-metadata.js
[Mongo CLI, Data sourcing from pool_test](https://www.mongodb.com/docs/mongocli/v1.24/)
Adds cases to site-metdata to prevent our switch to defaulting to `pool_test` in `dotcomprd` environments
=> hotfix-add-dotcom-repos-database-case

src/components/ListTable.js, tests/unit/__snapshots__/ListTable.test.js.snap
[DOP-2183](https://jira.mongodb.org/browse/DOP-2183)
[Atlas Docs in Prod](https://www.mongodb.com/docs/atlas/reference/api/database-users-update-a-user/#request-body-parameters)
[Atlas Staging ](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/grace.chong/DOP-2183/reference/api/database-users-update-a-user/#request-body-parameters)
=> DOP-2183: Fix styling issue with padding differences between table header and cell

package-lock.json, src/components/Link.js, tests/unit/Link.test.js, tests/unit/__snapshots__/BlockQuote.test.js.snap, tests/unit/__snapshots__/Breadcrumbs.test.js.snap, tests/unit/__snapshots__/CTABanner.test.js.snap, tests/unit/__snapshots__/Card.test.js.snap, tests/unit/__snapshots__/CardGroup.test.js.snap, tests/unit/__snapshots__/GuideNext.test.js.snap, tests/unit/__snapshots__/Link.test.js.snap, tests/unit/__snapshots__/Reference.test.js.snap
[DOP-2602](https://jira.mongodb.org/browse/DOP-2602)
[Atlas Production Example 1](https://www.mongodb.com/docs/atlas/tutorial/create-atlas-account/#google-accounts)
[Atlas Production Example 2](https://www.mongodb.com/docs/atlas/reference/unsupported-commands/#unsupported-commands-in-m0-m2-m5-clusters)
[Atlas Staging Example 1](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/grace.chong/DOP-2602/tutorial/create-atlas-account/#google-accounts)
[Atlas Staging Example 2](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/grace.chong/DOP-2602/reference/unsupported-commands/#unsupported-commands-in-m0-m2-m5-clusters) 
In summary, any link that isn't to `www.mongodb.com/docs/*` should opens in a new tab and should be styled according to LG's new link …
=> DOP-2602: Add option for external links to open in a new tab/window

package-lock.json, package.json
N/A
Click to enlarge any figure to open a modal, or give feedback through the feedback widget when the screen size is medium size (say, 900px). The location of the close button will differ.
[Charts Staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/charts/raymundrodriguez/master/) - master branch (7fda3590ae4788d7d008a1c901f576c5d3cc84d7) - the modal's close button can be found on the bottom left corner of the modal.
[Charts Prod](https://www.mongodb.com/docs/charts/) - the modal's close button can be found on the upper right corner of the modal, where it should be.
[Charts Staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/charts/raymundrodriguez/fix-modal-close/) - the modal's close button can be found on the upper right corner of the modal.
- This …
=> Fix modals' close button positioning

src/html.js
* The `DC.Source` tag, while interesting on paper, requires information to be passed to the frontend that currently isn't. So it's just woefully wrong right now.
* It would be nice to have an osd.xml, but let's wait until we actually have one to reference it.
DOP-2798
=> DOP-2798: Remove incorrect meta tags

src/components/Sidenav/SidenavDocsLogo.js, src/constants.js, src/utils/search-params-to-url.js, tests/unit/utils/mock-marian-fetch.js
N/A
[Landing Prod](https://www.mongodb.com/docs/)
[Landing QA Site](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/)
[Landing Staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/raymundrodriguez/fix-docs-homepage-style/index.html)
* Adds trailing slash to docs homepage url to prevent different link styling from applying through our `Link` component.
* `DOCS_URL` isn't used in too many places currently so I just updated it to `https://www.mongodb.com/docs/`. Let me know if we don't want to commit to this url yet and if we should stick to using `baseUrl()`!
=> Fix: Add trailing slash to docs homepage url

src/templates/drivers-index.js
DOP-NNNN
https://www.mongodb.com/docs/drivers/
https://docs-mongodbcom-integration.corp.mongodb.com/master/drivers/cassidy.schaufele/hotfix-drivers-landing.1/
Resolved observed issue from metadata page-data changes with drivers-index template
=> DOP-N/A: useSnootyMetadata in drivers-index, make parentPaths null safe

src/components/Link.js, tests/unit/__snapshots__/BlockQuote.test.js.snap, tests/unit/__snapshots__/Breadcrumbs.test.js.snap, tests/unit/__snapshots__/CTABanner.test.js.snap, tests/unit/__snapshots__/GuideNext.test.js.snap, tests/unit/__snapshots__/Reference.test.js.snap
DOP-NNNN
https://www.mongodb.com/docs/realm/sdk/react-native/
https://docs-mongodbcom-integration.corp.mongodb.com/master/realm/cassidy.schaufele/hotfix-sidenav-styling-external-links/
This fixes some of the more obvious styling mismatches in the Realm sidenav by allowing passthrough of relevant css props.
=> DOP-2912: Pass classnames through to external links

package-lock.json, package.json, src/components/Header.js
DOP-2934
[Landing prod](https://www.mongodb.com/docs/)
[Realm docs prod](https://www.mongodb.com/docs/realm/)
[Landing staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/landing/raymundrodriguez/DOP-2934/)
[Realm docs staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/realm/raymundrodriguez/DOP-2934/)
* Updates our version of `consistent-nav` and its peer dependencies.
* The main difference between staging links and current behavior is that hovering over the top nav links doesn't immediately open the menu dropdowns. They also close faster!
* Removed use of the `docsBaseUrl` prop from the `UnifiedNav` component since the docs-related URLs on the top nav seem to be in the "mongodb.com/docs" format already.
=> DOP-2934: Bump consistent-nav version to 1.2.13

package-lock.json, package.json, src/components/Button.js, src/components/Code/styles/codeStyle.js, src/components/DeprecatedVersionSelector.js, src/components/GuideNext/Content.js, src/components/Introduction.js, src/components/ListTable.js, src/components/Video/VideoPlayButton.js, tests/unit/__snapshots__/Button.test.js.snap, tests/unit/__snapshots__/Code.test.js.snap, tests/unit/__snapshots__/CodeIO.test.js.snap, tests/unit/__snapshots__/GuideNext.test.js.snap, tests/unit/__snapshots__/ListTable.test.js.snap, tests/unit/__snapshots__/LiteralInclude.test.js.snap, tests/unit/__snapshots__/QuizWidget.test.js.snap, tests/unit/__snapshots__/ReleaseSpecification.test.js.snap, tests/unit/__snapshots__/SearchResults.test.js.snap
DOP-2573
[Server docs prod](https://www.mongodb.com/docs/manual/)
[Landing prod - search page](https://www.mongodb.com/docs/search/?q=test)
[Landing prod - legacy page](https://www.mongodb.com/docs/legacy/)
[Realm docs prod](https://www.mongodb.com/docs/realm/tutorial/ios-swift/#part-1--set-up-the-mobile-app) (see video button)
[Guides old staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/test-guides/guides/raymundrodriguez/master/server/import/index.html#summary) (built on master branch of Snooty)
[Server docs staging](https://docs-mongodbcom-integration.corp.mongodb.com/DOP-2573/docs/raymundrodriguez/DOP-2573/index.html)
[Landing staging - search page](https://docs-mongodbcom-integration.corp.mongodb.com/master/landing/raymundrodriguez/DOP-2573/search/?q=test)
[Landing …
=> DOP-2573: Upgrade LG Button to v13.0.0

src/components/MainColumn.js, src/constants.js, src/utils/join-class-names.js, tests/unit/utils/join-class-names.test.js
DOP-2736
[Drivers prod](https://www.mongodb.com/docs/drivers/community-supported-drivers/)
[Drivers staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/drivers/raymundrodriguez/DOP-2736/community-supported-drivers/)
* The only difference between the staging and prod links should be that the staging link has a `main-column` class applied to a div.
* I ran `mut-index` locally and a document was successfully created for `community-supported-drivers/index.html`. We should check to make sure that the autobuilder creates a search document for this page when we deploy or test deploy `docs-ecosystem`.
=> DOP-2736: Re-add main-column class name

package-lock.json, package.json
N/A
[Drivers prod](https://www.mongodb.com/docs/drivers/)
[Drivers staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/drivers/raymundrodriguez/hotfix-add-dep/)
This hopefully fixes an issue with the frontend not being able to resolve a dependency for `@mdx-js/react` within `theme-ui`. 
For context, `@mdx-js/react` went from being a dependency to a [peer-dependency](https://github.com/system-ui/theme-ui/pull/1867/files#diff-ac3b342159924758a87a5f7b5a48087ee29bb461797aa51de76b33c87aab87a2R20) when v12 of `theme-ui` was released. `flora` and `consistent-nav` have followed suit to add `@mdx-js/react` as a peer dependency, but this wasn't an issue for snooty until we bumped these dependencies in #612.
=> Hotfix: Add mdx-js/react as a dependency

package-lock.json, package.json, src/components/Code/Code.js, src/components/Code/CodeIO.js, src/components/Code/Output.js, src/components/Code/styles/codeStyle.js, tests/unit/__snapshots__/Code.test.js.snap, tests/unit/__snapshots__/CodeIO.test.js.snap, tests/unit/__snapshots__/LiteralInclude.test.js.snap, tests/unit/__snapshots__/ReleaseSpecification.test.js.snap
[DOP-2952](https://jira.mongodb.org/browse/DOP-2952)
[Atlas Prod Ex. 1](https://www.mongodb.com/docs/atlas/driver-connection/#driver-examples)
[Atlas Prod Ex. 2](https://www.mongodb.com/docs/atlas/tutorial/connect-to-your-cluster/#test-your-pymongo-installation)
[Realm Prod](https://www.mongodb.com/docs/realm/sdk/flutter/quick-start/#create-data-model)
[Atlas Staging Ex. 1](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/grace.chong/DOP-2952/driver-connection/#driver-examples)
[Atlas Staging Ex. 2](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/grace.chong/DOP-2952/tutorial/connect-to-your-cluster/#download-and-install-utility)
[Realm Staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/realm/grace.chong/DOP-2952/sdk/flutter/qu …
=> DOP-2952: Include full literalinclude support for io-code-block directives

src/utils/parse-marian-manifests.js
DOP-3023
[Landing Prod](https://www.mongodb.com/docs/search/?q=test)
[Landing Staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/landing/raymundrodriguez/DOP-3023/search/?q=test)
* Although the main issue was the typo for Atlas CLI, there are other malformed search property names for certain categories. I'm bundling this all up here to avoid more typo tickets during World.
* This hardcoded mapping should be temporary and may be removed once #624 is ready for release.
=> DOP-3023: Fix typos in search property mapping

.github/workflows/test.yml
DOP-3057
N/A
N/A
* This should hopefully ensure that all dependencies are installed as they should be, regardless of the version of `npm` that the CI is using
=> DOP-3057: Add legacy-peer-deps flag to CI installation step

src/components/Sidenav/TOCNode.js
[DOP-2847](https://jira.mongodb.org/browse/DOP-2847)
[Prod link](https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/connection/)
Steps to reproduce:
- click the "Connection Guide" TOC element to toggle it closed
- click one of the links on the page. for example, "Connect to MongoDB"
- note how the "Connection Guide" TOC element does not automatically expand to show you the selected TOC item. The current view makes it seem the page does not correspond to anything in the TOC 😢 
[Staging link](https://docs-mongodbcom-integration.corp.mongodb.com/master/java/drew.beckmen/dop-2847-toc-behavior/fundamentals/connection/)
Repeat the same steps as above. Now, the "Connection Guide" TOC element expands, allowing you to see the selected item.
_Put a link to your staging …
=> DOP-2847: Ensure TOC item open state matches active state

src/components/Image.js
[DOP-2372](https://jira.mongodb.org/browse/DOP-2372)
[Prod site example](https://www.mongodb.com/docs/atlas/production-notes/#single-region-and-multi-region-clusters): On initial page load, the image cannot be clicked. However, if you navigate to a separate page via the TOC and then return to the initial page, the image becomes clickable. We expect the click behavior on initial page load as well.
[Staging site](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/drew.beckmen/dop-2372-image-enlargement/production-notes/#single-region-and-multi-region-clusters): On initial page load, the "click to enlarge" message is present, and users can click on the image to open a modal.
- The behavior is **not** reproducible locally when running `npm run develop`. The fact that the …
=> DOP-2372: Allow images to be enlarged on initial page load

src/components/Image.js
DOP-3106
[Atlas App Services](https://www.mongodb.com/docs/atlas/app-services/authentication/custom-jwt/) (prod)
[Atlas App Services](https://docs-mongodbcom-integration.corp.mongodb.com/test-figure-rendering/atlas-app-services/raymundrodriguez/DOP-3106/authentication/custom-jwt/index.html) (staging) - pay attention to the images on the page under the "App Services UI" tab.
* This bug only affects images that are not rendering with a lightbox (i.e. they cannot be clicked to expanded). The `useEffect` hook in the `Image` component was being triggered and ran repeatedly.
* For testing/validating, you can use the React Dev Tools extension, toggle the setting that highlights components that are re-rendering. Going to the prod page should show the problem images re-rendering. Going to the page …
=> DOP-3106: Prevent Images from repeatedly re-rendering

src/html.js
[DOP-3086
](https://jira.mongodb.org/browse/DOP-3086)
[Compass Docs](https://www.mongodb.com/docs/compass/current/) (current prod) 
Current docs have stylesheet link in head to Inconsolata font.
[Compass Docs](https://docs-mongodbcom-integration.corp.mongodb.com/master/compass/matt.meigs/DOP-3086/) (staging) 
Stylesheet link to unused Google font has simply been removed. I assume this is all that's necessary!
=> DOP-3086: removed unused font (Inconsolata) from html.js

gatsby-node.js, src/init/DocumentDatabase.js, src/utils/setup/fetch-manifest-metadata.js, src/utils/setup/validate-env-variables.js, src/utils/site-metadata.js
[DOP-2986](https://jira.mongodb.org/browse/DOP-2986)
There should be no visual changes as a result of the PR. 
[Realm Prod](https://www.mongodb.com/docs/realm/)
[Compass Prod](https://www.mongodb.com/docs/compass/current/)
[Atlas Prod](https://www.mongodb.com/docs/atlas/)
[Realm Staging](https://docs-mongodbcom-integration.corp.mongodb.com/test/realm/grace.chong/DOP-2986/
)
[Compass Staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/compass/grace.chong/DOP-2986/)
[Atlas Staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/grace.chong/DOP-2986/)
If a manifest file is specified, this code pulls information related to environment variables directly from the file instead of using the environment variables. This avoids having to include …
=> DOP-2986: Load project name and branch from manifest

gatsby-ssr.js
DOP-3150
www.mongodb.com/docs
https://docs-mongodbcom-integration.corp.mongodb.com/master/landing/cassidy.schaufele/DOP-3150/
Adds `defer` to our optimizely script include to make it non-render blocking. This will potentially cause screen flicker should experiments be run, but we don't expect anybody to be running experiments on docs.
Why not `async`? Because we want to make sure it fetches + spends cpu *after* html parse is complete within the browser 👍
=> DOP-3150: Defer Optimizely script

src/components/Card/index.js, src/components/Chapters/Chapter.js, src/components/Chapters/ChapterNumberLabel.js, src/components/Chapters/RightColumn.js, src/components/DriversIndexTiles.js, src/components/Operation.js, src/components/Widgets/FeedbackWidget/FeedbackTab.js, src/components/Widgets/QuizWidget/QuizChoice.js
[DOP-2578](https://jira.mongodb.org/browse/DOP-2578)
[Guides](https://www.mongodb.com/docs/guides/)
[Drivers](https://www.mongodb.com/docs/drivers/)
[Guides](https://docs-mongodbcom-integration.corp.mongodb.com/098a51155afa851ada950d2f32e93107a46bcd59/master/guides/seung.park/DOP-2578-post-typography/)
[Landing](https://docs-mongodbcom-integration.corp.mongodb.com/ca1cc8487251860566cc18198a0059a91c4d4fd7/master/landing/seung.park/DOP-2578-post-typography/)
[Drivers](https://docs-mongodbcom-integration.corp.mongodb.com/098a51155afa851ada950d2f32e93107a46bcd59/master/drivers/seung.park/DOP-2578-post-typography/)
- used updated typography to fill in the card content, applying when necessary. Cards, Driver Index Tiles, Chapters, and FeedbackTab were …
=> DOP-2578: update cards to use new typography

package.json, src/components/Tabs/index.js
[DOP-2577](https://jira.mongodb.org/browse/DOP-2577)
PLP tabs:
https://www.mongodb.com/docs/atlas/
non PLP tabs:
https://www.mongodb.com/docs/atlas/access-tracking/#procedure
also hidden tabs:
https://www.mongodb.com/docs/atlas/alert-resolutions/#view-alerts
PLP tabs:
https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/seung.park/DOP-2577-post-typography/
non PLP tabs:
https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/seung.park/DOP-2577-post-typography/access-tracking/#procedure
also hidden tabs:
https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/seung.park/DOP-2577-post-typography/alert-resolutions/#view-alerts
- [LG updates](https://github.com/mongodb/leafygreen-ui/blob/main/packages/tabs/src/TabTitle.tsx#L42) pushed a change …
=> DOP-2577: update LG/tabs to v8 (post typography update)

package-lock.json, src/components/Paragraph.js, src/utils/append-trailing-punctuation.js, tests/unit/Paragraph.test.js, tests/unit/__snapshots__/Paragraph.test.js.snap, tests/unit/data/Paragraph-Format.test.json
[DOP-3167](https://jira.mongodb.org/browse/DOP-3167)
Reverted in production at the moment, but dangling punctuation multiplies on rerenders.
- when the user navigates back and forth between pages the punctuation is added on again and again. 
Attaching picture.
[Realm page with a Link and dangling period in first admonition on the page](https://docs-mongodbcom-integration.corp.mongodb.com/master/realm/matt.meigs/DOP-3167/sdk/kotlin/install/android/)
First fix of DOP-3167 - (attaching dangling punctuation to preceding Links) - was plagued by unintended consequence of never-ending additions of the same punctuation. References to the same node causes this. 
Current fix creates a deep copy of the change so as not to influence further renders from the same data.
=> DOP-3167: fixed terrifying multiplication of punctuation

src/components/Banner/styles/bannerItemStyle.js, src/templates/product-landing.js, tests/unit/__snapshots__/Banner.test.js.snap, tests/unit/__snapshots__/CTABanner.test.js.snap
[DOP-3215](https://jira.mongodb.org/browse/DOP-3215)
[@jeff-allen-mongo 's staged version](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/v5.3-legacy-banner/)
[PLP without banner](https://www.mongodb.com/docs/manual/)
[existing banner in non PLP](https://www.mongodb.com/docs/atlas/reference/api/database-users/)
[staged changes from same forked repo](https://docs-mongodbcom-integration.corp.mongodb.com/775894b310e16770681b8ca63b9f74ad5f3a734c/v5.3-legacy-banner/docs/seung.park/DOP-3215/)
[manual docs PLP without banner (regression test)](https://docs-mongodbcom-integration.corp.mongodb.com/775894b310e16770681b8ca63b9f74ad5f3a734c/master/docs/seung.park/master/)
[existing banner (regression test)](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs …
=> DOP-3215: fix banners in PLP

gatsby-node.js, jest.config.js, src/components/RootProvider.js, src/components/VersionDropdown/index.js, src/context/version-context.js, src/hooks/use-site-metadata.js, src/init/DocumentDatabase.js, src/layouts/index.js, src/utils/realm.js, src/utils/setup/construct-repos-filter.js, src/utils/setup/fetch-manifest-metadata.js, src/utils/site-metadata.js, tests/context/version-context.test.js
[DOP-3210](https://jira.mongodb.org/browse/DOP-3210)
This PR adds a version context that should be consumable by points of navigation (ie. sidenav, right column) for a consolidated ToC tree and content with embedded documentations
[Atlas Docs](https://www.mongodb.com/docs/atlas/)
[landing](https://www.mongodb.com/docs/)
[staged Atlas Docs](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/seung.park/DOP-3210/)
[staged landing](https://docs-mongodbcom-integration.corp.mongodb.com/master/landing/seung.park/DOP-3210/)
There are no visible behavior changes in front end.
However, you should be able to observe network requests when first loading the page, and [debugging server side code](https://www.gatsbyjs.com/docs/debugging-the-build-process/#vs-code-debugger-auto-config) …
=> DOP-3210: add version context 

src/components/RootProvider.js, src/components/Sidenav/Sidenav.js, src/context/toc-context.js, src/context/version-context.js, src/utils/setup/fetch-manifest-metadata.js, src/utils/setup/toc-test-data.json, tests/context/toc-context.test.js
[DOP-3225](https://jira.mongodb.org/browse/DOP-3225)
[atlas docs](https://www.mongodb.com/docs/atlas/)
[atlas docs staged](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/seung.park/DOP-3225/getting-started/)
- using [mocked data](https://github.com/mongodb/snooty/pull/702/files#diff-1594a8cd87a233c31de3b28bc4b7639b66cd33e42ea4b28ae15a3800c8f129cc) for manifest metadata, as well as document uploaded to snooty_dev.metadata. filter by {page_id: /3225} to check out the document
- staged link has GATSBY_TEST_EMBED_VERSIONS environment variable set to true, and is reading from snooty_dev (see [changes](https://github.com/mongodb/snooty/pull/702/files#diff-67fd2be78a4e3484aedf9be9ed69bf5d5a356fa2a503d987deac14a4d2becfbeR64) )
- can optimize useEffect calls to use useMemo …
=> DOP-3225: add version context

gatsby-ssr.js
DOP-3268
[Atlas](www.mongodb.com/docs/cloud)
https://docs-mongodbcom-integration.corp.mongodb.com/master/realm/cassidy.schaufele/DOP-3268/
Switches the `defer` in our Optimizely import to `async`. See discussion in ticket for additional context.
=> DOP-3268: Make Optimizely Async

src/components/Sidenav/GuidesLandingTree.js, src/components/Sidenav/GuidesTOCTree.js, src/components/Sidenav/IA.js, src/components/Sidenav/Sidenav.js, src/components/Sidenav/SidenavBackButton.js, src/components/Sidenav/TOCNode.js, src/components/Sidenav/styles/sideNavItem.js, tests/unit/__snapshots__/GuidesLandingTree.test.js.snap
DOP-3343
[drivers](https://www.mongodb.com/docs/drivers/)
[landing](https://www.mongodb.com/docs/)
[app services](https://www.mongodb.com/docs/atlas/app-services/)
[tutorials](https://www.mongodb.com/docs/guides/)
[drivers](https://docs-mongodbcom-integration.corp.mongodb.com/DOP-3343/drivers/seung.park/DOP-3343/)
[landing](https://docs-mongodbcom-integration.corp.mongodb.com/master/landing/seung.park/DOP-3343/)
[app services](https://docs-mongodbcom-integration.corp.mongodb.com/DOP-3343/atlas-app-services/seung.park/DOP-3343/)
[tutorials](https://docs-mongodbcom-integration.corp.mongodb.com/f81f5376b71fbcec68989e99960e545694b29098/DOP-3343/guides/seung.park/DOP-3343/atlas/account/)
this change may have resulted in the change of [LG/emotion …
=> DOP-3343: fix ToC styling

src/components/Contents/ContentsList.js
DOP-2591
[right column in compass](https://www.mongodb.com/docs/compass/current/collections/)
[right column in guides](https://www.mongodb.com/docs/guides/)
[right column in compass](https://docs-mongodbcom-integration.corp.mongodb.com/DOP-2591/compass/seung.park/DOP-2591/collections/)
[right column in guides](https://docs-mongodbcom-integration.corp.mongodb.com/master/guides/seung.park/DOP-2591/)
- the changes are evident in the `on this page` and `chapters` labels on the right column
=> DOP-2591: fix styling on 'on this page'

src/components/RootProvider.js, src/components/VersionDropdown/index.js, src/context/version-context.js, src/layouts/index.js, src/utils/url-utils.js
DOP-3362
[prod behavior](https://www.mongodb.com/docs/manual/core/data-modeling-introduction/)
flipping the version on the left side does not automatically take you to the **same page** on a different version of the doc
[staged changes](https://docs-mongodbcom-integration.corp.mongodb.com/master/docs/seung.park/DOP-3362/core/data-modeling-introduction/)
changing the version on the left side leads to a 404 (but this is desired) since url parsing is not working well between environments, but correct slug is being appended to the destination URL
- would be neat to clean up url parse to work interchangeably with environments, as a follow up to env cleanups
=> DOP-3362: include slug in url when changing versions

src/templates/landing.js
[DOP-3265](https://jira.mongodb.org/browse/DOP-3265)
[Current Site](https://www.mongodb.com/docs/)
[Staging Site with this new text color](https://docs-mongodbcom-integration.corp.mongodb.com/DOP-3265-illustrations/landing/matt.meigs/DOP-3265-landing/)
Overwrites leafygreen's h1 color to match the [figma designs](https://www.figma.com/file/2ZUCjznoCNNFhEzuaMTw8c/Docs-Homepage?node-id=532%3A3406) with the new hero image on the Landing page.
Alters the body's text over the hero image as well."
- Has media queries because below "medium" size screen, the text leaves the image and is on top of a white background.
Note: This PR is needed to deploy along with the new landing site hero image to ensure readability with its change as well.
=> DOP-3265: Update header colors for new hero image on Landing page

gatsby-node.js, src/context/version-context.js, src/hooks/use-site-metadata.js, src/utils/site-metadata.js, tests/context/version-context.test.js
Minor clean up: Follow up to DOP-3361:
Moving the `associated_products` property from front end graphql's `siteMetadata` to `snootyMetadata` as it should be.
SiteMetadata should contain info about the site being built and all other metadata should be obtainable from snootyMetadata node
**status:** ready for review
**regression staging links** :
[cloud docs](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/seung.park/DOP-3361-follow-up/)
[atlas cli](https://docs-mongodbcom-integration.corp.mongodb.com/master/atlas-cli/seung.park/DOP-3361-follow-up/)
[docs landing](https://docs-mongodbcom-integration.corp.mongodb.com/master/landing/seung.park/DOP-3361-follow-up/)
=> DOP-3361: moving around metadata

src/components/SearchResults/SearchResults.js, src/utils/escape-reserved-html-characters.js
DOP-2863
[\<boolean\> left out of search preview in prod](https://www.mongodb.com/docs/search/?q=exists)
[Landing with "exists" search query and visible \<boolean\>](https://docs-mongodbcom-integration.corp.mongodb.com/master/landing/allison/master/search/?q=exists)
I am not attached to the naming of the util if folks have better ideas. `replaceAll` is apparently great on all 2020+ browsers; if we need to support older ones, I can swap it to `replace` with a regex, but this seems reasonable to me (particularly since I don't think we *have* an official list of supported browsers?).
=> DOP-2863: escape HTML characters in search preview

src/components/FieldList/Field.js, tests/unit/__snapshots__/FieldList.test.js.snap
DOP-3236
updating font size on `return` statements for Code examples
[server docs example](https://www.mongodb.com/docs/manual/reference/method/KeyVault.addKeyAlternateName/#mongodb-method-KeyVault.addKeyAlternateName)
[server docs example 2](https://www.mongodb.com/docs/manual/reference/method/db.collection.replaceOne/#definition)
[staged server docs example 1](https://docs-mongodbcom-integration.corp.mongodb.com/master/docs/seung.park/DOP-3236/reference/method/KeyVault.addKeyAlternateName/#mongodb-method-KeyVault.addKeyAlternateName)
[staged server docs example 2](https://docs-mongodbcom-integration.corp.mongodb.com/master/docs/seung.park/DOP-3236/reference/method/db.collection.replaceOne/#definition)
=> DOP-3236: add font size for field component

src/components/SearchResults/SearchResults.js, src/components/Searchbar/SearchResult.js, src/utils/escape-reserved-html-characters.js, tests/unit/__snapshots__/SearchResults.test.js.snap
DOP-3374
[Search ?q=test](https://www.mongodb.com/docs/search/?q=test) - should lead to rendering error
[Search ?q=exists](https://www.mongodb.com/docs/search/?q=exists) - should load properly with escaped "<" and ">"
[Search ?q=test](https://docs-mongodbcom-integration.corp.mongodb.com/master/landing/raymundrodriguez/DOP-3374/search/?q=test) - should render, with a search result with empty preview text
[Search ?q=exists](https://docs-mongodbcom-integration.corp.mongodb.com/master/landing/raymundrodriguez/DOP-3374/search/?q=exists) - should work the same as current behavior
* Search results with no previews will continue to be rendered, but with some reserved space within the card to keep consistent styling with other cards that do have previews. Otherwise, the tags at the bottom of the …
=> DOP-3374: Render search results with empty previews

src/utils/append-trailing-punctuation.js, tests/unit/utils/append-trailing-punctuation.test.js
This fixes an issue where a trailing period would be appended in to the value of a node type with no value field, effectively causing the period to be truncated.
DOP-3327
* https://www.mongodb.com/docs/atlas/cli/stable/
* https://docs-mongodbcom-integration.corp.mongodb.com/master/atlas-cli/heli/DOP-3327/
=> DOP-3327: Move entire dangling node in appendTrailingPunctuation() rather than just value

src/components/Chapters/Chapter.js, src/components/Contents/ContentsListItem.js, src/components/DriversIndexTiles.js, tests/unit/__snapshots__/Chapter.test.js.snap
DOP-3403
Goal is to convert any `styled` leafygreen components into classNames so that this can be SSR'ed and not hydrated. 
This PR aims to only affect guides, given the scope of these components (chapters, contentlistitem -> is this used elsewhere? 
guides on prod
https://www.mongodb.com/docs/guides/
guides with staged changes
https://docs-mongodbcom-integration.corp.mongodb.com/master/guides/seung.park/DOP-3403-guides/
regression check for ContentListItem
https://docs-mongodbcom-integration.corp.mongodb.com/master/docs/seung.park/DOP-3403-guides/crud/
see prod version for a flash of styles that should be overwritten (ie. card padding, right column link styling)
=> DOP-3403: guides

src/components/Sidenav/TOCNode.js
DOP-3436
- minor change to check for existence of children for ToC nodes. over checking, since PR to insert empty children into associated ToC nodes is in place: https://github.com/mongodb/snooty-parser/pull/438
=> DOP-3436 front end

gatsby-ssr.js, src/html.js
DOP-2077
This PR adds the `name="robots"`  meta tag to the Helmet package so it is overwrite-able by nested or latter components
[staging link incoming with master branch](https://docs-mongodbcom-integration.corp.mongodb.com/master/atlas-open-service-broker/seung.park/master/)
note above link has two meta tags with the above tag
[staged link with repo branch as noted below](https://docs-mongodbcom-integration.corp.mongodb.com/master/atlas-open-service-broker/seung.park/DOP-2077/)
- both staged links are coming from[ this branch](https://github.com/schmalliso/cloud-docs-osb)
=> DOP-2077: add robots meta to Helmet

package-lock.json, package.json
DOP-3459
https://docs-mongodbcom-integration.corp.mongodb.com/master/guides/cassidy.schaufele/DOP-3459/
https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/cassidy.schaufele/DOP-3459/
Bumps us to 1.2.27 of the `consistent-nav`. See [conversation 1](https://mongodb.slack.com/archives/C020RL04PS7/p1673301365715419) and [conversation 2](https://mongodb.slack.com/archives/C02BMJU3K36/p1674072730455029) for additional context.
New version changes some links to promote Developer Data Platform positioning.
=> DOP-3459: Bump Consistent Nav Version

gatsby-node.js, src/utils/is-openapi-cli-page.js
[DOP-3469](https://jira.mongodb.org/browse/DOP-3469)
The current SSR OpenAPI implementation using Redoc CLI is up and running. For safety, this was enabled to overwrite the file that Snooty currently still builds using the frontend Redoc component. We have no need to build the client-side page anymore. 
This PR disables a snooty frontend page build on all openapi pages except for one - [the docs-landing preview page](https://www.mongodb.com/docs/openapi/preview/).
=> DOP-3469: Do not build OpenAPI pages using snooty except for :preview: page

gatsby-config.js, gatsby-node.js
Original ticket
[DOP-3388](https://jira.mongodb.org/browse/DOP-3388)
Preview build is based off of two conditions being true: the exact environment name(`siteMetadata.snootyEnv`) being equal to "prd" and the `PREVIEW_BUILD_ENABLED` flag uppercased being strictly equal to "TRUE". 
The `PREVIEW_BUILD_ENABLED` flag is correctly set in a gitPush "writer's build" job [as seen in within the ECS instance](https://us-east-2.console.aws.amazon.com/ecs/v2/task-definitions/docs-worker-pool-prd/30/json?region=us-east-2).
However, the environment designated for preview build (prd) sets the environment string passed to `siteMetadata.snootyEnv` from `SNOOTY_ENV` which is not equal to "prd" but rather set to "production" [here](https://github.com/mongodb/docs-worker-pool/blob/master/infrastructure/ecs-mai …
=> DOP-3388-B: Writer preview build conditioned on string "production" rather than "prd"

src/components/DriversIndexTiles.js
Updating the link in the DriversIndexTiles component for C# to link to the newly released documentation
=> Update Driver Tile link to new csharp docs

src/utils/realm.js
[DOP-3473](https://jira.mongodb.org/browse/DOP-3473)
current behavior when you (first load ie. incognito window) any docs website, is that you would see multiple network requests to `https://stitch.mongodb.com/api/client/v2.0/app/snooty-koueq/auth/providers/anon-user/login`:
https://www.mongodb.com/docs/atlas/
on the staged link, you should see only one request to the above URL. (two, given feedback realm app requires a login as well)
https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/seung.park/DOP-3473/
=> return a deferred promise for login when calling realm functions

src/context/toc-context.js
minor fix up on filtering ToC.
while investigating https://jira.mongodb.org/browse/DOP-3499, I noticed that we are hiding a ToC node if it's children list was empty. although the children list should ideally not be empty (this was a bug as noted in DOP-3499), it should still render the original ToC node without the children list.
**note**: bad data highlighted in DOP-3499 is used in the staging links below
[staged master branch with embedded flag on](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/seung.park/master/) (notice atlas-cli is completely missing, due to bad data)
[staged change (notice atlas-cli ToC is present, but missing children due to bad data)](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/seung.park/minor-toc-fix/)
=> Embedded minor fixup: include empty toc

src/components/Header/preview-header.js, src/layouts/preview-layout.js
[DOP-3514](https://jira.mongodb.org/browse/DOP-3514)
["Current" Behavior](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/matt.meigs/DOP-3388-omit-nav/) 
[Staging Link with indicator](https://docs-mongodbcom-integration.corp.mongodb.com/master/docs/matt.meigs/master/)
Added a text indicator for writer's staging builds to let stakeholders be aware of reasoning behind empty header/footer
Text is currently "This is a staging build." I am amenable to changes to that!
Other changes: Made new placeholder nav mobile responsive and removed unused `eol` prop
=> DOP-3514: Indicator for writer staging in header

src/components/Sidenav/TOCNode.js
minor fix. was encountering React error warnings for non unique key, with ToC nodes having same slug in associated metadata:
below metadata shows two ToC nodes with same slug with different options. key of Node JSX was throwing errors on master branch
produces errors on front end:
[staged changes](https://docs-mongodbcom-integration.corp.mongodb.com/master/atlas-cli/seung.park/unique-key-for-toc/)
[master branch with test data](https://docs-mongodbcom-integration.corp.mongodb.com/5aae0f7ee5aa0cbcc5d9ddf591fdcd31b349b35e/master/atlas-cli/seung.park/master/) (embedded version flag turned on) - nodes are failing to be removed because of their non unique keys. was encountering console issues as:
```
Warning: Encountered two children with the same key, `/`. Keys should be unique so that …
```
=> fixup: make unique key for toc node with versions

src/components/Select.js, src/components/Sidenav/VersionSelector.js, tests/unit/__snapshots__/SearchResults.test.js.snap, tests/unit/__snapshots__/Select.test.js.snap
DOP-3513
styling version dropdown for overflow and mobile views.
this PR only addresses styling so navigation via select dropdown is being addressed in DOP-3500
[master branch cloud docs with embedded flag turned on](https://docs-mongodbcom-integration.corp.mongodb.com/5aae0f7ee5aa0cbcc5d9ddf591fdcd31b349b35e/master/cloud-docs/seung.park/HEAD/)
[atlas cli docs with version dropdown styled](https://docs-mongodbcom-integration.corp.mongodb.com/master/atlas-cli/seung.park/DOP-3513/)
[cloud docs with version dropdown styled](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/seung.park/DOP-3513/)
- the test data was produced by repeating the [text for the Select Option choice](https://github.com/mongodb/snooty/blob/master/src/components/Sidenav/VersionSelector.js#L9)
- …
=> DOP-3513 style version selector for overflow and mobile

gatsby-node.js
there exists a catch block that mitigates this error (thankfully) but we should be checking for nulls before calling `.length`
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63efbd0205dd3cc814e5335f
=> add nullish check for associated products value

src/context/version-context.js
minor change to unrequire versions in snooty.toml  associated_products property
was testing couple PR's with [this line](https://github.com/10gen/cloud-docs/blob/b86dad571aac1116beec159313dbab7bfaa9bcf3/snooty.toml#L1111) removed and noticed the front end was still cross checking for options specified in snooty.toml
=> unrequire associated_products.versions on front end

gatsby-node.js, src/hooks/use-remote-metadata.js, src/layouts/index.js
DOP-3541
* [Atlas](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/raymundrodriguez/DOP-3541/)
* [Atlas CLI](https://docs-mongodbcom-integration.corp.mongodb.com/master/atlas-cli/raymundrodriguez/DOP-3541/)
* [Atlas App Services](https://docs-mongodbcom-integration.corp.mongodb.com/master/atlas-app-services/raymundrodriguez/DOP-3541/)
* [Server](https://docs-mongodbcom-integration.corp.mongodb.com/master/docs/raymundrodriguez/DOP-3541/)
* Uses a node for `remoteMetadata` instead of passing it in `pageContext`. Node schema is barebones for now. Logic changes are also minimal to ensure no differences in functionality.
* Merging this into the `gatsbyv4` branch for now since Gatsby v2 on the `master` …
=> DOP-3541: Create node for remote metadata

src/components/Select.js, src/components/Sidenav/TOCNode.js, src/context/toc-context.js, src/context/version-context.js, tests/context/toc-context.test.js, tests/context/version-context.test.js, tests/unit/__snapshots__/SearchResults.test.js.snap
DOP-3550
DOP-3549
[atlas cli](https://www.mongodb.com/docs/atlas/cli/upcoming/)
[atlas](https://www.mongodb.com/docs/atlas/)
[server docs](https://www.mongodb.com/docs/manual/)
[atlas cli](https://docs-mongodbcom-integration.corp.mongodb.com/3e2e1d8c5b30dee0c7fb0d80a29ce96f1e0f0e1f/master/atlas-cli/seung.park/DOP-3549/)
[atlas](https://docs-mongodbcom-integration.corp.mongodb.com/3e2e1d8c5b30dee0c7fb0d80a29ce96f1e0f0e1f/master/cloud-docs/seung.park/DOP-3549/)
[server docs (select component regression test)](https://docs-mongodbcom-integration.corp.mongodb.com/3e2e1d8c5b30dee0c7fb0d80a29ce96f1e0f0e1f/master/docs/seung.park/DOP-3549/)
- addresses DOP-3550 by removing the logic to `correct the active version` <- this was a race between version context and toc context, and [toc-context would …
=> DOP-3549 DOP-3550

src/components/Instruqt.js
DOP-3666
minor margin below instruqt labs controls to account for paragraphs under iframes.
sourced repository is from @rayangler 's SW sample: https://github.com/rayangler/docs/tree/sw-2023-instruqt
[staged above repo on master branch
](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/sw-2023-instruqt/docs/seung.park/master/instruqt-sample/index.html)
[staged changes on branch](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/sw-2023-instruqt/docs/seung.park/DOP-3666/instruqt-sample/index.html)
=> DOP-3666 add bottom margin for instruqt labs

src/components/SearchResults/SearchResults.js, tests/unit/__snapshots__/SearchResults.test.js.snap
DOP-3608
[prod link with search results](https://www.mongodb.com/docs/search/?q=test)
opening the above link may flash a `no results found` before actually showing results
**NOTE:** opening network tab and refreshing this page shows **two** requests to `https://docs-search-transport.mongodb.com/search?q=test`
[staging link for search page](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/seung.park/DOP-3608/search/index.html?q=test)
(cannot refresh above link due to S3 hosting issues). can test refresh by copying and pasting link https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/seung.park/DOP-3608/search/index.html?q=test
- does not show `no results found` when opening link, should only fire one request to search transport server for the query
- …
=> DOP-3608: wait for manifest to fire search

src/components/ComponentFactory.js, src/components/OpenAPIChangelog/ChangeList.js, src/components/OpenAPIChangelog/FiltersPanel.js, src/components/OpenAPIChangelog/OpenAPIChangelog.js, src/components/OpenAPIChangelog/index.js, src/templates/changelog.js, src/templates/index.js, src/utils/get-template.js
DOP-3677
Net new template page, component directory, and OpenAPIChangelog component structured out for future work on the changelog.
[UI Design](https://www.figma.com/file/Tal3RZFxMEz6u1tnilxwRY/API-Change-Log?type=design&node-id=1-539&t=3o9XrD5Lijm9ighd-0).
=> DOP-3677: OpenAPIChangelog component structure, template

.gitignore, src/components/Target.js
DOP-2317
We supported cssclass to hide components previously; now we'll let writers use a `:hidden:` flag on their methods if they want to hide them, and respect that.
https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-3627/atlas-app-services/allison/master/functions/mongodb/api/
=> DOP-2317: comply with the  hidden flag for targets

src/components/VersionDropdown/index.js
[see slack thread](https://mongodb.slack.com/archives/C018UTGP23T/p1683905669887079)
caused by referencing url slug instead of gitBranchName (expected by [VersionContext ](https://github.com/mongodb/snooty/blob/master/src/context/version-context.js#L209-L210) )
**staging link:**
https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/seung.park/gitbranchname-fix/index.html
verify that above dropdown leads to v7 URL (invalid URL for other S3 issues for staging links)
=> DOP-3697-follow up

gatsby-ssr.js
DOP-3556
https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/cassidy.schaufele/DOP-3556/index.html
Per discussion on 3556, this sets the Optimizely script to load synchronously.
=> DOP-3556: Switch Optimizely load type for (hopefully) the last time

gatsby-node.js, src/components/OpenAPIChangelog/OpenAPIChangelog.js, src/components/OpenAPIChangelog/components/ChangeList.js, src/components/OpenAPIChangelog/components/FiltersPanel/components/DiffSelect.js, src/components/OpenAPIChangelog/components/FiltersPanel/components/FiltersPanel.js, src/components/OpenAPIChangelog/components/ResourceChangesBlock.js, src/components/OpenAPIChangelog/utils/getDiffRequestFormat.js, src/components/OpenAPIChangelog/utils/useFetchDiff.js, src/utils/realm.js, tests/unit/ChangeList.test.js, tests/unit/OpenAPIChangelog.test.js, tests/unit/__snapshots__/ChangeList.test.js.snap, tests/unit/__snapshots__/OpenAPIChangelog.test.js.snap, tests/unit/data/OpenAPIChangelog.js
DOP-3617
The `OpenAPIChangelog` now dynamically fetches the diff between two `Resource Versions` whenever a user chooses two `Resource Versions` to compare. 
Also:
- moves the appending of " (latest)" to a display value rather than modifying the value in state.
- deals with `SegmentedContro`l `aria-controls` warning
- removes the change badges from the diffs as referenced by the design
- hides any changes that have the `changeType` "operation-id-changed" or "operation-tag-changed" as desired by APIx
- creates an [Atlas App Services Function](https://realm.mongodb.com/groups/5bad1d3d96e82129f16c5df3/apps/5d41ef5e2de84772fc7c2de2/functions/646cc47cf571983e9ce0671e) `fetchOADiff` to enable this querying and to bypass CORS
=> DOP-3716: dynamically fetches diff for OpenAPIChangelog

Makefile
N/A
[Atlas App Services](https://www.mongodb.com/atlas/app-services/)
[Atlas App Services](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/atlas-app-services/raymundrodriguez/replace-staging-host/index.html), just as a control to help see Makefile output, but no changes applied.
* Updates the staging url hostname used by the Makefile.
* For now, we don't use the hostname that we had on Fastly for staging. We have to use the S3 bucket's url with `index.html` appended at the end of the page path.
=> Echo S3 url for staging

gatsby-node.js, src/components/OpenAPIChangelog/OpenAPIChangelog.js, src/components/OpenAPIChangelog/utils/getDiffRequestFormat.js, src/init/DocumentDatabase.js
DOP-3720
On the event of any error in fetching OpenAPI Changelog data, Snooty should read the last successful runId from Atlas to gain valid data for the build.
The `openapi_changelog.atlas_admin_metadata` collection in Atlas will hold the last successful run's metadata.
On a successful build of changelog data, Snooty will upsert the metadata object directly into this collection. 
On errored builds of changelog data, Snooty will fallback to read this older metadata from Atlas and use the requisite data to successfully build the Atlas Admin Changelog.
Note: Also two bugs are fixed in this PR:
- on diff loading state, ensure that the previous diff is not shown along with the loading skeleton
- when sorting Resource Versions by date, slice Resource Version string down to a simple date (there …
=> DOP-3720: OpenAPI Changelog fallback to RunId

src/components/OpenAPIChangelog/components/FiltersPanel/components/FiltersPanel.js
DOP-3758
From UAT feedback:
The small chips could be confusing for users. Alas, LG cannot change the text in the Chip. However, this PR allows non-mobile users to see much longer Chips to have more context on what's chosen. The hover tooltip further clarifies.
=> DOP-3758: Changelog: Change chip size

src/components/Sidenav/TOCNode.js, src/components/Sidenav/VersionSelector.js, src/context/toc-context.js, src/context/version-context.js, tests/context/version-context.test.js, tests/unit/Toctree.test.js
DOP-3651
console logs in atlas docs show react hydration errors
[atlas docs](https://www.mongodb.com/docs/atlas/)
[atlas cli docs](https://www.mongodb.com/docs/atlas/cli/upcoming/)
[atlas docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/seung.park/DOP-3651/)
[atlas cli docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/atlas-cli/seung.park/DOP-3651/index.html)
two fixes to address these issues:
- [react error](https://legacy.reactjs.org/docs/error-decoder.html/?invariant=418) -> ie. `build time component does not match client side initial render` this was due to attempting to read local storage for initial values, which the server side does not. removed any local storage assumptions for init values. **note** this results in associated ToC …
=> DOP-3651: version context cleanup, use local storage only on front end

gatsby-node.js, src/components/OpenAPIChangelog/OpenAPIChangelog.js, src/components/OpenAPIChangelog/components/ResourceChangesBlock.js, src/components/OpenAPIChangelog/utils/constants.js, tests/unit/__snapshots__/OpenAPIChangelog.test.js.snap
DOP-3756
[Staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/changelog/cloud-docs/matt.meigs/DOP-3756-download/reference/api-changelog/index.html)
Updates all references to Changelog data fetching to new S3 bucket address for prod data. 
No longer needed to parse `yaml` because the data is available in both `yaml` and `json` formats.
This PR also changes the text of the Download API Changelog button to be "Download Full API Changelog" :) 
One last change in this PR is to account for possibly null values within the main changelog changes array. This will only occur in the first change of the array as the APIx team is using this blank change at points to override the `changeType` for the `changeTypeBadge`. We ignore these nulls in the UI but use the data to display the correct …
=> DOP-3756: update S3 bucket for Changelog to prod

package-lock.json, package.json
DOP-3825
There isn't Vector Search in the top nav.
Now there is: https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/allison/master/
=> DOP-3825: bump top nav to 1.2.39

plugins/gatsby-source-snooty-preview/gatsby-node.js, plugins/gatsby-source-snooty-preview/utils/post-build.js
DOP-3890
* [Build log](https://www.gatsbyjs.com/dashboard/083213ad-92d8-4d3f-af78-848bb8100c91/sites/51bd00fd-eaf5-4965-8493-f52ac88723c6/builds/e1a5f0ed-118c-4b04-82ee-dfaab63dec11/details?returnTo=%2Fdashboard%2F083213ad-92d8-4d3f-af78-848bb8100c91%2Fsites%2F51bd00fd-eaf5-4965-8493-f52ac88723c6%2FcmsPreview#rawLogs) where webhook was called (see "Post-build webhook was successfully called!" log message). The job ID present in the webhook body `64ca88c35de6a8485ac4de7c` was also successfully called.
* I tried to cover major/obvious points of failure by calling the webhook when those may potentially occur. This might not necessarily be exhaustive and we may need to add more calls in the future as needed.
=> DOP-3890: Call post-build webhook

plugins/gatsby-source-snooty-preview/gatsby-node.js, src/components/InternalPageNav.js
DOP-3982
Currently each page's internal nav (back and forward) buttons are just a forward button to go back to "What is MongoDB Atlas?" example: https://preview-mongodbmmeigs.gatsbyjs.io/cloud-docs/matt-build/cloud-providers-regions/
This was caused by the slug passed to each page having a forward slash prepended which does not match the toctree mappings.
=> DOP-3982: Fix internal navigation in Gatsby plugin

src/components/ChatbotUi.js, src/constants.js
DOP-3996
The chatbot team would like our non-prod environments to point the Chatbot towards their staging link. This uses the SNOOTY_ENV to determine this.
Would love a second pair of eyes and confirmations on the fact that SNOOTY_ENV's values could all be 'production' and 'dotcomprd'
=> DOP-3996: Chatbot server url

gatsby-config.js, plugins/gatsby-source-snooty-preview/gatsby-node.js, src/components/Link.js, src/context/toc-context.js, src/utils/is-current-page.js, src/utils/is-gatsby-preview.js, tests/context/toc-context.test.js
DOP-4009
[prd Gatsby Cloud site](https://preview-mongodbkanchanamongodb.gatsbyjs.io/cloud-docs/DOCSP-32895/atlas-search/knn-beta/) - Notice how the side nav does not show the "knn beta" page
[stg Gatsby Cloud site](https://preview-mongodbrayanglerstg.gatsbyjs.io/cloud-docs/test-master/atlas-search/knn-beta/) - The side nav now shows the expected content and no longer shows the version selector for associated products (this behavior matches current staging builds).
Seems like the TOC is fetching data on initial load of the page, which can result in incorrect TOC data, especially if the current changes of the branch don't match up with the TOC metadata being fetched from the db.
The `parserBranch` variable, which is tied to the declared branch that the site is for, is currently used when …
=> DOP-4009: Avoid fetching TOC data for preview builds

src/components/ChatbotUi.js
Clean up of 
DOP-3996
As Raymund pointed out [here](https://github.com/mongodb/snooty/pull/880#discussion_r1319143056), the SNOOTY_ENV value of "production" is used for writer's staging. Docs writer's staging should use the staging Chatbot server url for visibility in testing.
=> DOP-3996: Allow writer's staging to use staging Chatbot server url

src/components/Heading.js, src/components/Widgets/index.js
DOP-4025
Follow up to [previous PR](https://github.com/mongodb/snooty/pull/902)
[FeedbackHeading](https://github.com/mongodb/snooty/blob/master/src/components/Heading.js#L57) on mobile was calling Feedback context values with no provider being initiated:
```
index.modern.mjs:1 Uncaught Error: You must nest useFeedbackContext() inside of a FeedbackProvider.
at useFeedbackContext (context.js:102:1)
at FeedbackHeading (FeedbackHeading.js:6:1)
at renderWithHooks (react-dom.development.js:16305:1)
at mountIndeterminateComponent (react-dom.development.js:20074:1)
at beginWork (react-dom.development.js:21587:1)
at beginWork$1 (react-dom.development.js:27426:1)
at performUnitOfWork (react-dom.development.js:26557:1)
at workLoopSync (react-dom.development.js:26466:1)
at renderRootSync …
```
=> DOP-4025 follow up

tests/unit/Head.test.js, tests/unit/IA.test.js, tests/utils/mockStaticQuery.js
DOP-3893
* This PR fixes tests that broke after merging the `master` to the `gatsby-cloud-rc` branch.
* Seems like no other tests are currently broken thanks to Michal! (The GH action to run the tests do not work for the current base branch, but this can be confirmed by running `npm run test` locally)
=> DOP-3893: Fix tests for plugin compatibility

src/components/Button.js, tests/unit/__snapshots__/Button.test.js.snap
Enabling buttons to have href links.
We are using a combination of <Button> and <Link> components when rendering `:button:` ReST components with :uri: options ([example here](https://github.com/mongodb/docs-landing/pull/132/files#diff-f9560dd277cc6f848625b9db1465ddf3779112495f2d1cc559ff3f91ea6d186cR180)) which is a pretty common pattern in our docs
The `href` prop was being passed to Link component as `undefined` and therefore had a null Button with no href.
The docs are not super clear, but [the example](https://www.mongodb.design/component/button/documentation/) for `as` shows them explicitly pulling out the `href` prop when passing to a NextLink
[master branch has buttons disabled with links](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/)
[new homepage with …
=> pass href to link, for it to be not undefined

src/components/Landing/MoreWays/index.js, src/templates/landing.js
Minor change to use negative column for `grid-column-end`
[mobile view of video and card group on mobile:](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/)
[change on branch](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/cd384df47f04f518017bd11b4c2877e19c4df008/newhomepagewhodis/landing/seung.park/moreways-mobile-video/index.html)
=> Homepage redesign: more ways mobile video

src/components/OpenAPIChangelog/utils/constants.js
DOP-4041
Currently on prod, the OpenAPIChangelog download button does not work correctly. It is referencing the staging S3 bucket with a production runId. This adds a check for the 'dotcomprd' snooty env value.
=> DOP-4041: Changelog download button broken

src/components/ChatbotUi.js
N/A
updates the chatbot component to pull `snootyEnv` from the `site-metadata` hook and not the raw PROCESS.ENV - gatsby can only fetch GATSBY_ prefixed env vars at client side render time
=> hotfix: Use hook for snootyenv

src/components/Landing/MoreWays/index.js, src/components/LandingIntro/index.js, src/components/SectionHeader.js
[DOP-4053](https://jira.mongodb.org/browse/DOP-4053)
The new homepage hardcoded some of the headings in the components using the relevant LG components per the design, but didn't include the as props so that the headings render as the correct h-type in the DOM. 
[Prod Homepage](https://www.mongodb.com/docs/)
[homepage staging link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/anabella.buckvar/DOP-4053/)
=> DOP-4053: Update Headers to use correct "as" headings

src/components/Sidenav/Sidenav.js
[DOP-4054](https://jira.mongodb.org/browse/DOP-4054)
[prod homepage](https://www.mongodb.com/docs/)
[staging homepage](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/anabella.buckvar/DOP-4054/index.html)
=> DOP-4054: Update Uni and Community left sidenav links on landing to subfolder versions

src/components/Button.js
[DOP-4051](https://jira.mongodb.org/browse/DOP-4051)
An error for "undefined" glyphs appears during the frontend build stage because the `Button` component expected a rightGlyph.
[staging
](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/anabella.buckvar/DOP-4051/index.html)
=> DOP-4051: Fix Undefined Icon Warning in Frontend

src/components/SearchResults/Facets/FacetValue.js, src/components/SearchResults/SearchContext.js
small change to remove selectedFacets as a state, and read from url query params
behavior should be the same (FacetValues can be selected to append new url search params)
from notes:
```
- option 4: 
- expose search params from context
- iterate over all options to show pills (that are in the exposed search params from context) <- not done in this PR
- in facet value component (check if search params has this facet.key) to make it checked
- also, facet value component, check if all childrens' keys are selected (to make it full check vs half check) <- not done in this PR
```
=> DOP-3690: remove selectedFacets as a state. read from url params

plugins/gatsby-source-snooty-preview/gatsby-node.js, plugins/gatsby-source-snooty-preview/utils/data-consumer.js, src/utils/setup/save-asset-files.js
DOP-4063
This change is strictly for the Gatsby Cloud preview plugin, but not changes should be made. A successful refactoring means that the staging links build with correct side navs (for metadata), pages (for pages), and images (for assets).
[cloud-docs](https://preview-mongodbrayangler.gatsbyjs.io/cloud-docs/gc-test-img/)
[docs](https://preview-mongodbrayangler.gatsbyjs.io/docs/DOP-4063-test/)
* The bulk of this PR is just reorganizing the way data was being consumed from the Snooty Data API so that it was less nested, and easier to maintain. There should be no functional changes other than some additional proactive error handling for incorrect data formats to help improve completeness.
=> DOP-4063: Reorganize data consumption for preview plugin

src/components/DocumentBody.js
We want the locale flipper to flip you to the same page as you're on.
It points to the equivalent of www.mongodb.com/docs/
https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/newhomepagewhodis/landing/allison/smartlingslug/tools-and-connectors/index.html
=> add slug to locale switcher

src/components/Header/index.js, src/layouts/index.js
[DOP-3700](https://jira.mongodb.org/browse/DOP-3700)
Currently, on every page except https://mongodb.com/docs/ there is a large white space at the bottom of each page of the docs on Firefox. This PR removes one line of styling that fixes the gap issue on Firefox; I believe it doesn't affect any other behavior but I could be wrong.
[Staging environment](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/maya/DOP-3700-new/)
=> Dop 3700 new

src/components/SearchResults/Facets/FacetTags.js, src/components/SearchResults/Facets/Facets.js, src/components/SearchResults/Facets/utils.js, src/components/SearchResults/SearchContext.js, src/components/SearchResults/SearchResult.js, src/components/SearchResults/SearchResults.js, src/components/Tag.js, tests/unit/__snapshots__/SearchResults.test.js.snap
[DOP-4065](https://jira.mongodb.org/browse/DOP-4065)
This PR utilizes new attributes returned from /search API endpoint, specifically `documents[].facets[]` Example here: https://docs-search-transport.mongodb.com/search?q=$and
Goal is the show the tagged facets on each document in the search results
[Current behavior on prod:](https://www.mongodb.com/docs/search/?q=$or)
[Current behavior on master with feature flag on, shows no facet tags on search results](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/newhomepagewhodis/landing/seung.park/master/search/index.html?q=$or)
[Staged changes with feature flag = off](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/newhomepagewhodis/landing/seung.park/DOP-4065-frontend/search/index.html?q=$or)
[Staged changes with feature flag …
=> DOP-4065 frontend

src/components/DeprecatedVersionSelector.js
DOP-4098
N/A
N/A
Part of me searching through all DOP codebases to ensure we are not pulling in `prefix`, `bucket`, and `URL` from `repo_branches`, I stumbled across an outdated comment, and this PR updates that to reflect that `URL` now comes from `docsets` collection.
=> :bulb: DOP-4098 updates comment to reflect pulling from docset instead of repo_branches

src/components/ChatbotUi.js
[DOP-4112](https://jira.mongodb.org/browse/DOP-4112)
Currently, the loading skeleton for the chatbot is large enough to overflow the input bar. This changes the skeleton to have a height of 48px and be properly centered within the input bar.
[Staging link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/maya/DOP-4112/)
=> DOP-4112: Adjusting size of chatbot loading skeleton to not overflow input bar

src/components/Code/Code.js, src/components/Instruqt.js
[DOP-4084](https://jira.mongodb.org/browse/DOP-4084)
Frontend builds emit an error due to missing aria-labels for LeafyGreen's IconButton component
[Current behavior- docs Kotlin driver
](https://www.mongodb.com/docs/drivers/kotlin/coroutine/current/fundamentals/crud/read-operations/geo/)
[Current behavior- docs manual](https://www.mongodb.com/docs/manual/tutorial/getting-started/)
[Example build log for kotlin](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6525bd67885de6b26b544fbe)
[Docs manual](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/anabella.buckvar/master/tutorial/getting-started/index.html)
[Kotlin driver](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/kotlin/anabella.buckvar/master/fundamentals/crud/read-ope …
=> DOP-4084: IconButton missing aria-label leads to frontend errors

src/components/Tabs/index.js
[DOP-4132](https://jira.mongodb.org/browse/DOP-4132)
Currently, on the production [docs manual homepage](https://www.mongodb.com/docs/manual/), a row of horizontal tabs overlap when the screen size reaches a width of 1200px, the xLarge breakpoint
[docs manual homepage staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/anabella.buckvar/DOP-4132/index.html)
=> DOP-4132 Snooty overlapping tabs bug

src/components/SearchResults/SearchContext.js, src/components/SearchResults/SearchResults.js, src/utils/search-params-to-url.js
DOP-4089
This PR is the front end portion of responsive facets.
Behavior is as outlined:
- Facet list is derived from the `search term` only. (selecting a facet does not change facet list)
- Count is updated when `search term` or `facet selections` are changed
- Facet selections of the same category should count as OR selections
- Facet selections of two different categories should count as AND selections
[current search](https://www.mongodb.com/docs/search/?q=%24and)
[regression check for old search behavior. should behave same as above current behavior](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/newhomepagewhodis/landing/seung.park/DOP-4089/search/index.html?q=%24and)
**no staging link for changes. see steps to test below**
Steps to test:
- requires local search transport …
=> DOP-4089: Facet combination behaviors. Count different category as AND selections, same category as OR

src/components/Figure/Lightbox.js, tests/unit/__snapshots__/Figure.test.js.snap, tests/unit/__snapshots__/Lightbox.test.js.snap
[DOP-4124](https://jira.mongodb.org/browse/DOP-4124)
[current production behavior
](https://www.mongodb.com/docs/atlas/app-services/authentication/api-key/)
[Staging link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/atlas-app-services/anabella.buckvar/DOP-4124/authentication/api-key/index.html)
Large images have been overlapping with content, due to [this css property](https://github.com/mongodb/snooty/blob/059a676527c1c37b93789f340d3c56876e164c66/src/components/Figure/Lightbox.js#L49) that was originally added as part of [DOP-3793](https://jira.mongodb.org/browse/DOP-3793); however, that specific property is unnecessary and deleting it fixes the issue and doesn't affect the behavior requested for [DOP-3793](https://jira.mongodb.org/browse/DOP-3793)
=> DOP-4124 fixed large image overlap

src/components/SearchResults/Facets/FacetGroup.js, src/components/SearchResults/Facets/FacetValue.js, src/components/SearchResults/Facets/FacetVersionGroup.js, src/components/SearchResults/Facets/useFacets.js, src/components/SearchResults/SearchContext.js, src/components/SearchResults/SearchResults.js, src/utils/search-facet-constants.js, src/utils/search-params-to-url.js, tests/unit/data/SearchResults.test.json, tests/unit/utils/mock-marian-fetch.js
DOP-4081
[regression check for existing search with feature flag off `GATSBY_FEATURE_FACETED_SEARCH=false`](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/newhomepagewhodis/landing/seung.park/DOP-4081/search/?q=compass&page=1&searchProperty=atlas-master)
[staging link with test data used ](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/bf468afd223919483e1a071ee959d062620fafb7/newhomepagewhodis/landing/seung.park/DOP-4081/search/index.html?q=%24and&page=1&facets.target_product%3Edocs%3Esub_product=v7.0&facets.target_product=docs)
- This is using test data, as `versions` is not available as facet options yet.
- When a version is selected, parent facet selections are pruned when sending the API request to /search and v2/search/meta since 
- When a parent facet selection is …
=> DOP-4081: version dropdown for facet filters

src/components/SearchResults/SearchResults.js, src/utils/search-facet-constants.js, src/utils/search-params-to-url.js
[DOP-3998](https://jira.mongodb.org/browse/DOP-3998)
current preprd environment makes requests to our production search instance
https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/search/?q=mongodb
(open network tab and see requests for docs-search being made to prod instance `
https://docs-search-transport.mongodb.com/`)
[This staged change](https://docs-mongodbcom-staging.corp.mongodb.com/landing/docsworker-xlarge/DOP-3998-2/search/?q=atlas&page=1) makes requests to `https://docs-search-transport.docs.staging.corp.mongodb.com` 
And is able to bypass CORS errors when user is already authenticated. https://docs-search-transport.docs.staging.corp.mongodb.com/v2/status can verify your authentication
=> DOP-3998: supply credentials with requests to search staging instance

src/components/SearchResults/SearchResults.js
DOP-4144
[docs search on prod with no page in URL query param does not allow next page](https://www.mongodb.com/docs/search/?q=%24elemAt)
[staged changes with no page URL in query param (still allows to navigate to next page)](https://docs-mongodbcom-staging.corp.mongodb.com/cc800abda5dfe62f645022423a560d547c3705c3/newhomepagewhodis/landing/seung.park/DOP-4144/search/?q=mongodb)
- staged changes is making requests to stage search server. must be okta verified at https://docs-search-transport.docs.staging.corp.mongodb.com/v2/status
=> DOP-4144: add default page logic to be 1

package-lock.json, package.json
DOP-4147
[Server docs](https://www.mongodb.com/docs/manual)
[Landing docs](https://www.mongodb.com/docs/)
[Server docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/raymund.rodriguez/DOP-4147/index.html)
[Landing docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/raymund.rodriguez/DOP-4147/index.html)
* To test locally, feel free to run `npm install @mdb/consistent-nav@2.0.3-rc.14`
* All changes listed in the ticket were spot checked and look good
=> DOP-4147: Bump consistent-nav to v2.0.3-rc.14

package-lock.json, package.json
DOP-4200
[Server docs](https://www.mongodb.com/docs/manual/)
[Landing](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/raymund.rodriguez/DOP-4200/index.html)
[Server docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/raymund.rodriguez/DOP-4200/index.html)
* Existing consistent nav behavior between the productions sites and the staging links should be the same (consistent, if you will). The main differences should be those outlined in the Jira ticket (mostly copy and logo size changes).
=> DOP-4200: Bump consistent-nav to v2.0.3-rc.15

src/utils/realm.js
DOP-4178
[Server docs](https://www.mongodb.com/docs/manual/)
[Server docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/raymund.rodriguez/DOP-4178/index.html)
* To verify that the change no longer infinitely creates new users, feel free to clear local storage and refresh the page. The number of users for the Snooty App Service should be 1. Realm should handle refresh tokens and caching anonymous user so that it doesn't result in a new user every time. Compare this behavior with current behavior on production, where new users are added to local storage upon every refresh.
=> DOP-4178: Prevent infinite new anon users for Snooty App Service

src/context/image-context.js
DOP-4207
- Minor fix to check for null images. Was getting a build error `  WebpackError: TypeError: Cannot read properties of null (reading 'relativePath')` on cloud-docs /billing page.
- Verified this works as intended with webp images as in this [staging link ](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/mmeigs-move-ako/cloud-docs/seung.park/DOP-4207-safeguard-null-images/billing/index.html)
=> DOP-4207: check if image exists before calling

plugins/gatsby-source-snooty-preview/gatsby-node.js, plugins/gatsby-source-snooty-prod/gatsby-node.js, plugins/utils/docsets.js, src/components/Image.js, src/components/RootProvider.js, src/context/toc-context.js, src/context/version-context.js, src/hooks/useAllDocsets.js, src/hooks/useAssociatedProducts.js, src/init/DocumentDatabase.js, src/layouts/index.js, src/utils/realm.js, tests/context/toc-context.test.js, tests/context/version-context.test.js, tests/unit/VersionDropdown.test.js
DOP-4264
This behavior is not in prod / stage yet, as we reverted back the doc content changes
[cloud docs with atlas cli and operator ToC's embedded
](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/mmeigs-move-ako/cloud-docs/seung.park/DOP-4264-frontend/index.html)[docs-atlas-cli with atlas cli and operator ToC's embedded into cloud docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/atlas-cli/seung.park/DOP-4264-frontend/index.html)
[docs-atlas-operator with atlas cli and operator ToC's embedded into cloud docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/atlas-operator/seung.park/DOP-4264-frontend/)
- The first initial front end bug was that we were not getting any sibling associated information (only checking if current project was used as …
=> DOP-4264: allow sibling associated products' ToC to be visible

src/components/Heading.js, src/components/Instruqt/InstruqtFrame.js, src/components/Instruqt/index.js, tests/unit/Instruqt.test.js, tests/unit/data/Instruqt.test.json
DOP-3846
[Server prod](https://www.mongodb.com/docs/manual/tutorial/getting-started/)
[Server staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/raymund.rodriguez/DOP-4284/tutorial/getting-started/index.html)
[Server staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/raymund.rodriguez/DOP-3846/tutorial/getting-started/index.html) - drawer
[Server staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/raymund.rodriguez/DOP-3846/reference/method/db.collection.find/index.html#try-it-yourself) - no drawer
* Main change is to remove the fullscreen functionality from the existing Instruqt component. This component was originally added as part of the original implementation of the Instruqt iframe, but is no longer needed …
=> DOP-3846: Remove instruqt fullscreen and feature flag

tests/unit/Presentation.test.js, tests/unit/__snapshots__/Presentation.test.js.snap
DOP-4302
[Flaky test](https://github.com/mongodb/snooty/actions/runs/7805040018/job/21288329645)
[Passing test](https://github.com/mongodb/snooty/actions/runs/7820424159)
It seems according to Jest's [test](https://jestjs.io/docs/api#testname-fn-timeout) method documentation, there is a way of making a test wait for the promise to resolve before letting the test complete. 
In our case, the solution is to return the promise from the `waitFor` async function from RTL.  Since this test now waits for the promise to resolve, we can remove the optional timeout.
=> :white_check_mark: DOP-4302 handles test with lazy loading a component

src/components/Header/index.js, src/components/RootProvider.js, src/components/SearchResults/SearchWrapper.js, src/components/SearchResults/index.js, tests/unit/SearchResults.test.js
DOP-4333
Open the network tab of the browser's dev tools, filter by "search-transport" and you should see requests for them, even on pages that aren't the search page. The search page is expected to have them.
[Server prod](https://www.mongodb.com/docs/manual/)
[Landing prod](https://www.mongodb.com/docs/) - homepage
[Landing prod](https://www.mongodb.com/docs/search?q=test) - search
[Landing staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/facets-enabled/master/landing/raymund.rodriguez/main/index.html?q=test) - search (facets enabled)
Open the network tab of the browser's dev tools, filter by "search-transport" and you should see requests for them only on the search pages, and no requests on non-search pages. Ideally, this PR does not change the search page's current …
=> DOP-4333: Limit search fetches to SearchResults component

src/components/DocumentBody.js, src/components/DocumentBodyPreview.js, src/components/Widgets/FeedbackWidget/useFeedbackData.js, src/components/Widgets/index.js, src/layouts/index.js, src/layouts/preview-layout.js, tests/unit/useFeedbackData.test.js
[DOP-4327](https://jira.mongodb.org/browse/DOP-4327)
This PR should not result in any meaningful changes, it is just removing the deprecated data structure `publishedBranches` which used to list out active and published branches/versions of a docs repo but has has long been deprecated in favor of repos_branches. The frontend still referenced it and passed it down as a prop to the feedback widget, but it was not actually being used.
[Staging link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/anabella.buckvar/DOP-4327/)
=> DOP-4327: Remove references to publishedBranches from frontend

src/components/Instruqt/LabDrawer.js
DOP-4355
[Server staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/raymund.rodriguez/main/tutorial/getting-started/index.html) - from the bug bash
[Server staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/raymund.rodriguez/DOP-4355/tutorial/getting-started/index.html)
* Main change was to wrap the lab handle to allow the grab area to extend past the actual handle div. Please let me know if the range is big enough or not!
* This PR also fixes the annoying interaction in Chrome with the iframe where resizing downwards would become wonky after the mouse starts to hover over the iframe. The change was to add a div overlay only when resizing so that the mouse would technically directly hover the div, and not the iframe itself. Unsure if …
=> DOP-4355: Extend grab area of lab drawer handle

src/components/DocumentBody.js, src/layouts/index.js, src/templates/landing.js, tests/unit/Presentation.test.js, tests/unit/__snapshots__/Presentation.test.js.snap
DOP-4188
[docs landing](https://www.mongodb.com/docs/)
[server docs](https://www.mongodb.com/docs/manual/)
Staging links should have no changes
[docs landing with lazy loaded footer](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/seung.park/DOP-4188/index.html)
[server docs with lazy loaded footer](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/v7.0/docs/seung.park/DOP-4188/index.html)
- Can see the code splitting happen in network tab under the filename `9c6d7990-737d6ad1b77adc9697a1.js`:
=> DOP-4188: lazy load unified footer

src/components/Select.js, src/components/Tabs/TabSelectors.js
[DOP-4393](https://jira.mongodb.org/browse/DOP-4393)
Clicking the language selector causes the screen to go blank.
example: https://www.mongodb.com/docs/atlas/atlas-vector-search/vector-search-stage/
[Staging Link with working Language Selector](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/anabella.buckvar/DOP-4393/manage-connections-aws-lambda/)
[Staging Link with working Deprecated Version Selector](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/anabella.buckvar/DOP-4393/legacy/index.html)
=> DOP-4393: fix broken language selector

src/components/ChatbotUi.js, src/components/ComponentFactoryLazy.js, src/components/DocumentBody.js, src/components/SuspenseHelper.js, src/components/Widgets/index.js
DOP-4406
[Cloud-docs](https://www.mongodb.com/docs/atlas/getting-started/)
[Landing](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/matt.meigs/DOP-4406-suspense/index.html)
[Cloud-docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/matt.meigs/DOP-4406-suspense/index.html)
In the current prod site, you can see the react minified error #419 which is here. 
This happens because of SSR hydration differences when using `React.Suspense` and Gatsby. There are a couple [open issues](https://github.com/gatsbyjs/gatsby/issues/36678) with Gatsby for this (even one with our friend Grayson), but this PR introduces a very simple fix to allow the SSR to compile the static html with the fallback and allow stable …
=> DOP-4406: Fixed React minified error in Suspense

src/components/Image.js
DOP-4408
[server docs on main branch](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/c077494d33ab88ab38e05f862cb0a3e8e5dbb9fe/v7.0/docs/seung.park/main/index.html)
[server docs on branch](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/c077494d33ab88ab38e05f862cb0a3e8e5dbb9fe/v7.0/docs/seung.park/DOP-4408-follow-up/index.html)
- This is a follow up to the [previous PR ](https://github.com/mongodb/snooty/pull/1029) which provided gatsby image props without checking for lazy load. Gatsby image should be used for lazy loading images, and regular image DOM with a `srcset` property should be used for non lazy (hero image in example)
- - [X] This PR does not introduce …
=> DOP-4408: skip gatsby image props if not lazy loaded

src/components/DocumentBody.js, src/components/Footer.js, src/components/SEO.js, src/utils/locale.js, tests/unit/Head.test.js, tests/unit/__snapshots__/Head.test.js.snap, tests/unit/__snapshots__/Presentation.test.js.snap, tests/unit/utils/__snapshots__/locale.test.js.snap, tests/unit/utils/locale.test.js
DOP-4398
[Server docs on prod](https://www.mongodb.com/docs/manual)
[Server docs on pre-prod](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/manual/)
[Server docs on main](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/raymund.rodriguez/main/index.html) - Note that the footer at the bottom has access to many languages
[Server docs staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/raymund.rodriguez/DOP-4398/index.html)
Alternate links for different languages have been introduced. Note that these currently use the static `siteUrl` config value to ensure that the base URL is defined at build time. This does mean that when built in staging links or pre-prod, the links will always point to the main https://mongodb.com site. Since …
=> DOP-4398: Add hreflang links to every page

src/components/Footer.js, tests/unit/Presentation.test.js
DOP-4419
[Server prod](https://www.mongodb.com/docs/manual/) - no language/locale selector
[Server staging on main branch](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/raymund.rodriguez/main/index.html) - language/locale selector should be visible
[Server staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/raymund.rodriguez/DOP-4419/index.html) - language/locale selector should be visible
* Logic that was gated by the `GATSBY_HIDE_UNIFIED_FOOTER_LOCALE` env variable has been removed in favor of showing the locale selector by default, regardless of the env's value from the Autobuilder.
* In case of emergency, a rollback of behavior will require reverting this commit and then redeploying all docs properties.
* Removal of the feature flag from …
=> DOP-4419: Remove feature flag to hide footer language selector

src/utils/locale.js, src/utils/url-utils.js, tests/unit/VersionDropdown.test.js, tests/unit/utils/__snapshots__/locale.test.js.snap, tests/unit/utils/locale.test.js
DOP-4453
[Server prod](https://www.mongodb.com/docs/manual/)
[Server staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/raymund.rodriguez/DOP-4453/index.html)
* The main problem can be summarized in the ticket itself.
* It's kind of difficult to get accurate testing done through a staging link. I'll make sure to test deploy some stuff in pre-production to verify changes. The main goal is to make sure current behavior of the version dropdown doesn't break, while new behavior on localized pages work.
=> DOP-4453: Include locale when using version selector

src/components/ChatbotUi.js, src/components/Widgets/ChatbotWidget/ChatbotFab.js
Re-do of https://github.com/mongodb/snooty/pull/1036 (CI failing on that one because I don't have creds on my fork)
- Adds a new suggested prompt to the AI chatbot
- Moves the list of suggested prompts into an exported object called `defaultSuggestedPrompts`
- Uses `defaultSuggestedPrompts` for both versions of the chatbot instead of different lists
[EAI-280: Add register for atlas as a suggested prompt](https://jira.mongodb.org/browse/EAI-280)
_I don't have a staging env - would appreciate if someone could stage or send me setup info_
=> EAI-280: Add register for atlas as a suggested prompt

src/components/Header/index.js, src/components/Sidenav/Sidenav.js, src/templates/landing.js
DOP-4443
Currently, while the chatbot is visible in production, in other environments the `GATSBY_SHOW_CHATBOT` environment variable needs to be true for the chatbot to show up. This PR removes the need for that!
[Cloud docs staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/maya/DOP-4443/index.html)
[Docs landing staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/maya/DOP-4443/)
This is a tiny, tiny issue but I noticed that when the chatbot is shown, there's a larger, somewhat more awkward (in my opinion) gap under the "View All Products" drop down in the Sidenav (no-chatbot staging link [here](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/maya/main/)). I'm wondering if that's something that should be …
=> DOP-4443: Remove GATSBY_SHOW_CHATBOT feature flag from the frontend

src/components/SEO.js, src/utils/locale.js, src/utils/url-utils.js, tests/unit/Head.test.js, tests/unit/__snapshots__/Head.test.js.snap, tests/unit/utils/locale.test.js
DOP-4457
[Server prod](https://www.mongodb.com/docs/manual/)
[Server staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/raymund.rodriguez/DOP-4457/index.html) - mostly to spot check that things (the version dropdown, hreflang links, and footer language selector) aren't broken. Unfortunately, this will need to be tested in production due to Smartling's production-only logic.
The situation is that Smartling overrides some frontend logic on their end to allow the frontend to properly link to other docs pages within the same locale. We purposely have logic that localizes URLs ourselves, so that we can link to them (for example: the language selector at the footer). This works fine on the English docs, but on the translated docs, Smartling's overridden localized slugs …
=> DOP-4457: Strip away locale code from slugs before localizing them

package-lock.json, package.json, tests/unit/__snapshots__/SearchResults.test.js.snap
DOP-4470
[Prod search page](https://www.mongodb.com/ko-kr/docs/search/) - typing "유" results in its individual characters being used as input "ㅇㅠ"
[Staging search page](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/raymund.rodriguez/main/search/index.html) - on the `main` branch, to confirm that this isn't only happening in prod
[Staging search page](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/raymund.rodriguez/DOP-4470/search/index.html) - typing "유" results in "유"
* The fix was to just bump the `@leafygreen-ui/search-input` package to its latest version. Couldn't figure out why this fixed it, but I'm assuming there was just some sort of incompatibility in our version.
* To test locally, you may need to add Korean as a language on your …
=> DOP-4470: Bump LG search-input version to fix localized input

src/components/Footer.js, src/utils/locale.js
DOP-4449
[English Server prod](https://www.mongodb.com/docs/manual/)
[Korean server prod](https://www.mongodb.com/ko-kr/docs/manual/)
[Simplified Chinese server prod](https://www.mongodb.com/zh-cn/docs/manual/)
[Portuguese server prod](https://www.mongodb.com/pt-br/docs/manual/)
[Regular staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/raymund.rodriguez/DOP-4449/index.html) - expected to be English by default
[English staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/docs/raymund/manual/index.html)
[Korean staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/ko-kr/docs/raymund/manual/index.html)
[Simplified Chinese staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/zh-cn/docs/raymund/manual/index.html)
[Portuguese …
=> DOP-4449: Add locale to footer

src/components/Widgets/FeedbackWidget/FeedbackCard.js, src/components/Widgets/FeedbackWidget/FeedbackForm.js, src/components/Widgets/FeedbackWidget/components/ScreenshotButton.js, src/components/Widgets/FeedbackWidget/views/CommentView.js, src/utils/dynamically-set-z-index.js
DOP-4363
https://www.mongodb.com/docs/manual/
[staging commit](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/260c33fea31807930b73a0375bded1e908a79879/master/docs/caesarbell/DOP-4363/index.html)
This PR, fixes the "Submit Feedback with Screenshot" bug, by dynamically setting the z-index on the widget container. It also provides a utility for dynamically setting and resetting a z-index based on the selector given.
**Screenshots**
**Stored Screenshot**
https://docs-feedback-screenshots.s3.us-east-2.amazonaws.com/screenshot-65f9c1141ea69e0248784367.png
=> :bug: DOP-4363 fixes bug for submitting a feedback with a screenshot

src/components/Widgets/FeedbackWidget/context.js, tests/unit/Presentation.test.js
DOP-4502
[Atlas Prod](https://www.mongodb.com/docs/atlas/)
[Atlas Staged Commit](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/7ae5e68f3c92834abd53aeabf67abdead93af0a6/master/cloud-docs/caesarbell/DOP-4502/index.html)
The change here provides a solution to reduce the INP score, which originally was no bueno. It achieves this by introducing transitions from React's useTransition. Transitions in React allow the state to be updated without blocking the UI. For more information, check out the docs for [useTransition](https://react.dev/reference/react/useTransition#). 
**screenshots if you are into that kind of stuff**
Before transitions
After transitions
**It works still*
- - …
=> DOP-4502 turns the set functions in initializeFeedback into transitions

src/components/InternalPageNav.js, tests/unit/__snapshots__/InternalPageNav.test.js.snap
DOP-4524
[server docs page showing next page, but linking to prev page](https://www.mongodb.com/docs/manual/core/timeseries/timeseries-limitations/)
[staged server docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/v7.0/docs/seung.park/DOP-4524/core/timeseries/timeseries-limitations/index.html)
Bug originated from [this change](https://github.com/mongodb/snooty/pull/1049/files#diff-6a4d349ee7d923a3ad2abf378f68b402e44b8bd6f8ba7f77ff9e0b7ccfc0bbc5R56-R61) while fixing link styling.
=> DOP-4524: use nextslug for link

src/hooks/use-canonical-url.js
DOP-4514
[Customize Cluster Storage](https://www.mongodb.com/docs/atlas/customize-storage/)
[Staged Commit](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/795b0c49fad7fe1754f35c17d2dea1fa72f691f9/master/cloud-docs/caesarbell/DOP-4514/index.html)
This PR does the following; 
-  Uses `normalizePath` as a catch-all for double slashes within the canonical URL.
=> :bug: DOP-4514 using normalizePath as a catch-all for double slashes

src/components/Card/CardGroup.js, src/components/Card/index.js, tests/unit/__snapshots__/Card.test.js.snap, tests/unit/__snapshots__/CardGroup.test.js.snap, tests/unit/__snapshots__/CardRef.test.js.snap
DOP-4543
[Drivers prod](https://www.mongodb.com/docs/drivers/)
[Landing prod](https://www.mongodb.com/docs/)
[Drivers staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4510/drivers/raymund.rodriguez/DOP-4543/index.html)
[Mocked programming language landing page](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4510/drivers/raymund.rodriguez/DOP-4543/php-libraries/index.html)
[Landing staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/raymund.rodriguez/DOP-4543/index.html)
* The programming language landing pages will be using cards in the same format/shape as the cards of the drivers homepage. However, the margins that come with the card group for the drivers homepage are coupled with the `:type: drivers` option.
* Solution: …
=> DOP-4543: Generalize card styles for programming language landing pages

src/components/Widgets/FeedbackWidget/handleScreenshot.js
DOP-4471
Some images were not being captured in screenshots. 
This took quite a bit of investigation and experimentation. I did not really find this issue out on the web, but after taking the time to compare which images did and didn't carry over. The fix was to remove the attribute srcset just for the screenshots.
=> imgs in screenshot bugfix

src/components/Figure/Lightbox.js, src/theme/docsTheme.js, tests/unit/useStickyTopValues.test.js
DOP-4567
[original slack message of k8s docs shows figure with distorted image 1](https://preview-mongodbjuliamongo.gatsbyjs.io/docs-k8s-operator/om-ha/tutorial/om-diagram-multi-cluster/)
[example 2 from k8s docs](https://preview-mongodbjuliamongo.gatsbyjs.io/docs-k8s-operator/om-ha/tutorial/om-nw-lb-mesh-multi-cluster/#diagram-example-1--external-load-balancer)
[atlas example of lighthouse figure](https://www.mongodb.com/docs/atlas/atlas-search/create-index/)
[k8s docs example 1 with staged changes](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/om-ha/docs-k8s-operator/seung.park/DOP-4567/tutorial/om-diagram-multi-cluster/index.html)
[staged example 2 from k8s docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/om-ha/docs-k8s-operator/seung.park/DOP-4567/tutorial/om-nw- …
=> DOP-4567: remove fixed height for image in lightbox

.desktop-lighthouserc.js, .github/constants/lighthouse-urls.js, .github/workflows/lighthouse.yml, .mobile-lighthouserc.js, lighthouserc.js
DOP-4505
[Docs Lighthouse Server](https://docs-lighthouse-server.docs.prod.corp.mongodb.com/app/projects/docs-lighthouse-server/dashboard)
Now, we will have both desktop and mobile scores. These can be seen by switching the url field. I decided not to add a query param to indicate the mobile scores just so that we would continue to have a continuous look-back history of the scores! If we would rather have the obvious "?mobile" on the url strings and don't care about linking the past runs with the future runs, we can do that too.
=> DOP-4505: Lighthouse Server scores for desktop and mobile

src/components/Link.js, src/utils/validate-element-attributes.js, tests/unit/utils/validate-element-attributes.test.js
DOP-4572
[Current Behavior](https://www.mongodb.com/docs/manual/query-api/)
[New Behavior](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/7e656a70bc3127a7327a0223343def3e99e3af38/master/docs/caesarbell/DOP-4572/query-api/index.html)
This PR fixes the **Unused objects/props are included in reference links** issue by providing a validation filter for props that will become attached to an HTML element, in this case, it filters out the invalid props before being spread to GatsbyLink or LGLink which in turn passes those props into an anchor tag i.e. `<a></a>`
- [Reach Router Link API](https://reach.tech/router/api/Link)
- [Gatsby Link API](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/)
- [Global attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Gl …
=> :bug: DOP-4572 Unused objects/props are included in reference links

package-lock.json, package.json
DOP-4587
[docs-landing](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/maya/DOP-4587/index.html)
[cloud-docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/maya/DOP-4587/index.html)
[docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/v7.0/docs/maya/DOP-4587/)
=> DOP-4587: Bump consistent-nav package to 2.0.7

src/components/Breadcrumbs/IndividualBreadcrumb.js, src/utils/get-complete-breadcrumb-data.js, tests/unit/__snapshots__/Breadcrumbs.test.js.snap
=> Ensure crumb titles are strings, and fix truncated tooltip baseFontSize

src/components/Breadcrumbs/IndividualBreadcrumb.js, tests/unit/__snapshots__/BreadcrumbContainer.test.js.snap, tests/unit/__snapshots__/Breadcrumbs.test.js.snap
Fix Safari bug. Older Safari versions do not support text-wrap: nowrap.
This adds white-space: nowrap to allow all Browsers to keep breadcrumbs on one line.
Picture of fixed in safari:
=> bugfix. add whitespace:nowrap for safari

src/components/InternalPageNav.js, tests/unit/__snapshots__/InternalPageNav.test.js.snap
DOP-4609
[sample page showing hydration styling](https://www.mongodb.com/docs/atlas/create-connect-deployments/)
[page loads with prestyled component](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/seung.park/DOP-4609/create-connect-deployments/index.html)
Really small change to use styled from @emotion rather than `styled-components`
=> DOP-4609: use emotion styled vs styled components

src/components/OpenAPI/index.js, src/components/Sidenav/DocsHomeButton.js, src/components/Sidenav/Sidenav.js
DOP-4569
[open api preview page on main branch](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/seung.park/main/openapi/preview/index.html)
[open api preview page on branch](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/seung.park/DOP-4569/openapi/preview/index.html)
[regression check - atlas docs with changes](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/seung.park/DOP-4569/index.html)
- Minor conversion from using `components/link` to using `LG/link` in `DocsHomeButton` due to errors of `"useLocation()" may be used only in the context of a <Router> component` within a callback of Redoc component
- - [X] …
=> DOP-4569 - include home button in sidenav of openapi preview

gatsby-ssr.js, src/utils/locale.js
DOP-4598
N/A
[Japanese Stagged Commit Site](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/ja-jp/master/docs/caesarbell/DOP-4598/introduction/index.html)
I left a comment [here](https://jira.mongodb.org/browse/DOP-4598?focusedCommentId=6331814&focusedId=6331814&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-6331814) asking about adding Japanese to the language selector. Currently, we only provide the following languages to our users when visiting the docs pages.
- English
- Simplified Chinese
- Korean
- Portuguese
=> DOP-4598 adds support to use Noto Sans for Japanese Docs Sites

src/templates/drivers-index.js
Minor fix to address this extra padding that was bothering me while inspecting different breadcrumbs
[QA drivers homepage](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/drivers/)
[drivers homepage (seems like this hasn't been deployed since latest snooty release)](https://www.mongodb.com/docs/drivers/)<img width="541" alt="image" src="https://github.com/mongodb/snooty/assets/13054820/f2b8b617-ffa7-4217-8329-50b1d720a267">
[staged drivers homepage ](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/drivers/seung.park/drivers-index-remove-padding/index.html)
=> Breadcrumbs follow - removing extra padding on drivers index page - verify this is wanted

src/components/Tabs/tab-context.js
DOP-4707
[Connect via drivers page in cloud docs](https://www.mongodb.com/docs/atlas/driver-connection/)
You can also look at the selector specific to a code block [here](https://www.mongodb.com/docs/atlas/driver-connection/#driver-examples).
[Same page as above](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/maya/DOP-4707/driver-connection/index.html)
[Code block](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/maya/DOP-4707/driver-connection/index.html#driver-examples)
To test, check that when you select "Rust (Async)" or "Rust (Sync)" on the language flipper there is a logo that appears next to the title, and it is the same as the Rust icon in the drivers icons.
- - [ ] This PR introduces changes that should be reflected in the …
=> DOP-4707: Icon mapping for tab selectors missing keys for rust-async and rust-sync

gatsby-ssr.js, src/components/DocumentBody.js, src/context/dark-mode-context.js
DOP-4671
[staged site that should read from your system settings](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/drivers/seung.park/DOP-4671/index.html)
- Local testing requires env variable `GATSBY_ENABLE_DARK_MODE=true` to have all the effects take place (from [this PR](https://github.com/mongodb/snooty/pull/1099))
- To test system detection, change your system appearance to light/dark and staged site should respect your system settings
- Added to the previous PR's logic of saving to the local storage - the HTML document will also be added a classname for `dark-theme` (or `light-theme`) via a pre render script that reads the local storage. This allows for our own styling ie. page background before …
=> DOP-4671 - detect system for light/dark modes

gatsby-browser.js, gatsby-ssr.js, package-lock.json, package.json, src/components/RootProvider.js, src/context/dark-mode-context.js
DOP-4667
[sample drivers page for dark mode](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/drivers/seung.park/DOP-4667/index.html)
- Dark mode setting is stored in local storage - Caveat is that this can only be read by the clients' browser local storage which means users will see an initial load of default (non dark) before switching to dark mode. 
- Includes changes from DOP-4669 (feature flag) and DOP-4671 (detecting system dark mode)
- Test locally with env variable `GATSBY_ENABLE_DARK_MODE=true`
=> DOP-4667 - create dark mode context

src/utils/locale.js
DOP-4603
[Atlas docs prod](https://mongodb.com/docs/atlas)
[With feature flag ON](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/raymund.rodriguez/DOP-4603/index.html) - should include Japanese in the locale selector and hreflang links
[With feature flag OFF](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/flag-false/master/cloud-docs/raymund.rodriguez/DOP-4603/index.html) - should be the same as prod
[Japanese site example](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/ja-jp/master/cloud-docs/raymund.rodriguez/DOP-4603/index.html) - to validate that the locale selector shows the Japanese language as the selected locale.
* Conditionally adds Japanese to the list of languages through a feature flag. This should automatically handle adding …
=> DOP-4603: Add Japanese locale behind feature flag

src/components/Sidenav/IA.js, src/components/Sidenav/Sidenav.js, src/components/Sidenav/TOCNode.js, tests/unit/__snapshots__/IA.test.js.snap
DOP-4598
https://www.mongodb.com/docs/search/
https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/no-ia-header/landing/matt.meigs/DOP-4698-hide-ia-header/search/index.html
Consolidates the two pages that need to hide the Docs Home. Includes Search page now.
=> DOP-4698: Hide IA header on Search

package-lock.json, package.json, src/components/Footer.js, src/components/Header/index.js, src/utils/locale.js
DOP-4715
[Cloud docs landing page](https://www.mongodb.com/docs/atlas/)
[English cloud-docs landing page (has Japanese language available in dropdown)](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/maya/DOP-4715-b/index.html)
["Japanese" cloud-docs landing page (only navigable from English page)](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/ja-jp/master/cloud-docs/maya/DOP-4715-b/index.html)
["Portuguese" cloud-docs landing page](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/pt-br/master/cloud-docs/maya/DOP-4715-b/index.html)
["Korean" cloud-docs landing page](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/ko-kr/master/cloud-docs/maya/DOP-4715-b/index.html)
["Simplified Chinese" cloud-docs landing …
=> DOP-4715: Upgrade consistent nav to "v2.1.0"

package-lock.json, package.json, src/components/Footer.js, src/components/Header/index.js, src/utils/locale.js
Reverts mongodb/snooty#1108 - consistent nav back to 2.0.7
Removes language selector from the header
**Staging Links**
[Drivers](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4623/drivers/maya/revert-1108-DOP-4715-b/)
[Docs-landing](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/maya/revert-1108-DOP-4715-b/)
=> Revert "DOP-4715: Upgrade consistent nav to "v2.1.0""

src/components/Figure/Lightbox.js, src/components/Figure/index.js, src/components/Image.js, tests/unit/__snapshots__/Figure.test.js.snap, tests/unit/__snapshots__/Lightbox.test.js.snap
DOP-4643
[previous staged link showed borders around hero image in dark mode](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/seung.park/DOP-4643/index.html)
[docs landing](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/seung.park/DOP-4643-followup/index.html)
[language pages from docs landing](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/seung.park/DOP-4643-followup/languages/cpp/)
[atlas docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/seung.park/DOP-4643-followup/index.html)
[atlas docs with image example](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/seung.park/DOP-4643-followup/atlas-search/create-index/index.html#node-status)
[regression …
=> DOP-4643: strict rules for image borders

src/components/Card/index.js, src/components/CommunityPillLink.js, tests/unit/__snapshots__/Card.test.js.snap
DOP-4662
[Python Landing](https://www.mongodb.com/docs/languages/python/)
[Docs Landing](https://www.mongodb.com/docs/)
[Staged: Python Landing](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/caesarbell/DOP-4662/languages/python/index.html)
[Staged: Docs Landing](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/forked/dark-icons/landing/caesarbell/DOP-4662/index.html) (built from a forked repo)
- For this PR, I modified the community pill component to be reusable and swapped out the Tag component to use the new community pill component.
=> :sparkles: DOP-4662 adds community pill to cards for when using tags

src/components/ChatbotUi.js
[Prod landing](https://www.mongodb.com/docs/)
[Prev landing staging link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/dark-mode-disabled/master/landing/caesarbell/DOP-4624/index.html) - Dark mode **disabled**
[Prev landing staging link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/dark-mode-enabled/master/landing/caesarbell/DOP-4624/index.html) - Dark mode **enabled**
[Landing](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/feature-off/master/landing/raymund.rodriguez/fix-chatbot-landing/index.html) - Dark mode **disabled**; background behind Chatbot should stay white.
[Landing](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/feature-on/master/landing/raymund.rodriguez/fix-chatbot-landing/index.html) - Dark mode **enabled**; background behind …
=> Fix ChatbotUI background inheritance

package-lock.json, package.json, src/components/Tabs/index.js
DOP-4761
[Tab behavior on homepage](https://www.mongodb.com/docs/atlas/)
[Tabs in inner content page](https://www.mongodb.com/docs/atlas/access-tracking/)
[Tabs on a landing page](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/seung.park/DOP-4761/index.html)
[Tabs in inner content page](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/seung.park/DOP-4761/access-tracking/index.html)
- Styling and user interaction should see no change
- Tabbed content is visible in the HTML produced (as well as the page HTML). You can verify this by going to the [S3 bucket](https://us-east-2.console.aws.amazon.com/s3/object/docs-mongodb-org-stg?region=us-east-2&bucketType=general&prefix=master/cloud-docs/seung.park/DOP-4761/index.html) and downloading the …
=> DOP-4761: update LG/tabs to v12 to render content in HTML

src/components/Footnote/index.js, tests/unit/__snapshots__/Footnote.test.js.snap
DOP-4635
[Previous Staged: Docs Manual](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/caesarbell/DOP-4635/tutorial/install-mongodb-enterprise-on-red-hat-tarball/index.html#footnote-oracle-linux)
[New Staged without Style Prop: Docs Manual](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/caesarbell/DOP-4635-ClassName/tutorial/install-mongodb-enterprise-on-red-hat-tarball/index.html#platform-support)
- Same styles applied, but now using only `classnames` rather than using the style props. 
=> :art: DOP-4635 using static css approach

src/components/Card/index.js, src/templates/landing.js, tests/unit/__snapshots__/Card.test.js.snap, tests/unit/__snapshots__/CardRef.test.js.snap
DOP-4760
[Docs Landing](https://www.mongodb.com/docs/)
[Staged Docs Landing](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/caesarbell/DOP-4760/index.html)
- Sets the `letter-spacing` to `0` from `0.5px` for `<p>` and `<a>` tags on the landing template.
=> :art: DOP-4760 sets the letter-spacing for p and a tags within the landing template

package.json
Snooty version is 0.16.20 but package.json is 0.16.17
Fixing before next release.
=> Fix package.json to be current version

package-lock.json, package.json, src/components/Tabs/index.js
Reverts mongodb/snooty#1141
During release, a bug was found with the Language Selectors. 
The icons for Python, Ruby, and Kotlin had color/spacing issues within the selector.
The upgrade in LG Tabs seems to have caused this either directly or in combination with other recent changes.
=> Revert "DOP-4761: update LG/tabs to v12 to render content in HTML"

src/components/DocumentBody.js, src/components/DocumentBodyPreview.js, src/components/Widgets/FeedbackWidget/context.js, src/components/Widgets/index.js
DOP-4784
[Cloud-docs](https://www.mongodb.com/docs/atlas/getting-started/)
[404](https://www.mongodb.com/docs/404/)
[Landing with no widgets](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/)
[Cloud-docs with both Feedback and Chatbot](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/atlas/)
[404 with Chatbot](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/404/)
Chatbot now present on 404 page.
Extras: 
- Removed unused `hideHeader`/`hideFeedbackHeader `.
- Cleaned up conditionals of when to hide widgets
=> DOP-4784: Chatbot on 404

src/components/InternalPageNav.js, tests/unit/__snapshots__/InternalPageNav.test.js.snap
DOP-4791
[MongoDB Atlas](https://www.mongodb.com/docs/atlas/getting-started/)
[Staged: MongoDB Atlas](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4791/cloud-docs/caesarbell/DOP-4791/getting-started/index.html)
[Staged MongoDB Manual](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4791/docs/caesarbell/DOP-4791/core/databases-and-collections/index.html)
- Introduces the new next/prev component which is used at the bottom of the docs page to navigate to the next section.
- Proposes the use of [conditional class names](https://emotion.sh/docs/@emotion/css#cx), which I believe allows us to use static styling. It is a proposal, so please oppose if there are any opinions. I battled with myself if I should use dynamic styles aka returning the css`` via a function, but …
=> :sparkles: DOP-4791 introduces new next/prev button

gatsby-ssr.js
DOP-4789
[Atlas docs (English)](https://mongodb.com/docs/atlas/)
[Atlas docs (Chinese)](https://mongodb.com/zh-cn/docs/atlas/)
[Atlas docs (Portuguese)](https://mongodb.com/pt-br/docs/atlas/)
[Atlas docs (Korean)](https://mongodb.com/ko-kr/docs/atlas/)
[English staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/raymund.rodriguez/DOP-4789/index.html)
[Chinese staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/zh-cn/master/cloud-docs/raymund.rodriguez/DOP-4789/index.html)
[Portuguese staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/pt-br/master/cloud-docs/raymund.rodriguez/DOP-4789/index.html)
[Korean staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/ko-kr/master/cloud-docs/raymund.rodriguez/DOP-4789/index.html)
* …
=> DOP-4789: Re-enable redirects based on browser language

src/components/ActionBar/ActionBar.js, src/components/ChatbotUi.js, src/components/Header/index.js, src/components/Widgets/index.js, src/layouts/index.js, src/templates/NotFound.js
DOP-4784 (b)
[Cloud-docs](https://www.mongodb.com/docs/atlas/getting-started/)
[404](https://www.mongodb.com/docs/404/)
[Landing](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/matt.meigs/DOP-4784-fix-404-chatbot/index.html)
[Cloud-docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/matt.meigs/DOP-4784-fix-404-chatbot/index.html)
[404](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/add-title/docs-404/matt.meigs/DOP-4784-fix-404-chatbot/index.html)
This is a re-do of DOP-4784.
I had previously added the Chatbot FAB to the 404 page. What is actually needed is the ChatbotUI bar.
This PR removes the FAB from the 404. It also adds the ChatbotUi component to the 404 page.
In doing so, there …
=> DOP-4784-B: Remove chatbot FAB from 404, use ChatbotUi bar

package-lock.json, package.json, tests/unit/__snapshots__/Admonition.test.js.snap
I think we're waiting on design for this but I got bored so I upgraded Callout
[Note](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/v7.0/docs/maya/upgrade-callout/aggregation/index.html#aggregation-pipelines)
[Tip](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/v7.0/docs/maya/upgrade-callout/sharding/index.html#shard-key-strategy)
[Important](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/v7.0/docs/maya/upgrade-callout/reference/method/db.collection.find/index.html)
[Warning](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/v7.0/docs/maya/upgrade-callout/reference/method/KeyVault.rewrapManyDataKey/index.html) (scroll down)
[Example](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/v7.0/docs/maya/upgrade-callout/core/security-ldap/index.html#managin …
=> Upgrade Callout/Admonition so we can use Dark Mode

src/components/DocumentBody.js, tests/unit/Head.test.js, tests/unit/data/CompleteEOLPageContext.json, tests/unit/data/HeadPageContext.test.json
DOP-4835
[Atlas prod](https://www.mongodb.com/docs/atlas/atlas-data-processing/) - `noindex` does not appear in a meta tag
[Atlas staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/raymund.rodriguez/DOP-4835/atlas-data-processing/index.html) - `noindex` appears in a meta tag.
* Re-introduces page data into Gatsby Head. This was missing due to page context no longer having page data.
* Throws an error if page AST is missing from Gatsby Head again. This should hopefully stop the build with an error to emphasize that this is not expected.
* Adjusts existing data sources for tests for the `Head` component to split between page context and data. This should better mock how data is being passed into the component.
- - [ ] This PR introduces changes that should be …
=> DOP-4835: Fix meta robots not appearing due to missing page data

src/components/Banner/SiteBanner.js, tests/unit/SiteBanner.test.js, tests/unit/__snapshots__/SiteBanner.test.js.snap
DOP-4824
[Atlas](https://www.mongodb.com/docs/atlas/getting-started/)
[Atlas](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/matt.meigs/DOP-4824-mobile-banner/index.html) (no real difference other than showing that there are breakpoints)
- the tablet image is the same as the mobile image for now, will speak to design to see if they want to add one for Vector Search
Adds a tablet breakpoint for SiteBanner
[Link to Atlas App Services Values](https://services.cloud.mongodb.com/groups/5bad1d3d96e82129f16c5df3/apps/5d41ef5e2de84772fc7c2de2/values)
Conversation with design (Amelia) confirmed these sized breakpoints.
- - [x] This PR does not introduce changes that …
=> DOP-4824: SiteBanner tablet breakpoint

src/components/Collapsible/index.js
[DOP-4691](https://jira.mongodb.org/browse/DOP-4691?focusedCommentId=6547966&focusedId=6547966&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-6547966)
[Previous PR](https://github.com/mongodb/snooty/pull/1171)
[Staging link with Segment action added](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4690/docs-test-spark/seung.park/DOP-4691-tracking/dop-4690/index.html) (clicking on the collapsible icon should still work as designed)
Segment does not work on above staging link, but when testing this locally:
```
{
"userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
"url": "http://localhost:9000/DOP-4690/docs-test-spark/seung.park/DOP-4691-tracking/dop-4690/", …
```
=> DOP-4691: add tracking to collapsible

src/components/Banner/SiteBanner.js, src/components/Header/index.js, src/hooks/useStickyTopValues.js, tests/unit/__snapshots__/SiteBanner.test.js.snap, tests/unit/useStickyTopValues.test.js
DOP-4825
[Docs landing](https://www.mongodb.com/docs/)
[Manual](https://www.mongodb.com/docs/manual/)
[Cloud-docs](https://www.mongodb.com/docs/atlas/getting-started/)
[Docs landing](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/maya/DOP-4825/index.html) (behavior should be unchanged)
[Manual](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/v7.0/docs/maya/DOP-4825/index.html)
[Cloud docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/maya/DOP-4825/index.html)
[Example without banner](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/no-banner/v7.0/docs/maya/DOP-4825/index.html)
[Example with dark mode/action bar enabled](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/dark-mode-enable/master/cloud-docs/maya/DOP-4825 …
=> DOP-4825: Hide Sitewide CTA banners on Scroll

src/components/ActionBar/ActionBar.js, src/components/Banner/SiteBanner.js, src/components/Sidenav/Sidenav.js, src/components/Widgets/FeedbackWidget/FeedbackCard.js, src/components/Widgets/index.js, src/hooks/useStickyTopValues.js, src/theme/docsTheme.js, tests/unit/__snapshots__/SiteBanner.test.js.snap, tests/unit/useStickyTopValues.test.js
DOP-4797
[Current behavior on recent staging link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/v7.0/docs/maya/upgrade-callout/index.html)
In mobile views, above staging link shows Action Bar taking precedence over ConsistentNav and Docs Mobile Nav Menu. Also the feedback widget in mobile view is hidden behind the new Action Bar.
[Staging link with Action Bar enabled](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/HEAD/cloud-docs/seung.park/DOP-4797/index.html)
[Regression check with existing Nav Bar only](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/e30f3798c918e2ceea07829aed9dd431b02df7f7/HEAD/cloud-docs/seung.park/DOP-4797/atlas-search/atlas-search-overview/index.html)
- May have some conflicts with @mayaraman19 's [PR for non-sticky …
=> DOP-4797: address action bar's z-index in relation to nav and sidebar

src/components/CommunityPillLink.js, tests/unit/__snapshots__/Card.test.js.snap, tests/unit/__snapshots__/CommunityPillLink.test.js.snap
DOP-4584
https://www.mongodb.com/docs/languages/python/#frameworks
[Staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/dark-mode-enable/master/landing/maya/DOP-4584/languages/python/index.html#frameworks)
[Using tags in Card](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/dark-mode-enable/DOP-4641/landing/maya/DOP-4584/index.html) - to ensure no changes/extra margins here
[Only one community built link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/dark-mode-enable/DOP-4641/landing/maya/DOP-4584/languages/python/index.html#frameworks)
=> DOP-4584: Add bottom margin for last "community built" link in list

src/components/Code/Code.js, src/components/Tabs/TabSelectors.js, src/components/Tabs/index.js, src/components/Tabs/tab-context.js
DOP-4813
[Visiting this page in incognito leads to hydration error in console](https://www.mongodb.com/docs/manual/core/indexes/create-index/)
- Addresses the problem of hydration errors by having consistent initial values in server and client side (either nodejs in language dropdown, or first option for each set of tabs)
[Visiting this page in incognito, and selecting C++, ](https://www.mongodb.com/docs/manual/core/transactions/) then in a new tab [visiting this page results in no tab selection (since no C++)](https://www.mongodb.com/docs/manual/core/indexes/create-index/)
- Addresses problem of preserving a non-existent tab by checking for its existence before setting it as the current tab
[No hydration errors. First init in nodejs, and then update to local storage (if it …
=> DOP-4813: address React warnings for hydration for tabs

src/components/Breadcrumbs/BreadcrumbContainer.js, src/components/Breadcrumbs/IndividualBreadcrumb.js, tests/unit/__snapshots__/BreadcrumbContainer.test.js.snap, tests/unit/__snapshots__/Breadcrumbs.test.js.snap
DOP-4875
[Atlas](https://www.mongodb.com/docs/atlas/)
[Atlas](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/matt.meigs/DOP-4875-dark-mode-breadcrumbs/index.html)
This PR updates the color of breadcrumbs in dark mode.
[Figma](https://www.figma.com/design/7cR6eWtFvKTnJIPL8ZsTaB/Content-Template-Projects?node-id=2560-7626&t=bnSXpL7I3dsa6zw2-4)
=> DOP-4875: Dark Mode - Breadcrumbs

src/components/Widgets/ChatbotWidget/ChatbotFab.js, src/components/Widgets/FeedbackWidget/FeedbackButton.js
DOP-4874
[Atlas](https://www.mongodb.com/docs/atlas/)
[Landing](https://www.mongodb.com/docs/legacy/)
[Atlas](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/matt.meigs/DOP-4874-dark-mode-fabs/index.html)
[Landing](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/matt.meigs/DOP-4874-dark-mode-fabs/legacy/index.html)
This allows the chatbot to ingest the darkmode state. It also matches the Feedback FAB to the dark mode styles.
[FIgma](https://www.figma.com/design/7cR6eWtFvKTnJIPL8ZsTaB/Content-Template-Projects?node-id=2560-7626&t=bnSXpL7I3dsa6zw2-4)
And offline discussions for some colors with Amelia in design.
I've let the chatbot team know that the sparkle AI icon is the wrong color and they're working with LG on it.
- - [ ] This PR …
=> DOP-4874: Dark Mode: FABs

src/components/Target.js, tests/unit/__snapshots__/Target.test.js.snap
DOP-4839
This is a real quick fix (follow up to https://github.com/mongodb/snooty/pull/1163) to remove custom buffer space and use default for Target components
Less prominent now with the banner being hidden, but for consistency sake.
[Heading Permalink](https://www.mongodb.com/docs/v7.3/reference/write-concern/#write-concern-specification)
[Example of Target using Permalink](https://www.mongodb.com/docs/v7.3/reference/write-concern/#mongodb-writeconcern-writeconcern.-majority-)
[Heading Permalink](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/8f161c3c0788eed8c351e2f19031c33149385317/v7.3/docs/seung.park/DOP-4839/reference/write-concern/index.html#write-concern-specification)
[Example of Target using Permalink](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/8f161c3c0788 …
=> DOP-4839: use same buffer for target links

src/components/Procedure/index.js, src/components/Tabs/index.js, src/styles/global-dark-mode.css
DOP-4846
This was a lot smaller than I anticipated due to work done in [DOP-4843](https://github.com/mongodb/snooty/pull/1183)
Ensures tab buttons are initialized in light/dark mode (reducing flicker)
[This is an example of tabs flickering - open with dark mode already enabled](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4767/docs-test-spark/seung.park/DOP-4767-css-vars/index.html). You can see the tabs change from light -> dark mode
[Staging link shows Tab buttons initializing in preferred mode (light/dark both)](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4690/docs-test-spark/seung.park/DOP-4846/index.html)
- - [X] This PR does not introduce changes …
=> DOP-4846: initialize tabs in dark mode

src/components/Header/preview-header.js, src/styles/global-dark-mode.css, src/styles/mongodb-docs.css, tests/unit/__snapshots__/Admonition.test.js.snap
[Staging](https://preview-mongodbmmeigs.gatsbyjs.io/cloud-docs/test-again/)
In Gatsby Preview site, the Preview header had a white background but the text was taking in dark mode and also becoming light gray. 
Also, the nav was scrolling too far. And the banner was eating into the header because the preview header wasn't aware of it.
This does not introduce anything new to prod. It also is just taking logic over from the normal header to the preview header.
=> Fix Preview header styles and scroll

src/templates/document.js
DOP-4806
I tried adding a test, but this template is kind of tricky and requires an oodle-load of stuff to be mocked. I can try and get a test going if desired, however!!
* https://www.mongodb.com/docs/atlas/security-serverless-private-endpoint/
=> DOP-4806: Correct Document template data ingestion to fix noprevnext

src/components/Collapsible/index.js, tests/unit/Collapsible.test.js, tests/utils/mock-location.js
DOP-4869
Pretty straightforward implementation to open the collapsible if there is a hash in the url containing the ID of the collapsible heading
[Previous staging link with hash id in URL](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4690/docs-test-spark/seung.park/DOP-4691/dop-4690/index.html#this-collapsible-has-no-subheader)
[Collapsible component's hash id in URL](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4690/docs-test-spark/seung.park/DOP-4869/dop-4690/index.html#this-collapsible-has-no-subheader)
=> DOP-4869: set collapsible open if hash found in url

src/components/Header/preview-header.js, src/styles/global-dark-mode.css, src/styles/mongodb-docs.css, tests/unit/__snapshots__/Admonition.test.js.snap
[Staging](https://preview-mongodbmmeigs.gatsbyjs.io/cloud-docs/test-again/)
This PR was merged into `gatsby-cloud-latest` already but not into `main`.
Corrects content's main body bg color and makes the preview header "dark mode" to help viewing.
=> Fix preview header

src/components/ActionBar/ActionBar.js, src/components/DocumentBody.js, src/components/DocumentBodyPreview.js, src/components/Header/index.js, src/components/Sidenav/DocsHomeButton.js, src/components/Widgets/FeedbackWidget/FeedbackButton.js, src/components/Widgets/FeedbackWidget/FeedbackCard.js, src/components/Widgets/FeedbackWidget/FeedbackContainer.js, src/components/Widgets/FeedbackWidget/FeedbackForm.js, src/components/Widgets/FeedbackWidget/components/ScreenshotButton.js, src/components/Widgets/FeedbackWidget/components/StarRating.js, src/components/Widgets/FeedbackWidget/constants.js, src/components/Widgets/FeedbackWidget/context.js, src/components/Widgets/FeedbackWidget/index.js, src/components/Widgets/FeedbackWidget/views/CommentView.js, src/components/Widgets/FeedbackWidget/views/SubmittedView.js, src/hooks/use-canonical-url.js, src/layouts/index.js, src/layouts/preview-layout.js, src/styles/global-dark-mode.css, tests/testSetup.js, tests/unit/Chatbot.test.js, tests/unit/FeedbackWidget.test.js, tests/unit/Presentation.test.js, tests/utils/mock-location.js
DOP-4879
[Current prod feedback uses FAB for feedback](https://www.mongodb.com/docs/atlas/)
[Staging link with feedback enabled in action bar](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/seung.park/DOP-4879/index.html)
[Gatsby preview build test](https://preview-mongodbseungpark.gatsbyjs.io/drivers/DOP-4817/)
- This PR updates the Feedback Module to be in the Action Bar (for Desktop)
- Feedback behavior should not change as existing, but there are small design changes that are noticeable 
- caption to indicate rating
- update padding and sizing of feedback card
- update copy based on selected feedback rating
- - [X] This PR does not introduce changes that …
=> DOP-4879: use feedback widget in action bar (desktop)

src/components/Card/index.js, src/styles/global-dark-mode.css, tests/unit/__snapshots__/Card.test.js.snap, tests/unit/__snapshots__/CardGroup.test.js.snap, tests/unit/__snapshots__/CardRef.test.js.snap
DOP-4844
[Tools & Connectors](https://www.mongodb.com/docs/tools-and-connectors/)
[Atlas](https://www.mongodb.com/docs/atlas/api)
[Landing](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4743-dark-hero/landing/matt.meigs/DOP-4844-init-cards/index.html)
[Tools & Connectors](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4743-dark-hero/landing/matt.meigs/DOP-4844-init-cards/tools-and-connectors/index.html)
[Atlas](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/matt.meigs/DOP-4844-init-cards/api/index.html)
This PR simply makes Cards initialize in Dark Mode (if user preferred) without light mode flash. The icons are sometimes (usually) still in light mode. That will be taken care of in [this …
=> DOP-4844: Init Cards in dark mode

src/components/Sidenav/Sidenav.js, src/styles/global-dark-mode.css
DOP-4956
Initializes sidenav items for dark mode on hover as well.
To test, reload the page and hover over sidenav items.
[Dark Mode Docs pre-this change](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/dark-mode-enable/DOP-4683/docs/maya/main/index.html)
[Docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/dark-mode-enable/DOP-4683/docs/maya/DOP-4956/index.html)
=> DOP-4956: Hovering over sidenav results in light mode while loading

src/templates/product-landing.js
Don't have a good link, but the title and the introduction paragraph on the hero image were turning light gray in dark mode and could not be seen on top of this light hero image.
https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4942-dark-icons-realm-master/realm/matt.meigs/realm-dark-mode-hero-text/index.html
Color now stays black on realm landing page in desktop size.
=> No ticket: Realm landing page hero text fix (dark mode)

src/components/Contents/ContentsListItem.js, src/components/Link.js
DOP-4881
[Manage Connections with AWS Lambda](https://www.mongodb.com/docs/atlas/manage-connections-aws-lambda/)
[Configure Cluster Authentication](https://www.mongodb.com/docs/atlas/security/config-db-auth/)
[Manage Connections with AWS Lambda](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/dark-mode-enable/DOP-4683/cloud-docs/maya/DOP-4881/manage-connections-aws-lambda/index.html)
[Configure Cluster Authentication](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/dark-mode-enable/DOP-4683/cloud-docs/maya/DOP-4881/security/config-db-auth/index.html) (just to make sure underline still looks okay)
- - [X] This PR does not introduce changes that should be reflected in …
=> DOP-4881: Z-index issue with left nav and language dropdown

src/components/ListTable.js, tests/unit/__snapshots__/ListTable.test.js.snap
DOP-4893
Table has weird shift in spacing in dark mode in cells with nested content because leafygreen paragraph styles overwrite table styles.
[Global clusters on main branch](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/dark-mode-enable/DOP-4683/cloud-docs/maya/main/global-clusters/index.html#global-write-zones-and-zone-mapping)
[Unsupported commands on main branch](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/dark-mode-enable/DOP-4683/cloud-docs/maya/main/unsupported-commands/index.html)
[Table testing on main branch](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/dark-mode-enable/DOP-4683/cloud-docs/maya/main/tables/index.html)
[Global clusters](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/dark-mode-enable/DOP-4683/cloud-docs/maya/DOP-4893/glob …
=> DOP-4893: List Table bugs in dark mode

src/templates/product-landing.js
After fixing the header text color on the Realm landing page, I realized that there are many uses of the `product-landing` template within the Realm repo. This means that it was changing all the text colors in those pages rather than just the one with the light color hero on it. 
This PR makes this change more specific than just being in the Realm repo and product-landing template. It requires a hard-coded fileid to identify which page has the light color hero image.
In the future, if we have the time maybe we add an option to the image directive in the parser to specify which hero images are light colored? This is not a wide-spread problem, but I also hate the hard-coded solution long-term. 
[Old staging with issue (check any of the sdk pages to see the …
=> No ticket: Realm product-landing template headers - more specific

gatsby-ssr.js, src/components/ActionBar/ActionBar.js, src/components/OpenAPI/index.js, src/components/RootProvider.js, src/components/Sidenav/DocsHomeButton.js, src/components/Sidenav/ProductsList.js, src/components/Sidenav/Sidenav.js, src/context/dark-mode-context.js, src/layouts/index.js, src/layouts/preview-layout.js
DOP-4955
[Preview Page](https://www.mongodb.com/docs/openapi/preview/)
[Preview Page](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4873-dark-icons/landing/matt.meigs/DOP-4955-dark-openapi-preview/openapi/preview/index.html)
This PR disables Dark Mode on the OpenAPI preview page. It does it in such a way that it does not affect localStorage or the user's saved preference at all so that when navigating between the preview page and any other docs page, the user's dark mode preference will not be affected by the switch. 
Also, I have cleaned up some unused props.
=> DOP-4955: OpenAPI Preview page - disable Dark Mode

src/components/SearchResults/MobileFilters.js
DOP-4978
Current dark mode mobile search filters page:
[Staging Link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4873-dark-icons/landing/matt.meigs/DOP-4978-search-mobile-dark/search/index.html)
To see: use mobile viewport and click "Refine your search"
Mobile Search filters "page" background and button text were not ingesting dark mode.
=> DOP-4978: mobile search filters page in dark mode

src/components/ChatbotUi.js
No ticket. This bug has been seen during release process
[stage (qa) landing docs shows transparent background in the chatbot sticky header](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/)
[staged change for homepage](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/seung.park/v0.17.4-fix-homepage/index.html) - used `master` branch of docs landing and v0.17.1 of parser
=> [no ticket] use white background for landing

src/components/List/ListItem.js, src/components/Procedure/Step.js, tests/unit/__snapshots__/BlockQuote.test.js.snap, tests/unit/__snapshots__/List.test.js.snap, tests/unit/__snapshots__/Procedure.test.js.snap, tests/unit/__snapshots__/Step.test.js.snap
DOP-4989
Updated list markers to reflect dark mode (by matching with the text color). Also updated some spacing errors with step titles (see the H5s under "Create an Atlas Search Index" in the linked page).
[docs-qa Atlas Search Queries](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/atlas/atlas-search/tutorial/embedded-documents-tutorial/)
[docs-qa Connect to your cluster](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/atlas/tutorial/connect-to-your-cluster/)
[Atlas Search Queries](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/dark-mode-enable/DOP-4683/cloud-docs/maya/DOP-4989/atlas-search/tutorial/embedded-documents-tutorial/index.html)
[Connect to your cluster](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/dark-mode-enable/DOP-4683/c …
=> DOP-4989: List item markers do not conform to dark mode colors

src/components/Widgets/index.js
DOP-4990
Removing feedback FAB from docs outlined in ticket
[atlas data lake](https://www.mongodb.com/docs/datalake/)
[atlas app services](https://www.mongodb.com/docs/atlas/app-services/)
[atlas data lake](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/datalake/seung.park/DOP-4990/index.html)
[realm](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/realm/seung.park/DOP-4990/index.html)
[atlas app services](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/atlas-app-services/seung.park/DOP-4990/index.html)
[regression check for cloud docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/seung.park/DOP-4990/index.html)
- Incoming separate PR for removing feedback button from action bar, targeting feature branch
- - [ ] …
=> DOP-4990: remove fab from depreacted projects

src/components/DocumentBody.js, src/components/StructuredData/DocsLandingSD.js
DOP-4920
[Google Rich Results test](https://search.google.com/test/rich-results/result/r%2Fsitelinks-searchbox?id=O19qyQs_m8tHGiL3zp-ZTg) - No errors found; new SearchAction is present.
[schema.org validator](https://validator.schema.org/#url=https%3A%2F%2Fdocs-mongodb-org-stg.s3.us-east-2.amazonaws.com%2Fmaster%2Flanding%2Fraymund.rodriguez%2FDOP-4920-search-action%2Findex.html) - No errors found
[Landing](https://mongodb.com/docs)
[Atlas](https://www.mongodb.com/docs/atlas/)
[Landing](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/raymund.rodriguez/DOP-4920-search-action/index.html)
[Atlas](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/raymund.rodriguez/DOP-4920-search-action/index.html) - control; no `SearchAction` structured data …
=> DOP-4920: Add SearchAction structured data

src/components/Widgets/FeedbackWidget/FeedbackButton.js
DOP-4616
[Staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4873-dark-icons/landing/matt.meigs/DOP-4994-feedback-btn/index.html)
Wraps text to keep in line when in other languages.
=> DOP-4994: Feedback Button horizontal text in all languages

src/components/ActionBar/SearchInput.js, src/components/ActionBar/SearchMenu.js
DOP-5002
[Old cloud-docs](https://mongodbcom-cdn.website.staging.corp.mongodb.com/pt-br/docs-qa/atlas/)
- be on VPN!
[New docs-landing](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/) (check other languages)
- make sure to be on VPN!
We need to only have chatbot functionality on English sites.
Went with the simplest solution. 
Disallowed chatbot search option and disallowed chatbot hotkey when the locale is anything other than `en-us`.
=> Easiest solution: disallow option and hotkey in locale not en-us

src/hooks/useViewport.js
DOP-5000
Unfortunately I can't really replicate this behavior in local dev, but in preprd you see that `scrollY = undefined` on initial load which causes the bottom 3 links to not show up until you scroll. This PR sets it to 0 when it's being built so it is not undefined on initial load. Check out the `<div>` with id `docs-side-nav-container`. 
[Landing prod](https://www.mongodb.com/docs/)
[Landing preprd](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/)
[Landing Staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4683/landing/maya/DOP-5000/index.html)
=> 0px if not browser

src/components/Header/index.js
DOP-4908
Note: this [has been done before](https://github.com/mongodb/snooty/pull/1204/files#diff-a89ac12c8ec97364db532676bd572c7e552dcb933901a3d3358fa0285fabe445R32), but got undone when addressing [merge conflicts on the feature branch](https://github.com/mongodb/snooty/commit/632c79eb22f83a04c16c32a956d63b0e9d3e0cee#diff-a89ac12c8ec97364db532676bd572c7e552dcb933901a3d3358fa0285fabe445)
[current QA docs show search icon in top nav](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/atlas/)
[staged cloud docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/seung.park/remove-search-from-topnav/index.html)
- - [X] This PR does not introduce …
=> DOP-4908: remove search icon from top nav

src/components/ActionBar/SearchInput.js
Prod sites making requests to staging URL
We should be reading from site metadata
=> Universal Search fast follow - update env reading

src/components/Video/index.js, tests/unit/Video.test.js, tests/unit/__snapshots__/Video.test.js.snap
DOP-4918
[Related parser PR](https://github.com/mongodb/snooty-parser/pull/619)
[Example rST](https://github.com/rayangler/cloud-docs/commit/93ab9b1cc34c1a461e8266da44f07687acc49c49)
Examples of pages with videos. They're in the same order as the staging links below
* https://www.mongodb.com/docs/atlas/atlas-search/create-index/ - Video is under the "Atlas UI" language/tab
* https://www.mongodb.com/docs/atlas/atlas-search/manage-indexes/
* https://www.mongodb.com/docs/atlas/atlas-search/operators-and-collectors/
* https://www.mongodb.com/docs/atlas/atlas-search/searching/
* [Video with all options](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/test-video-object/cloud-docs/raymund.rodriguez/DOP-4918-video-object/atlas-search/create-index/index.html) - Video is under the "Atlas …
=> DOP-4918: Add VideoObject structured data to Video component

src/utils/head-scripts/redirect-based-on-lang.js, src/utils/locale.js, tests/unit/__snapshots__/Head.test.js.snap, tests/unit/__snapshots__/Presentation.test.js.snap, tests/unit/utils/__snapshots__/locale.test.js.snap
DOP-4601
* [Japanese](https://www.mongodb.com/ja-jp/docs/atlas/)
* [English](https://www.mongodb.com/docs/atlas/)
* [Chinese](https://www.mongodb.com/zh-cn/docs/atlas/)
* [Korean](https://www.mongodb.com/ko-kr/docs/atlas/)
* [Portuguese](https://www.mongodb.com/pt-br/docs/atlas/)
All links were built without the `GATSBY_FEATURE_SHOW_HIDDEN_LOCALES` feature flag, to mimic prod.
* [Japanese](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/ja-jp/sandbox/cloud-docs/raymund.rodriguez/DOP-4601-jp-live/index.html)
* [English](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/sandbox/cloud-docs/raymund.rodriguez/DOP-4601-jp-live/index.html)
* [Chinese](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/zh-cn/sandbox/cloud-docs/raymund.rodriguez/DOP-4601-jp-live/index.html)
* …
=> DOP-4601: Unhide Japanese locale

src/components/Banner/SiteBanner.js, tests/unit/__snapshots__/SiteBanner.test.js.snap
DOP-5032
[Current prod with banner](https://www.mongodb.com/docs/)
[Staging link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4873-dark-icons/landing/matt.meigs/DOP-5032-banner-width/index.html)
NOTE: to see the issue in prod, you must have your user settings to ALWAYS show scrollbar.
Simply needed to be `100%` vs `100vw`.
=> DOP-5032: Site Banner width

src/components/ComponentFactory.js, src/components/Roles/Gold.js
DOP-4947
N/A
[Staging link using parser branch with new role](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/gold-role/mongodb-shell/matt.meigs/DOP-4947-gold-role/run-commands/index.html)
Creates a Gold role component. Also, adds the correct dark mode color for the Red role component color.
=> DOP-4947: Add Gold role component

package-lock.json, package.json, tests/unit/__snapshots__/Presentation.test.js.snap
DOP-4902
[Prod](https://www.mongodb.com/docs/)
[Staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4873-dark-icons/landing/matt.meigs/DOP-4902-update-flora/index.html)
Needed to update Flora to take advantage of inline style change from [this PR](https://github.com/10gen/flora/pull/313/files).
=> DOP-4902: Update flora to v1.14.2

src/components/Breadcrumbs/BreadcrumbContainer.js, src/components/Code/Code.js, src/components/Code/CodeIO.js, src/components/Code/Output.js, src/components/StructuredData/DocsLandingSD.js, src/components/Video/index.js, src/utils/get-language.js, src/utils/structured-data.js, tests/unit/CodeIO.test.js, tests/unit/__snapshots__/Code.test.js.snap, tests/unit/__snapshots__/CodeIO.test.js.snap, tests/unit/__snapshots__/Collapsible.test.js.snap, tests/unit/__snapshots__/LiteralInclude.test.js.snap, tests/unit/__snapshots__/ReleaseSpecification.test.js.snap, tests/unit/utils/__snapshots__/structured-data.test.js.snap, tests/unit/utils/structured-data.test.js
DOP-4916
* [Different language examples](https://www.mongodb.com/docs/atlas/driver-connection/)
* [IO code block examples](https://www.mongodb.com/docs/atlas/atlas-search/compound/)
* [No language example](https://www.mongodb.com/docs/atlas/billing/)
Google doesn't care about `SoftwareSourceCode`, so they're not present in Rich Results.
* [Different language examples](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/sandbox/cloud-docs/raymund.rodriguez/DOP-4916-software-source-code/driver-connection/index.html)
* [Validator](https://validator.schema.org/#url=https%3A%2F%2Fdocs-mongodb-org-stg.s3.us-east-2.amazonaws.com%2Fsandbox%2Fcloud-docs%2Fraymund.rodriguez%2FDOP-4916-software-source-code%2Fdriver-connection%2Findex.html)
* [IO code block …
=> DOP-4916: Implement SoftwareSourceCode structured data

src/components/Footnote/index.js, tests/unit/__snapshots__/Footnote.test.js.snap
DOP-5016
Updating font size for both text and links to be 13px; see [Slack thread here](https://mongodb.slack.com/archives/C04L4BVFEM9/p1728051297579989)
[Example 1](https://www.mongodb.com/docs/atlas/reference/microsoft-azure/#footnote-azure-disk-docs)
[Example 2](https://www.mongodb.com/docs/atlas/unsupported-commands/#ref-1-id4)
[Example 1](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4973-example/cloud-docs/maya/DOP-5016/reference/microsoft-azure/index.html#footnote-azure-disk-docs)
[Example 2](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4973-example/cloud-docs/maya/DOP-5016/unsupported-commands/index.html#ref-1-id4)
- - [X] This PR does not …
=> DOP-5016: Links in footnote can have inconsistent font size

src/components/Roles/Abbr.js, src/theme/docsTheme.js
DOP-5048
* [Atlas prod](https://mongodb.com/docs/atlas/atlas-vector-search/vector-search-overview/index.html#atlas-vector-search-queries)
* [Atlas staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/sandbox/cloud-docs/raymund.rodriguez/DOP-5048-inline-def-visibility/atlas-vector-search/vector-search-overview/index.html#atlas-vector-search-queries)
* Just a simple z-index fix. Created a new `popovers` field for z-indexes in our themes file. I chose a high number that could potentially serve as our maximum, if needed, but happy to tone it down if it seems too much.
=> DOP-5048: Ensure inline definition popover is visible

src/components/ActionBar/DarkModeDropdown.js
DOP-5038
[docs landing without tracking](https://www.mongodb.com/docs/)
[staging link with user tracking](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/seung.park/DOP-5038/index.html)
- To test, you can visit the live debugger for [segment actions](https://app.segment.com/mongodb/sources/docs/debugger) and visit the above staging link to test the analytics:
=> DOP-5038: add segment tracking to dark mode controls

src/components/Collapsible/index.js, tests/unit/Collapsible.test.js, tests/unit/data/CollapsibleExpanded.test.json
DOP-5059
No current collapsibles in prod, I don't thiiiiink?
[Staging with collapsibles in old build](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4690/docs-test-spark/seung.park/DOP-4691/dop-4690/index.html)
[New staging with three collapsibles](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4873-dark-icons/landing/matt.meigs/DOP-5059-expanded/launch-manage/index.html) (first and third are expanded by default)
Partner PR in parser [here](https://github.com/mongodb/snooty-parser/pull/626)
=> DOP-5059: Default expanded Collapsibles

src/components/Code/Code.js, src/components/Code/Output.js, src/components/DocumentBody.js, src/components/Procedure/index.js, src/components/StructuredData/BreadcrumbSchema.js, src/components/StructuredData/DocsLandingSD.js, src/components/Video/index.js, src/utils/structured-data.js, tests/unit/__snapshots__/Code.test.js.snap, tests/unit/__snapshots__/CodeIO.test.js.snap, tests/unit/__snapshots__/Collapsible.test.js.snap, tests/unit/__snapshots__/LiteralInclude.test.js.snap, tests/unit/__snapshots__/ReleaseSpecification.test.js.snap
DOP-5095
[Atlas prod](https://www.mongodb.com/docs/atlas/)
[Atlas staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/sandbox/cloud-docs/raymund.rodriguez/DOP-5095-sd-class-name/index.html)
* No behavior change is expected. This should solely be an additive change recommended by the Smartling team, in case we need to target them in the future for whatever reason.
=> DOP-5095: Add structured_data class name to script tags

src/components/Procedure/index.js, tests/unit/__snapshots__/Procedure.test.js.snap
DOP-5083
[Current bug](https://www.mongodb.com/docs/atlas/tutorial/create-serverless-instance/#select-the-serverless-type) (be in dark mode, click Atlas UI tab, scroll down til text is unreadable)
[Staged Atlas](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-5020-dark-mode-images/cloud-docs/matt.meigs/DOP-5083-dark-text/tutorial/create-serverless-instance/index.html)
darkMode was not being passed to component.
I reconfigured to use our newer approach anyway! No light mode flash.
=> DOP-5083: Bugfix. Procedure text color in Dark Mode

src/components/ActionBar/SearchMenu.js
DOP-5014
[Current behavior on docs shows that you cannot choose chatbot twice in a row](https://www.mongodb.com/docs/)
https://github.com/user-attachments/assets/d5fe32fb-deb9-4ab5-8ccc-969d93e86ad9
[Staging link with minimal changes](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/seung.park/DOP-5014/index.html)
Above link works with multiple times of selecting the chatbot option
- This was due not triggering the useEffect watching for changes on selectedOption, because selectedOption was persisted as the same option. This small PR resets the selectedOption when any option is selected, to enable the trigger.
- - [X] This PR does not introduce changes that …
=> DOP-5014: allow chatbot option consecutively

build.sh
Update `build.sh` to parser version v0.18.4
=> Update build.sh parser version

src/components/DeprecatedVersionSelector.js, tests/unit/DeprecatedVersionSelector.test.js
DOP-5053
[Current](https://www.mongodb.com/docs/legacy/)
[Staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4873-dark-icons/landing/matt.meigs/DOP-5053-legacy-fetch/legacy/index.html)
Fixes error in checking for empty fetch result. Fixes and adds a test.
=> DOP-5053: Fix client-side fetch refresh - legacy page

plugins/utils/products.js
DOP-4810
I just staged this branch... but clicking on any of the products would take you to something like `www.mongodb.com.website/atlas`
[Preprd landing](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/)
Might be staged back by someone else to how it used to be (buggy)
Pictures of hovered urls
Went for the simplest approach. Modifying `baseUrl` util would have had wider ranging consequences.
=> DOP-4810: All Products dropdown docs-qa links

src/components/DocumentBody.js, src/components/Tabs/tab-context.js
DOP-4945
[Connect to your cluster](https://www.mongodb.com/docs/atlas/tutorial/connect-to-your-cluster/)
[Autocomplete](https://www.mongodb.com/docs/atlas/atlas-search/autocomplete/)
[Connect to your cluster](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/matt.meigs/DOP-4945-chosen-tab/tutorial/connect-to-your-cluster/index.html) (default tab is now python)
[Autocomplete](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/matt.meigs/DOP-4945-chosen-tab/atlas-search/autocomplete/index.html) (default tab is now go)
Adds the ability to specify the default tab in drivers tabs.
The flow will be as follows: use localStorage activeTab if available, use a default tab if available (NEW), use nodejs if available, otherwise use the first tab.
Clear …
=> DOP-4945: Default tab for drivers tabs

src/components/Banner/Banner.js, tests/unit/__snapshots__/Banner.test.js.snap
DOP-5161
[current behavior](https://www.mongodb.com/docs/atlas/app-services/)
[staging behavior](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/atlas-app-services/bianca.laube/DOP-5161/index.html)
* simple fix, there was just an extra `}`
=> DOP-5161: Banner color is wrong

src/components/ComponentFactory.js, src/components/Link.js, src/components/Roles/LinkNewTab.js
DOP-4562
Current links all use same tab
[Staged](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/collapse-expanded/landing/matt.meigs/DOP-4562-new-tab/launch-manage/index.html) (the **Atlas Playground** link)
From [this rst](https://github.com/mongodb/docs-landing/blob/ec04305be221313abece37a4fd14f96a093cb240/source/launch-manage.txt#L47)
New role to open links in new tab.
=> DOP-4562: new LinkNewTab role

src/components/ActionBar/styles.js
DOP-5194
https://www.mongodb.com/docs/
[staging link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/seung.park/DOP-5194/index.html)
- To reproduce the issue, check the current behavior link on a mobile phone (preferably iPhone to recreate the zoom), and open the search input. The same issue does not occur on the staging link
=> DOP-5194: update input font size for mobile

netlify/functions/fetch-url.js
DOP-5189
N/A - Function does not exist yet
https://deploy-preview-1310--docs-frontend-stg.netlify.app/.netlify/functions/fetch-url?url=https://raw.githubusercontent.com/10gen/docs-shared/main/dbx/encrypt-fields.rst
https://deploy-preview-1310--docs-frontend-stg.netlify.app/.netlify/functions/fetch-url?url=https://raw.githubusercontent.com/10gen/docs-shared/main/dbx/compatibility-table-legend.rst
https://deploy-preview-1310--docs-frontend-stg.netlify.app/.netlify/functions/fetch-url?url=https://raw.githubusercontent.com/10gen/docs-shared/main/dbx/lifecycle-schedule-callout.rst
* The function currently relies on the `url` query param to fetch the content from said URLs. The function is currently as minimal as possible and leverages basic cache headers.
* This function is intended to only be …
=> DOP-5189: Create Netlify function to proxy URL fetch

.gitignore, README.md, build.sh, netlify.toml
[DOP-5159](https://jira.mongodb.org/browse/DOP-5159): Specify Content Repo and Parser version for Frontend Netlify builds
Currently, the frontend only builds the master branch of docs-landing unless the build script itself is changed. 
[Current netlify.toml](https://github.com/mongodb/snooty/blob/main/netlify.toml)
[Current build script](https://github.com/mongodb/snooty/blob/main/build.sh)
[docs-frontend-stg build](https://app.netlify.com/sites/docs-frontend-stg/deploys/673e75a8626dc49e7ebdaec2)
[docs-frontend-dotcomstg build](https://app.netlify.com/sites/docs-frontend-dotcomstg/overview)
This PR updates the build script for Netlify builds, but will not have any effect on autobuilder builds. It allows for controlling the repo, repo branch, and parser version used for the Netlify build …
=> DOP-5159 Specify content repo and parser version in build script for Netlify Frontend Builds

src/components/Image.js
DOP-5142
[ReadWriteConcern photo for example](https://www.mongodb.com/docs/v8.0/reference/read-concern-majority/#example)
[ReadWriteConcern in staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-5106-redirects/docs/matt.meigs/DOP-5142-img-corners/reference/read-concern-majority/index.html#example)
All dark mode images that were not hero images or on landing pages were being given a large border-radius style which could obscure some content. This removes that.
=> DOP-5142: Remove border radius one dark mode images

package-lock.json, package.json, src/styles/mongodb-docs.css
DOP-5181
[Landing](https://mongodb.com/docs/)
[Landing](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/collapse-expanded/landing/matt.meigs/DOP-5181-chatbot/index.html)
Updated Chatbot. Need to be on VPN to test on staging.
=> DOP-5181: Upgrade Chatbot to 0.10.2

src/components/ListTable.js, tests/unit/__snapshots__/ListTable.test.js.snap
DOP-5124
[test page for tables on main branch](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/sandbox/cloud-docs/seung.park/main/test-tables/index.html) - includes all of Atlas docs as well as the test page (sourced [here](https://github.com/rayangler/cloud-docs/blob/sandbox/source/test-tables.txt))
[test page for tables on branch](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-5124-test-tables/cloud-docs/seung.park/DOP-5124/test-tables/index.html)
- This PR does not change the way tables are rendered, or how they should be used in ReST. This updates the logic for constructing table data on the front end, so that we can pass processed column/row data, enabling us to use farther features as [expanded content ](https://github.com/mongodb/leafygreen-ui/tree/main/packages …
=> DOP-5124: reconstruct table data using tanstack tables

src/components/Collapsible/index.js, src/components/Collapsible/styles.js, src/components/ComponentFactoryLazy.js, src/utils/head-scripts/offline-ui/collapsible.js, src/utils/head-scripts/offline-ui/index.js, tests/unit/__snapshots__/Collapsible.test.js.snap
DOP-5258
[Sample S3 file that has collapsibles enabled on offline page](https://us-east-2.console.aws.amazon.com/s3/object/docs-mongodb-org-stg?region=us-east-2&bucketType=general&prefix=DOP-5124-test-tables/cloud-docs/seung.park/DOP-5258/tutorial/prometheus-integration/index.html) (append #mongo-metrics.json to URL or search for `mongo-metrics.json`
[Regression check for online collapsibles](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/offline-docs-false/DOP-5124-test-tables/cloud-docs/seung.park/DOP-5258/tutorial/prometheus-integration/index.html)
- Made a minor change to allow videos to be covered by `OfflineNotAvailable` component.
- Minor improvement to add `aria-expanded` to collapsibles and their button
- - [ ] This PR introduces changes that should be reflected in the …
=> DOP-5258: make collapsibles interactive offline

src/components/Collapsible/index.js, src/components/Collapsible/styles.js, src/components/MethodSelector/MethodOptionContent.js, src/components/MethodSelector/MethodSelector.js, src/utils/head-scripts/offline-ui/collapsible.js, src/utils/head-scripts/offline-ui/index.js, src/utils/head-scripts/offline-ui/method-selector.js, tests/unit/__snapshots__/Collapsible.test.js.snap
DOP-5259
[S3 file to download and verify that method selector works offline](https://us-east-2.console.aws.amazon.com/s3/object/docs-mongodb-org-stg?region=us-east-2&bucketType=general&prefix=sandbox/cloud-docs/seung.park/DOP-5259/testing-method-selector/index.html)
[online docs without OFFLINE_DOCS env flag for regression check](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/offline-docs-false/sandbox/cloud-docs/seung.park/DOP-5259/testing-method-selector/index.html)
- The arrow indicator has been removed for offline method selectors as it needs some calculations based on selected index to get the position
- On this Page headings will be handled separately as the content values are hidden in a React context
- - [ ] This PR introduces changes that should be reflected in the …
=> DOP-5259: interactive method selector for offline docs

netlify.toml, src/components/Heading.js, src/components/Tabs/TabSelectors.js
DOP-5242
[Docs Altas Prerequisites](https://www.mongodb.com/docs/atlas/driver-connection/#prerequisites)
This PR fixes the issue of the tab selector not rendering in the mobile view.
=> DOP-5242 🐛  fixes the issue of the tab selector now rendering on mobile view

src/components/ListTable.js
DOP-5273
On the main branch, building a wrongly structured ListTable can produce an error in the build step for ListTables.
See [this build log](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=dotcom_queue&jobId=6764665504ba9f49246c5ea5) and search for `ListTable`. This resulted in the front end throwing an error at build time.
[An example of badly structured ListTable](https://github.com/mongodb/docs-pymongo/blob/960ea6688e47334a09d3a77a84b75a6512de37f0/source/includes/mongodb-compatibility-table-pymongo.rst?plain=1#L16-L27)). This row has too many columns (12) even though the table only has 9 columns.
[Staging link with test RST with too many items in row
](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/HEAD/pymongo/seung.park/DOP-5273/compatibility/index.html …
=> DOP-5273: add console warning for column out of index and continue

src/components/Literal.js, tests/unit/__snapshots__/DefinitionList.test.js.snap, tests/unit/__snapshots__/Field.test.js.snap, tests/unit/__snapshots__/FieldList.test.js.snap, tests/unit/__snapshots__/Line.test.js.snap, tests/unit/__snapshots__/Literal.test.js.snap, tests/unit/__snapshots__/Target.test.js.snap, tests/unit/__snapshots__/VersionModified.test.js.snap
DOP-5114
[Current](https://www.mongodb.com/docs/manual/reference/command/replSetGetStatus/#mongodb-data-replSetGetStatus.electionCandidateMetrics)
[Staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/matt.meigs/DOP-5114-literals-wrap/reference/command/replSetGetStatus/index.html)
Inline literals can be long and they will never wrap. They go straight off the page and don't scroll. Unreadable. 
This allows them to wrap.
=> DOP-5114: Force inline literals to wrap

src/utils/head-scripts/redirect-based-on-lang.js, src/utils/locale.js, tests/unit/utils/head-scripts/redirect-based-on-lang.test.js
DOP-5362
* [English prod](https://www.mongodb.com/docs/atlas/)
* [English staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/sandbox/cloud-docs/raymund.rodriguez/DOP-5362-query-lang/index.html)
* [Chinese staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/zh-cn/sandbox/cloud-docs/raymund.rodriguez/DOP-5362-query-lang/index.html)
The approach is to change the `location.pathname` instead of `location.href` so that we only need to modify the pathname, automatically keeping the search query strings and hashes the same.
To test (best done in incognito window. Otherwise, delete site's local storage):
1. Set your browser's primary language to Simplified Chinese. Make sure it's the top language (i.e. about English).
2. Add a query search query string and/or a hash to a …
=> DOP-5362: Fix missing search and hash from lang redirects

src/components/ListTable.js, tests/unit/__snapshots__/ListTable.test.js.snap
DOP-5342
[Related Osiris PR](https://github.com/10gen/osiris/pull/32)
[Test tables staging (main branch)](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/sandbox/cloud-docs/raymund.rodriguez/main/test-tables/index.html)
[Test tables staging page](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/sandbox/cloud-docs/raymund.rodriguez/DOP-5342-lone-table/test-tables/index.html) - should ideally look the same as the one on the main branch.
* Wraps cell content inside of a div so that all of its content are together when laid out. This allows us greater flexibility with layout styling of cell contents without needing to worry about exact structure.
* The main reason for this change was to help prevent awkward styling with elements passed in from Osiris. Seems like if there were …
=> DOP-5342: ListTable consolidates cell content inside of divs

src/components/Sidenav/TOCNode.js
DOP-5401
* [Java staging (main branch)](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/java/raymund.rodriguez/main/index.html)
* [Java staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/java/raymund.rodriguez/DOP-5401/index.html)
* [Offline build staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/offline-build/master/java/raymund.rodriguez/DOP-5401/index.html)
Tries to avoid drawers wrapping unnecessarily. I'm unsure what exactly about the `Link` component was causing the issue (other than differences in css 🤪)
=> DOP-5401: Fix drawer visual wrapping

netlify.toml, src/components/Code/Output.js, tests/unit/__snapshots__/CodeIO.test.js.snap
DOP-5411
This PR fixes the problem where we see the styling as plain text on offline docs. This can be seen on the offline docs, as well as pre-hydration on live production sites. This was due to a small `display: inline !important` styling done in code components that also mistakenly captured style elements
[This page shows a flash of styling text on top of the code output](https://www.mongodb.com/docs/languages/python/pymongo-driver/current/data-formats/custom-types/) - original page from issue description
[Another page where flash of styling text on page from atlas docs](https://www.mongodb.com/docs/atlas/atlas-search/aggregation-stages/search/#troubleshooting)
The problem can be seen on the offline doc [here](http://mongodb.com/docs/offline/pymongo-master.tar.gz) (navigate to the …
=> DOP-5411: hide style on code outputs

src/components/SEO.js, tests/unit/Head.test.js
DOP-5358
[Current Cloud-docs](https://www.mongodb.com/docs/atlas/)
[Cloud-docs Staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/matt.meigs/DOP-5358-title/index.html)
Sarah Lin asked us to append "- MongoDB Docs" to all page titles. I did not append it to the main landing page as it would then be "MongoDB Documentation - MongoDB Docs".
=> DOP-5358: Add "MongoDB Docs" to page titles

netlify.toml, src/components/Permalink.js, tests/unit/__snapshots__/Collapsible.test.js.snap, tests/unit/__snapshots__/Heading.test.js.snap, tests/unit/__snapshots__/Procedure.test.js.snap, tests/unit/__snapshots__/Section.test.js.snap, tests/unit/__snapshots__/Target.test.js.snap
DOP-5452
[Getting Started with the Atlas Architecture Center](https://www.mongodb.com/docs/atlas/architecture/current/getting-started/)
~~One approach is to reduce the padding from `0 10px` to `0 5px`, which seems like the simplest solution with the design team's approval, of course. We can also consider using flex styling on the header and inline-block or inline-flex on the anchor tag.~~
~~There is also a `max-content` method we can explore, but this will disrupt the current responsiveness, requiring us to introduce some media query breakpoints.~~
~~I am completely open to other options and approaches.~~
Setting `position: absolute` around the Permalink so it doesn't need to take up any extra whitespace.
- - [ ] This PR …
=> DOP-5452: fixes anchor tag wrapping for longer text headings.

src/utils/head-scripts/offline-ui/tabs-selectors.js
DOP-5408
See first comment in issue.
The [previous change to make tabs work in sync](https://github.com/mongodb/snooty/pull/1355/files#diff-b0b2d09e76bfa9dfc8673f4b44f7525c7e1832cbfd7fa01933fddfa47fb89b0eL214) had a side effect of removing DOM attributes used by tabs selectors. This PR updates so that both offline modules look for the same DOM attribute
Download this [offline doc](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/offline/cloud-docs-master.tar.gz). The page for /driver-connection which [correlates to this page in prod](https://www.mongodb.com/docs/atlas/driver-connection/), does not have the tabs selector working 
[Sample offline page upload to S3](https://us-east-2.console.aws.amazon.com/s3/object/docs-mongodb-org-stg?region=us-east-2&bucketType=general&prefi …
=> DOP-5408 followup: make sure offline tabs selectors work

src/components/AssociatedVersionSelector/index.js, src/components/Sidenav/Sidenav.js, src/components/VersionDropdown/index.js, src/context/toc-context.js, src/context/version-context.js
DOP-5504
* https://www.mongodb.com/docs/bi-connector/current/
* https://www.mongodb.com/docs/atlas/architecture/current/
* https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/bi-connector/raymund.rodriguez/DOP-5504-version-dropdown/index.html
* https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/main/atlas-architecture/raymund.rodriguez/DOP-5504-version-dropdown/index.html
* Bonus: Also renamed a variable to accommodate confusion around embedded versioning variables.
=> DOP-5504: Remove version dropdown filter for active versions

src/utils/head-scripts/offline-ui/tabs.js
DOP-5510
Can test by [downloading this Offline Doc](http://mongodb.com/docs/offline/cloud-docs-master.tar.gz), and navigating to the configure-alerts page.
Can also find this in this S3 link: https://us-east-2.console.aws.amazon.com/s3/object/docs-mongodb-org-dotcomprd?region=us-east-2&bucketType=general&prefix=docs/offline/cloud-docs-master.tar.gz
Offline pages of a snooty build have been uploaded to [this S3 path](https://us-east-2.console.aws.amazon.com/s3/buckets/docs-mongodb-org-stg?prefix=master%2Fcloud-docs%2Fseung.park%2FDOP-5510%2F&region=us-east-2&bucketType=general&tab=objects)
To replicate above behavior, see [this file](https://us-east-2.console.aws.amazon.com/s3/object/docs-mongodb-org-stg?region=us-east-2&bucketType=general&prefix=master/cloud-docs/seung.park/DOP-5510/config …
=> DOP-5510: handle nested tabs

src/components/DeprecatedVersionSelector.js, src/components/Heading.js, src/styles/button.ts
DOP-5474
* [Server docs](https://www.mongodb.com/docs/manual/reference/method/db.collection.find/)
* [Csharp](https://www.mongodb.com/docs/drivers/csharp/current/fundamentals/crud/write-operations/insert/)
* [Legacy](https://www.mongodb.com/docs/legacy/)
* [Server docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/raymund.rodriguez/DOP-5474-lab-button/reference/method/db.collection.find/index.html)
* [Csharp](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/csharp/raymund.rodriguez/DOP-5474-lab-button/fundamentals/crud/write-operations/insert/index.html)
* [Legacy](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/raymund.rodriguez/DOP-5474-lab-button/legacy/index.html) (control for disabled button change)
* The solution was to …
=> DOP-5474: Move lab button outside of h1 element

netlify.toml, src/components/Procedure/Step.js, tests/unit/__snapshots__/Procedure.test.js.snap, tests/unit/__snapshots__/Step.test.js.snap
DOP-5468
[Production](https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-windows/)
The tabs are now visible and scrollable horizontally, which also prevents the content from being cutoff. 
The fix solution: 
Allow the content to shrink properly in a flex container. 
Adding the following
```css
flex: 1; 
min-width: 0;
```
does two things. First, it allows the child to grow and shrink to fill the available space in the flex container, and second tells the browser it's okay for this flex item to shrink below its content's intrinsic width.
- - [x] This PR does not introduce changes that should be reflected in the …
=> DOP-5468 🐛  Fixes Tabs in procedures are not fully visible in mobile view issue.

gatsby-ssr.js
DOP-5568
* [Writers' staging](https://deploy-preview-11568--docs-mongodb-internal.netlify.app) (redirects based on browser lang)
* [Server docs prod](https://www.mongodb.com/docs/manual/) (redirects based on browser lang)
* [With prd SNOOTY_ENV](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/raymund.rodriguez/DOP-5568-redirects/index.html) (mimics the env for Netlify deploy previews. Ideally, this shouldn't redirect based on browser lang)
* [With dotcomprd SNOOTY_ENV](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/dotcomprd/master/docs/raymund.rodriguez/DOP-5568-redirects/index.html) (ideally, this continue to redirect based on browser lang)
**To test:**
1. Set browser's primary language to Korean, Simplified Chinese, Portuguese, or Japanese. Ensure it's the …
=> DOP-5568: Prevent browser lang redirects on writers staging

src/components/OfflineDownloadModal/DownloadModal.tsx, tests/unit/__snapshots__/OfflineDownloadModal.test.tsx.snap
DOP-5539
[Current behavior cuts off the download modal (and makes version selector hard to see) when filtering projects:
](https://www.mongodb.com/docs/atlas/)![image](https://github.com/user-attachments/assets/01b59727-4c54-4912-8137-8a8cf30e4aaa)
See Staging link below
- Min height kicks in when using the filter and there are only few projects to download:
=> DOP-5539: add min height to download modal

src/templates/product-landing.js
DOP-5680
[current](https://www.mongodb.com/docs/atlas/app-services/)
[staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/realm/bianca.laube/DOP-5680/index.html)
* Just the homepage that i missed the deprecated project list, now fixed!
=> DOP-5680: Get rid of Rating Component in app-services

README.md
DOP-5715
- Updated the README
- Add Developer Quickstart section
- Remove unneeded .env variables (these get automatically set now)
- Move Staging section to Staging (Deprecated) and put it below Staging with Netlify
--
--
This changes IS "README updates" 😄 
- - [x] This PR introduces changes that should be reflected in the README, and I have made those updates.
=> Dop 5715 update readme

src/components/ComponentFactory.tsx, src/components/Contents/index.tsx, src/components/DismissibleSkillsCard.tsx, src/components/RightColumn.tsx, src/templates/document.js
[Staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/main/docs/matt.meigs/fix-dismiss/data-modeling/design-patterns/index.html)
Regression testing staged pages 
[Staging page with Contents list and Card](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/main/docs/matt.meigs/fix-dismiss/data-modeling/design-antipatterns/index.html)
[Staging page that also was not showing a Card in last iteration that now is](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/main/docs/matt.meigs/fix-dismiss/tutorial/authenticate-a-user/index.html)
[Staging page with no Card](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/main/docs/matt.meigs/fix-dismiss/data-modeling/design-patterns/group-data/bucket-pattern/index.html)
Dismissible Skills Cards would not render if there …
=> bugfix. Dismissible Skills Card allowed without Contents directive

src/components/DismissibleSkillsCard.tsx
DOP-5732
[Current Staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/main/docs/matt.meigs/fix-dismiss/data-modeling/design-antipatterns/index.html)
[New Staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/main/docs/matt.meigs/DOP-5732-tracking/data-modeling/design-antipatterns/index.html)
Adds tracking analytics to the two types of clicks available on the DismissibleSkillsCard. Titles and state of analytics discussed with Sarah Lin.
=> Add tracking to DismissibleSkillsCard

plugins/gatsby-source-snooty-prod/gatsby-node.js, src/context/toc-context.js
N/A for now
[Manual writers' staging](https://deploy-preview-12119--mongodb-manual.netlify.app/docs/upcoming/) - Notice how the TOC shows "Atlas Search" and "Atlas Vector Search"
[Atlas prod deploy](https://www.mongodb.com/docs/atlas/) - Show Atlas CLI and other embedded TOCs
[Manual staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/upcoming/docs/raymund.rodriguez/remove-remote-toc/index.html) (using writers' staging db) - Notice how the TOC shows "Search" and "Vector Search" as expected
[Atlas staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/raymund.rodriguez/remove-remote-toc/index.html) (using prod deployments db) - Still shows Atlas CLI and other 
* This PR removes the ability for writers' staging to fetch remote metadata for embedded …
=> Remove fetching remote TOC in writers' staging

src/context/version-context.tsx, tests/unit/VersionDropdown.test.js
N/A
[Prod](https://www.mongodb.com/docs/cluster-to-cluster-sync/current/) - Using the version dropdown appends the target URL to the current pathname.
[Staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/node/raymund.rodriguez/fix-version-dropdown-navigate/index.html) - version dropdown should **replace** the pathname instead of add it onto the end.
* Seems like the behavior of `navigate` in `gatsby` and `@gatsby/reach-router` are different. The former seems to append to the current pathname while the latter replaces it as we currently use it. We can probably handle this without `navigate` (i.e. with `location` directly), but just reverting this change in the meantime.
- - [ ] This PR introduces changes that should be reflected in the README, and I have made those …
=> Fix version dropdown navigate

src/components/UnifiedSidenav/UnifiedTocNavItems.js, toc_data/toc.ts
DOP-5806
no link, but collapsible items didnt work without a url 
* request from writers to not need a url for collapsible items
=> DOP-5806: collapsible item doesn't need link

src/components/Sidenav/Sidenav.tsx
DOP-5752 follow up. Seems like we introduced a bug in the height of sidenav.
Current behavior in [preprd on cloud manager docs](https://mongodb-cloud-manager-preprd.netlify.app/docs/cloud-manager/)
[Staging link on pymongo](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/pymongo/seung.park/DOP-5752-follow-up/index.html) (same behavior with sidenav)
=> DOP-5752: re add scrolly to style

src/components/UnifiedSidenav/UnifiedTocNavItems.js
DOP-5938
* Micheal pointed out that showsubnav wasnt working for sidenav items inside collapsibles so made that fix in this pr
N/A
N/A
* if you would like to test locally i have a toc.json i can send you. But it was just a bug that i wasnt passing some variables to the collapsible component. 
* 
=> DOP-5938: `showSubNav` inside collapsible

src/components/UnifiedSidenav/UnifiedTocNavItems.js
DOP-6063
* Drawer pages don't collapse on click: [bug report line 22](https://docs.google.com/spreadsheets/d/1Yw46uX0owcq8Velbv_bihO5curwlVT3PwRgs9_xFJsA/edit?gid=0#gid=0)
- example of the current bug, when an active item is selected that has collapsible it doesn't toggle between open and close on click 
https://mongodbcom-cdn.staging.corp.mongodb.com/docs/spark-connector/upcoming/batch-mode/
Released these changes on `bi-connector` in preprd since frontend-stg doesnt work for unified toc for now 
https://mongodbcom-cdn.staging.corp.mongodb.com/docs/bi-connector/current/client-applications/
=> DOP-6063: Collapsible item should open on close on Click of Active item

src/components/Link.tsx
DOP-6061
https://mongodbcom-cdn.staging.corp.mongodb.com/docs/pricing/
N/A since caesar is working on staging links but below is a screenshot of my local host
=> DOP-6061: Icon for external links

src/components/ComposableTutorial/ComposableTutorial.tsx, src/components/ComposableTutorial/ConfigurableOption.tsx, tests/unit/__snapshots__/ComposableTutorial.test.tsx.snap
DOP-6043
[Current page](https://www.mongodb.com/docs/atlas/atlas-vector-search/tutorials/vector-search-quick-start/?deployment-type=atlas&interface=driver&language=python)
[Composable with content before](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-5920/landing/seung.park/DOP-6043/vector-search-quick-start-2/index.html) - content  is located [here](https://github.com/10gen/docs-mongodb-internal/blob/DOP-5920/content/landing/source/vector-search-quick-start-2.txt)
[Composable with repeated content within](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-5920/landing/seung.park/DOP-6043/vector-search-quick-start/index.html) - content is located [here](https://github.com/10gen/docs-mongodb-internal/blob/DOP-5920/content/landing/source/vector-search-quick-start.txt) …
=> DOP-6043: update composable based on design feedback

src/components/Link.tsx, src/components/Sidenav/DocsHomeButton.tsx
DOP-6105: Adding the icon for internal nav links, ie symlinks
** Also found small bug of clicking the `Docs Home` button at the top of the side nav opens in new tab instead of same tab so made that fix 
[slack thread ](https://mongodb.slack.com/archives/C088QVAUS2Z/p1755008760361089)
[figma link](https://www.figma.com/proto/KEtaPAkucUDw2Fdr1k6U7v/TOC-WORK?page-id=3565%3A23307&node-id=4316-36888&viewport=-10679%2C769%2C0.85&t=H6PVLKU2bSLKB3SS-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=4072%3A5949&show-proto-sidebar=1)
* Staging link N/A until [DOP-6105](https://jira.mongodb.org/browse/DOP-6105) is complete
* Also made sure regular external icon svg looks as it should
* <img width="237" height="198" alt="Screenshot 2025-08-12 at 1 13 19 PM" …
=> DOP-6105: Adding icon for internal toc node symlinks

src/components/VersionDropdown/index.tsx
DOP-6123
* Mellisa noticed when you are on a content site and loading a different a version dropdown on a different site the legacy docs option in the dropdown wont take you to the legacy docs page. Need to fix the behavior so when ever you select legacy docs it will link you to the correct page
* [bug report line 52](https://docs.google.com/spreadsheets/d/1Yw46uX0owcq8Velbv_bihO5curwlVT3PwRgs9_xFJsA/edit?gid=0#gid=0)
https://mongodbcom-cdn.staging.corp.mongodb.com/docs/development/
https://deploy-preview-1519--docs-frontend-stg.netlify.app/docs/
click on `Development` L1 to see the version selector
=> DOP-6123: allow for legacy docs to link

src/components/HorizontalList.tsx
DOP-6046
[See this page for horizontal list item](https://www.mongodb.com/docs/atlas/unsupported-commands/)
[Staged above individual page via S3](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/preprd/cloud-docs/seung.park/DOP-6046/unsupported-commands/index.html)
- Verifying with Design team that this is the direction (vs scrollable table)
- Above has been verified, and we will tackle text wrapping with monospace as a separate mobile issue
=> DOP-6046: fix styling for HL

src/components/ComposableTutorial/ComposableTutorial.tsx, tests/unit/ComposableTutorial.test.tsx
DOP-6125
Follow this link and notice the marketing query params being dropped
https://www.mongodb.com/docs/atlas/atlas-vector-search/tutorials/vector-search-quick-start/?utm_source=testSource&utm_medium=testMedium&utm_campaign=testCampaign 
Same query parameters but on staging deploy preview:
https://deploy-preview-14008--mongodb-cloud-docs.netlify.app/docs/atlas/atlas-vector-search/tutorials/vector-search-quick-start/?utm_source=testSource&utm_medium=testMedium&utm_campaign=testCampaign
Note the original query params are preserved
=> DOP-6125: preserve external query params on composable tutorials

plugins/gatsby-source-snooty-prod/gatsby-node.js, plugins/utils/banner.js, src/init/DocumentDatabase.js, src/utils/realm.ts, tests/unit/SiteBanner.test.tsx
DOP-6162
https://www.mongodb.com/docs/
Below see that the banner pill says "MongoDB Jokes" and when clicked it takes you to a Dad jokes site :) 
[Staging](https://deploy-preview-1552--docs-frontend-stg.netlify.app/docs/manual/)
MIgrate getBanner
=> DOP-6162: Migrate `getBanner`

src/components/ComposableTutorial/ComposableTutorial.tsx
DOP-6197
This link contains a ref hash id (test in incognito window or clear local storage)
http://mongodb.com/docs/atlas/atlas-search/tutorial/#create-the--index.-18
This does not lead users to any significant portion of the page, just makes default selections.
This staging link takes users to the correct selections and to the ref on the page:
https://deploy-preview-1563--docs-frontend-stg.netlify.app/docs/atlas/atlas-search/tutorial/#create-the--index.-18
- This behavior is done by memoizing all the hashes included in each composable content at build time, and verifying if the hash in URL belongs to a selected content.
- **In the case that multiple composable content have the same ref**, this is a content issue and will result in the first composable content being returned.
- - [ ] This …
=> DOP-6197: add ref/hash behavior
