mongodb/snooty

- front-end/src/components/Code.js
- front-end/src/components/ComponentFactory.js
- front-end/src/components/GuideHeading.js
- front-end/src/components/GuideSection.js
- front-end/src/components/Tabs.js
- front-end/src/components/URIText.js
- front-end/src/components/URIWriter.js
- front-end/src/constants.js
- front-end/src/templates/guide.js
- front-end/tests/ListTable.test.js
- front-end/tests/URIText.test.js
- front-end/tests/URIWriter.test.js
Removes all warnings when running `npm test` (mostly replacing `templateType` with `activeDeployment`) and makes general improvements to pill implementation. This includes updating the constants file to be more readable.
> Bugfix: templateType, pills

- gatsby-node.js
- src/localStorage.js
- src/templates/guide.js
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5086)] This PR fixes Gatsby builds by doing the following:
- Removes modals, which were the only components relying on the `mongodb-stitch-browser-sdk` package (the cause of failure)
- Updates localStorage functions to first check if the runtime environment is a browser
> DOCSP-5086: Fix Build

- src/components/Roles/Code.js
- tests/unit/__snapshots__/Role.test.js.snap
Fixes a few roles that were generating incorrect links. Used the regression testing suite to ensure we're now generating the correct links in all places.
> Fix incorrect links

- src/components/GuideBreadcrumbs.js
- src/templates/guide.js
[[Staging](https://docs-mongodborg-staging.corp.mongodb.com/guides/sophstad/fix-hook/)] Fix hook error that caused broken `develop` environment. Moves Breadcrumbs into their own component.
> Fix build error

- src/components/URIWriter/LocalForm.js
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5878)] [[Staging](https://docs-mongodborg-staging.corp.mongodb.com/guides/sophstad/DOCSP-5878/)]
- Fix URI Writer on Safari
- Improve logic so that we never delete all host input fields
> DOCSP-5878: URI Writer fixes

- src/components/Lightbox.js
Ticket: [https://jira.mongodb.org/browse/DOCSP-5936](https://jira.mongodb.org/browse/DOCSP-5936)
Staging: [https://docs-mongodbcom-staging.corp.mongodb.com/guides/raymundrodriguez/DOCSP-5936/cloud/migrate-from-aws-to-atlas](https://docs-mongodbcom-staging.corp.mongodb.com/guides/raymundrodriguez/DOCSP-5936/cloud/migrate-from-aws-to-atlas)
> DOCSP-5936: Add escape key support to image lightbox

- src/components/GuideSection.js
- src/components/TOC.js
- src/templates/guide.js
Staging link: [https://docs-mongodbcom-staging.corp.mongodb.com/guides/raymundrodriguez/DOCSP-5934/](https://docs-mongodbcom-staging.corp.mongodb.com/guides/raymundrodriguez/DOCSP-5934/)
Ticket link: [https://jira.mongodb.org/browse/DOCSP-5934](https://jira.mongodb.org/browse/DOCSP-5934)
> DOCSP-5934: Clicking on left hand nav item scrolls correctly

- src/components/CaptionLegend.js
- src/components/Figure.js
- src/components/Lightbox.js
- src/components/Paragraph.js
- tests/unit/__snapshots__/Figure.test.js.snap
- tests/unit/__snapshots__/Lightbox.test.js.snap
[[JIRA](https://jira.mongodb.org/browse/DOCSP-6575)] [[Compass Staging](https://docs-mongodbcom-staging.corp.mongodb.com/compass/sophstad/DOCSP-6575/export-pipeline-to-language#select-your-desired-export-language)]
> DOCSP-6575: Add support for image caption and legend

- src/components/Code.js
- src/components/GuideHeading.js
- src/components/Pills.js
- src/components/Tabs.js
- src/components/URIWriter/URIWriter.js
- src/components/layout.js
- src/components/tab-context.js
[[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/guides/sophstad/bugfix-local-storage/)] Fix bug where pill state was not selected from local storage on load.
> Bugfix: Fix localStorage pills in Guides

- src/components/ComponentFactory.js
- src/components/Deprecated.js
- src/components/VersionAdded.js
- src/components/VersionChanged.js
- src/components/VersionModified.js
[[JIRA](https://jira.mongodb.org/browse/DOCSP-6528)] [[BI Connector Staging](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/sophstad/DOCSP-6528/reference/mongosqld)]
> DOCSP-6528: Add deprecated, versionchanged, versionadded handling

- gatsby-node.js
[[JIRA](https://jira.mongodb.org/browse/DOCSP-6855)] [[Guides Staging](https://docs-mongodbcom-staging.corp.mongodb.com/guides/sophstad/DOCSP-6855/)] [[BI Connector Staging](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/sophstad/DOCSP-6855/)] Optimize fetching image assets so as to avoid iterating over the ASTs. The presence of images in the staging links indicates that the refactor is working correctly.
> DOCSP-6855: Improve fetching & saving of assets

- src/components/ComponentFactory.js
- src/components/Footnote.js
- src/components/FootnoteReference.js
- src/components/Paragraph.js
- src/components/layout.js
- src/templates/document.js
- src/utils/intersperse.js
[[JIRA](https://jira.mongodb.org/browse/DOCSP-6801)] [[Cloud Staging](https://docs-mongodbcom-staging.corp.mongodb.com/cloud/sophstad/DOCSP-6801/billing)] Implement front-end handling of anonymous and named footnotes.
> DOCSP-6801: Implement footnote directive

- src/components/CSSWrapper.js
[[JIRA](https://jira.mongodb.org/browse/DOCSP-7193)] [[Compass Staging](https://docs-mongodbcom-staging.corp.mongodb.com/compass/sophstad/DOCSP-7193/connect)]
> DOCSP-7193: Improve handling of class names in CSSWrapper

- src/templates/document.js
> Bugfix: don't render TOC in preview mode

- package-lock.json
- package.json
- src/components/dev-hub/layout.js
- src/components/dev-hub/theme.js
- src/pages/dev-hub/community.js
- src/pages/dev-hub/index.js
- src/pages/dev-hub/learn.js
- src/pages/dev-hub/storybook.js
- src/pages/storybook.js
- src/styles/devhub.js
@jestapinski Mind if we close #145 in favor of this one which re-orgs a little?
> Gb create pages

- .github/workflows/test.yml
Run tests:
- When PR is opened from a branch or fork (and whenever updates are pushed to that PR)
- When a new commit is merged to master
I don't think people often look at Actions for a branch before they've opened a PR, so this will avoid running duplicate tests on a PR.
> Run tests when PR is opened from fork

- src/templates/guide.js
Jira: https://jira.mongodb.org/browse/DOP-579
Staging: https://docs-mongodborg-staging.corp.mongodb.com/master/guides/tahiya.chowdhury/DOP-579/
> See also links rendering without title text in guides

- package-lock.json
- package.json
- src/components/VersionDropdown.js
- src/styles/version-dropdown.module.css
Jira: https://jira.mongodb.org/browse/DOP-785
Stagining: https://docs-mongodbcom-staging.corp.mongodb.com/master/manual/tahiya.chowdhury/DOP-785/
> Dop 785: Use LeafyGreen Button component for version dropdown

- scripts/ensure-master.js
Fixes release script which broke due to a broken dependency.
> fix release script

- src/components/Code.js
- src/styles/code.module.css
[[JIRA](https://jira.mongodb.org/browse/DOP-1003)] [[Datalake Staging](https://docs-mongodbcom-staging.corp.mongodb.com/DOCSP-9936/datalake/sophstad/DOP-1003/)] [[Drivers Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/drivers/sophstad/DOP-1003/)] [[Guides Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/guides/sophstad/DOP-1003/)]
- Fix newline bug
- Handle `:copyable:` flag
- Handle `:linenos:` flag
> DOP-1003: Code block bugfixes

- src/components/FeedbackWidget/FeedbackCard.js
- src/styles/code.module.css
[[Datalake Staging](https://docs-mongodbcom-staging.corp.mongodb.com/DOCSP-9936/datalake/sophstad/fix-codeblock/)]
- Fix issue where code block appeared on top of feedback widget
- Fix newline error on Firefox
> Bugfix: Codeblock

- src/components/ComponentFactory.js
Adds `"raw"` to the `ComponentFactory.js`'s list of ignored (directive) names
> DOP-1008: Ignore raw directive

- src/components/VersionDropdown.js
[[Datalake Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/datalake/sophstad/bugfix-version-dropdown/)]
> Bugfix: hide dropdown if only one version

- src/components/layout.js
- src/templates/document.js
- src/templates/ecosystem-index.js
- src/templates/guide.js
- src/templates/guides-index.js
- src/templates/landing.js
[[Drivers Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/drivers/sophstad/bugfix-v10/)]
- Fix code block/navbar bug
- Fix published branches undefined bug
> Fix navbar overlap bug

- src/html.js
- static/scripts/gtm.js
[[JIRA](https://jira.mongodb.org/browse/DOP-1146)] [[Drivers Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/drivers/sophstad/DOP-1146/)]
- Add Google Tag Manager code
> DOP-1146: Add support for Google Tag Manager

- src/components/Navbar.js
- src/constants.js
- tests/unit/__snapshots__/Navbar.test.js.snap
[[JIRA](https://jira.mongodb.org/browse/DOP-946)] [[Drivers Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/drivers/sophstad/DOP-946/)] [[BI Connector Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/bi-connector/sophstad/DOP-946/)]
- Fixes bug where Drivers was not highlighted in navbar on drivers page
> DOP-946: Fix navbar active sections

- src/components/site-metadata.js
[[Drivers Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/drivers/sophstad/disable-search/)] [[Homepage Staging](https://docs-mongodbcom-staging.corp.mongodb.com/DOP-1121/landing/sophstad/disable-search/)]
> Disable Search

- src/components/Navbar.js
- tests/unit/__snapshots__/Navbar.test.js.snap
[[Homepage Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/landing/sophstad/navbar-remove-realm/)] [[Drivers Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/drivers/sophstad/navbar-remove-realm/)]
> Remove realm from top navbar

- src/components/LiteralInclude.js
- tests/unit/__snapshots__/LiteralInclude.test.js.snap
- tests/unit/data/LiteralInclude.test.json
Reverts mongodb/snooty#200 in order to release updated .live banner without this change.
> Revert "DOP-877: Properly render literal includes"

- src/components/List.js
- tests/unit/__snapshots__/List.test.js.snap
- tests/unit/data/List.test.json
[[JIRA](https://jira.mongodb.org/browse/DOP-1184)] [[Drivers Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/drivers/sophstad/DOP-1184/)] [[Charts Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/charts/sophstad/DOP-1184/launch-charts#optional-create-an-cluster)] Update `List` component to address AST changes made in [DOP-1210](https://jira.mongodb.org/browse/DOP-1210) and [DOP-1129](https://jira.mongodb.org/browse/DOP-1129).
- Apply numbering type to ordered list
- Apply `start` attribute to ordered list
> DOP-1184: Update list component

- src/components/ListTable.js
- Fixes non-stub-column spacing
- Fixes appearance of blank page
- [Docs-charts](https://docs-mongodbcom-staging.corp.mongodb.com/master/charts/claire/DOP-1012-2/data-source-permissions)
- [BI-connector](https://docs-mongodbcom-staging.corp.mongodb.com/master/bi-connector/claire/DOP-1012-2/reference/drdl)
> DOP-1012-2: Fix CSSWrapper bug

- src/components/InternalPageNav.js
- src/templates/document.js
- [BI-Connector](https://docs-mongodbcom-staging.corp.mongodb.com/master/bi-connector/claire/DOP-1011/atlas-bi-connector), [BI-connector doc](https://github.com/mongodb/docs-bi-connector/blob/master/source/atlas-bi-connector.txt)
- [Datalake](https://docs-mongodbcom-staging.corp.mongodb.com/master/datalake/claire/DOP-1011/reference/config-files/data-lake-configuration), [Datalake doc](https://github.com/10gen/docs-datalake/blob/master/source/config/config-data-lake.txt)
> DOP-1011: Implement :noprevnext: functionality

- src/components/ComponentFactory.js
[[Landing Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/landing/sophstad/component-factory/)] [[Drivers Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/drivers/sophstad/component-factory/)] Just a few improvements to the component factory:
- Remove old code
- AST no longer outputs `problematic` nodes
- Domain namespace no longer included in a node's `name` field
- Convert from class to function component
- Improve warning for missing component
> Improve component factory

- package-lock.json
- package.json
- src/components/Searchbar/SearchContext.js
- src/components/Searchbar/SearchResult.js
- src/components/Searchbar/Searchbar.js
[Ecosystem Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/ecosystem/jordanstapinski/highlighting/)
[Guides Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/guides/jordanstapinski/highlighting/)
This PR adds search highlighting to the searchbar baed on the entered term. For tracking the entered term, I added a small `SearchContext` to avoid prop drilling the search term.
For handling the highlighting, I took an approach where we replace relevant terms with an HTML string, sanitize inputs with a new dependency [`sanitize-html`](https://www.npmjs.com/package/sanitize-html), and render using `dangerouslySetInnerHTML`. Because we sanitize, we are not introducing new risk in doing so.
Not sure if there is a better approach to dynamic highlighting?
> DOP-1220 Part 4: Safe Search Highlighting

- src/components/Select.js
- tests/unit/Select.test.js
- tests/unit/__snapshots__/Select.test.js.snap
[Search Ecosystem Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/ecosystem/jordanstapinski/select-component/)
(I didn't think it was worth re-building this branch since the component is not being used anywhere yet, so it can be seen in the WIP search work)
This PR takes the component from #240 and compares it against master.
> DOP-1276 Add Generic Select Component

- src/components/Select.js
- tests/unit/Select.test.js
No staging link because we're not using this anywhere yet. Also included the color fix. Thanks!
> Add reset functionality to Select

- src/components/Searchbar/ExpandedSearchbar.js
- src/components/Searchbar/SearchTextInput.js
- src/components/Searchbar/Searchbar.js
- src/utils/search-params-to-url.js
- tests/unit/SearchResults.test.js
- tests/unit/Searchbar.test.js
- tests/unit/__snapshots__/SearchResults.test.js.snap
- tests/unit/__snapshots__/Searchbar.test.js.snap
- tests/unit/utils/mock-marian-fetch.js
No JIRA
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/DOP-1337/landing/jordanstapinski/search-testing/)
This PR adds significant UI testing for the searchbar and search results page. We go through each action and ensure the UI is properly updated. We also add in a mock for calls to Marian which allows us to test our expected endpoint hits as well.
Jest also raised some DOM-related warnings, so this PR fixes those as well.
To check these, run:
```
npm run test tests/unit/SearchResults.test.js
npm run test tests/unit/Searchbar.test.js
```
> Searchbar & Search Results Testing

- gatsby-browser.js
- gatsby-ssr.js
- jest-preprocess.js
- jest.config.js
- package-lock.json
- package.json
- src/components/Code.js
- src/components/ComponentFactory.js
- src/components/ListTable.js
- src/components/OpenAPI.js
- src/components/Operation.js
- src/components/Roles/Required.js
- src/components/layout.js
- tests/emotionTestSetup.js
- tests/unit/ListTable.test.js
- tests/unit/Operation.test.js
- tests/unit/__snapshots__/ListTable.test.js.snap
- tests/unit/__snapshots__/Operation.test.js.snap
- tests/unit/data/Operation.test.json
[[JIRA](https://jira.mongodb.org/browse/DOP-1357)] [[Realm Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/sophstad/DOP-1357/admin/api/v3#base-url)] [[InVision](https://mongodb.invisionapp.com/d/main#/console/19952470/417730474/preview)]
- Render OpenAPI spec in page
- Implement [`LeafyGreen Provider`](https://github.com/mongodb/leafygreen-ui/tree/master/packages/leafygreen-provider) (this should have been done a while ago!)
- Render `ListTable` component with horizontal overflow scrolling
- Improve Jest config for testing with Emotion
> DOP-1357: Render OpenAPI

- package-lock.json
- package.json
- src/components/Admonition.js
[[JIRA](https://jira.mongodb.org/browse/DOP-1415)] [[Compass Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/compass/sophstad/DOP-1415/import-export)] Now that the `Example` callout has been released by LeafyGreen, use it to render `example` directives.
> DOP-1415: Render Example callout

- src/components/ComponentFactory.js
- src/components/Roles/Red.js
[DOP-1490] [[Manual Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/manual/sophstad/DOP-1490/reference/command/update#shard-key-modification)] Render `:red:` role (un-deprecated in https://github.com/mongodb/snooty-parser/pull/217).
> DOP-1490: Render :red:

- package-lock.json
- package.json
- src/components/ComponentFactory.js
- src/components/Roles/Kbd.js
[DOP-1396] [[MongoDB CLI Staging](https://docs-mongodbcom-staging.corp.mongodb.com/snooty-setup/mongocli/sophstad/DOP-1396/configure/autocomplete)] Add support for `:kbd:` role.
> DOP-1396: Support kbd role

- package-lock.json
- package.json
[DOP-1594] [[Datalake Staging](https://docs-mongodbcom-staging.corp.mongodb.com/DOCSP-12427/datalake/sophstad/DOP-1594/reference/cli/collections/create-collections-views)] Verified there are no more blank pages in Datalake!
> DOP-1594: Upgrade LeafyGreen Code package

- src/components/TabSelectors.js
[DOP-1544](https://jira.mongodb.org/browse/DOP-1544). [Cloud-docs](https://docs-mongodbcom-staging.corp.mongodb.com/snooty-setup/cloud-docs/cgoecknerwald/DOP-1544/tutorial/connect-to-your-cluster).
> DOP-1544: Add Segment analytics

- src/components/DocumentBody.js
- src/templates/blank.js
- src/templates/document.js
- src/templates/ecosystem-index.js
- src/templates/guide.js
- src/templates/landing.js
[[BI Connector Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/bi-connector/sophstad/footnote-fix/)] Move `Footer` component into `DocumentBody` component to ensure it is always a child of `FeedbackProvider`. Fixes error introduced in #303
> Fix feedback context error

- gatsby-node.js
- src/utils/setup/save-asset-files.js
[DOP-1701] [[Charts Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/charts/sophstad/DOP-1701/)] Write a file to the filesystem for each path used to refer to a given image.
> DOP-1701: Update image writes

- src/components/CaptionLegend.js
[DOP-1599] [[Realm Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/sophstad/DOP-1599/sync/partitioning)]
> DOP-1599: Add caption styling

- src/components/Navbar.js
- src/components/Searchbar/Searchbar.js
- src/layouts/index.js
- src/theme/docsTheme.js
[[Jira Ticket](https://jira.mongodb.org/browse/DOP-1860)]
[[Atlas Staging](https://jira.mongodb.org/browse/DOP-1860)]
I decided to keep the .live images in case we wanted to easily reuse it in the future, but I'm totally down to just delete it if it's not necessary to keep.
> DOP-1860: Remove .live banner

- src/constants.js
- src/utils/search-params-to-url.js
- tests/unit/Searchbar.test.js
- tests/unit/utils/mock-marian-fetch.js
[[Jira Ticket](https://jira.mongodb.org/browse/DOP-1792)]
[[Atlas Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/cloud-docs/raymundrodriguez/DOP-1792/)]
> DOP-1792: Change search url to keep it uniform across docs

- src/utils/setup/save-asset-files.js
[[Jira Ticket](https://jira.mongodb.org/browse/DOP-1879)]
[[Database Tools Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/database-tools/raymundrodriguez/DOP-1879/)]
> DOP-1879: Update saving static files to exclude manpages without buffers

- src/html.js
[DOP-1402](https://jira.mongodb.org/browse/DOP-1402). 
[Staging -- node](https://docs-mongodbcom-staging.corp.mongodb.com/master/node/cgoecknerwald/DOP-1402/?delighted=test).
[Staging -- drivers](https://docs-mongodbcom-staging.corp.mongodb.com/master/drivers/cgoecknerwald/DOP-1402/?delighted=test).
(Add `?delighted=test` to force the survey to appear.)
> DOP-1402: Add Delighted Widget to Node driver docs

- src/components/Code.js
[[Jira ticket](https://jira.mongodb.org/browse/DOP-1899)]
[[Realm staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/raymundrodriguez/DOP-1899/deploy/create-with-cli)]
> DOP-1899: Add Segment tracking on codeblock

- src/components/Searchbar/SearchResult.js
[DOP-1942] [[Realm Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/sophstad/DOP-1942/)]
> DOP-1942: Safely escape search queries

- src/components/Widgets/FeedbackWidget/FeedbackFullScreen.js
re: https://mongodb.slack.com/archives/CLY6HQWUE/p1613387197037800
Tested in Chrome simulator and on my iPhone through ngrok.
> Fix feedback widget scrolling on mobile

- src/components/Searchbar/SearchTextInput.js
- src/components/Searchbar/Searchbar.js
- tests/unit/Searchbar.test.js
[DOP-1994] [[Realm Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/sophstad/DOP-1994/)] [[BI Connector Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/bi-connector/sophstad/DOP-1994/) (no filter applied)]
> DOP-1994: Default to searching Realm on Realm docs

- src/templates/landing.js
Jira: [DOP-1976](jira.mongodb.org/browse/DOP-1976) | Staging: [docs-landing](https://docs-mongodborg-staging.corp.mongodb.com/structured-test/landing/allison/DOP-1976/)
> DOP-1976: add structured brand data to landing

- src/components/BreadcrumbSchema.js
- src/components/Breadcrumbs.js
- src/templates/document.js
- tests/unit/BreadcrumbSchema.test.js
- tests/unit/Breadcrumbs.test.js
- tests/unit/__snapshots__/Breadcrumbs.test.js.snap
DOP-1975
[Compass Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/compass/sophstad/bugfix-DOP-1975/)
[Atlas Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/cloud-docs/sophstad/bugfix-DOP-1975/)
> DOP-1975: Fix breadcrumb schema bug

- package-lock.json
- package.json
- src/components/Searchbar/ExpandedSearchbar.js
- [BI Connector](https://docs-mongodbcom-staging.corp.mongodb.com/master/bi-connector/sophstad/fix-textinput/)
- Upgrade to [v6](https://github.com/mongodb/leafygreen-ui/blob/main/packages/text-input/CHANGELOG.md#600) of component, which fixes a warning around accessibility
> Fix TextInput accessibility warning

- package-lock.json
- package.json
- src/components/CopyButton.js
- src/components/Operation.js
- tests/unit/Operation.test.js
- tests/unit/__snapshots__/Operation.test.js.snap
DOP-2109
[Realm](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/sophstad/DOP-2109/admin/api/v3/#realm-administrator-apis)
- I used [this tool](https://www.soscisurvey.de/tools/view-chars.php) to examine the invisible characters and ensure they don't appear when using the copy button
> DOP-2109: Add copy button to OpenAPI

- src/components/icons/Go.js
DOP-1815
[Docs Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/docs/carolinao/dop-1815/tutorial/query-documents/)
- Added {...styles}  to Go.js file
> DOP-1815 - Go Language logo display problems

- src/constants.js
- src/hooks/use-marian-manifests.js
DOP-2239
https://docs-mongodbcom-staging.corp.mongodb.com/8e4f6b05be631cd4bd413141aba100f8740e7037/bi-connector/heli/master/
> DOP-2239: Update marian endpoint to docs-search-transport

- gatsby-browser.js
- gatsby-ssr.js
- package-lock.json
- package.json
- src/clients/auth.js
- src/components/Navbar.js
- src/contexts/user-context.js
- src/pages/oidc.js
DOP-2280
N/A - currently only configured for localhost and an Okta sandbox environment.
- Adds logic around construction of login, signup, and logout links originating from a docs property.
- Adds logic for parsing and initializing an idToken and application session when login originates from a docs property
- Adds logic for initializing an idToken and application session when a user has an Okta IDP session present, but no application session within docs.
> Dop 2280 - SSO Session Initialization

- src/theme/docsTheme.js
DOP-2318
[Realm](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/raymundrodriguez/DOP-2318/)
[Landing](https://docs-mongodbcom-staging.corp.mongodb.com/master/landing/raymundrodriguez/DOP-2318/)
* Set `bannerContent.enabled` to `false` to remove banner
> DOP-2318: Remove .Live banner

- package-lock.json
- package.json
- src/components/SearchResults/EmptyResults.js
- src/layouts/index.js
DOP-2423
*Realm:*
https://docs-mongodborg-staging.corp.mongodb.com/master/realm/cassidy.schaufele/DOP-2423/
Updates to rc.13 of the consistent navigation.
Fixes UI bug where our legacy css applied a color on hover to footer links.
Adds logic for focus on new search input when consistent nav is enabled
> DOP-2423: Bump nav version, add a little more polish

- src/components/MainColumn.js
- src/components/Sidenav/IA.js
- src/components/Sidenav/Sidenav.js
- src/components/Sidenav/SidenavBackButton.js
- src/components/Sidenav/TOCNode.js
- src/components/Sidenav/styles/sideNavItem.js
- src/components/VersionDropdown.js
DOP-2425
[Docs Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/docs/raymundrodriguez/DOP-2425/)
[Landing Staging](https://docs-mongodbcom-staging.corp.mongodb.com/upstream-nav/landing/raymundrodriguez/DOP-2425/)
[Realm Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/raymundrodriguez/DOP-2425/)
* Updated padding and margins to save vertical space and to make nested TOC items more visibly distinct from parents.
> DOP-2425: Update padding and margins for TOC

- src/components/EcosystemHomepageTiles.js
This updates the ecosystem homepage to link to the new go docs.
> changes target for go

- src/components/Footer.js
- src/components/Header.js
- src/components/SearchResults/EmptyResults.js
- src/components/Sidenav/Sidenav.js
- src/components/Sidenav/SidenavBackButton.js
DOP-2435
**Landing -> Develop Applications**
https://docs-mongodbcom-staging.corp.mongodb.com/master/landing/cassidy.schaufele/DOP-2435/develop-applications/
Cleans up all instances of `process.env.GATSBY_FEATURE_FLAG_CONSISTENT_NAV` and related logic.
> DOP-2435: Cleanup Feature Flag Logic

- src/components/Sidenav/Sidenav.js
> DOP-2489: Update Community Link

- src/components/SearchResults/EmptyResults.js
[DOP-2465](https://jira.mongodb.org/browse/DOP-2465)
[Staging Link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/grace.chong/DOP-2465/search/index.html?q=mongoshrc)
> (DOP-2465) Fix error message for search with no results

- src/components/RightColumn.js
- src/components/Select.js
[DOP-2570](https://jira.mongodb.org/browse/DOP-2570)
[Docs Staging Link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/grace.chong/DOP-2570/indexes/index.html)
> (DOP-2570) Fix language selector dropdown to be visible

- src/utils/site-metadata.js
> DOP-2712  Add new env variables for dotcom environments

- src/components/Permalink.js
[Compass Staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/compass/raymundrodriguez/fix-headerbuffer/troubleshooting/connection-errors/)
* No logic changed except for bringing `HeaderBuffer` styled component outside of `Permalink`.
* This fixes a small bug where the currently active heading was not able to be determined.
> Fix HeaderBuffer declaration

- src/components/Code/CodeIO.js
- src/components/Code/Output.js
[DOP-2748](https://jira.mongodb.org/browse/DOP-2748)
[Atlas Staging Link](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/grace.chong/DOP-2748/driver-connection/index.html#driver-examples) (toggle language to Python to see a comprehensive list of examples)
> DOP-2748: Fix border radius on single input issue

- src/components/Code/CodeIO.js
- tests/unit/CodeIO.test.js
- tests/unit/__snapshots__/CodeIO.test.js.snap
- tests/unit/data/CodeIO.test.json
[DOP-2760](https://jira.mongodb.org/browse/DOP-2760)
[Atlas Staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/grace.chong/DOP-2760/driver-connection/index.html#driver-examples) - the first 3 examples under Driver's Examples
> DOP-2760: Make default visibility for output code snippet to be visible, with new option to specify visibility settings

- package-lock.json
- package.json
- src/components/ComponentFactory.js
- src/components/Video/Video.js
- src/components/Video/VideoPlayButton.js
- tests/unit/Video.test.js
- tests/unit/__snapshots__/Video.test.js.snap
- tests/unit/data/Video.test.json
[DOP-2754](https://jira.mongodb.org/browse/DOP-2754)
[Compass Staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/compass/grace.chong/DOP-2754/connect/index.html)
> DOP-2754: Video embeddings frontend components

- src/components/Code/CodeIO.js
- src/components/Sidenav/ProductsList.js
- src/components/Sidenav/Sidenav.js
- src/components/Sidenav/TOCNode.js
- src/components/Sidenav/styles/sideNavItem.js
- tests/unit/Toctree.test.js
[DOP-2645](https://jira.mongodb.org/browse/DOP-2645)
[Realm Staging Link](https://docs-mongodbcom-integration.corp.mongodb.com/master/realm/grace.chong/DOP-2645/mongodb/index.html)
[Compass Staging Link](https://docs-mongodbcom-integration.corp.mongodb.com/master/compass/grace.chong/DOP-2645/index.html)
> DOP-2645: Add carats to sidenav to indicate level

- src/components/ComponentFactory.js
- src/components/Heading.js
- src/components/Procedure.js
- src/components/Procedure/Procedure.js
- src/components/Procedure/Step.js
- tests/unit/Procedure.test.js
- tests/unit/Step.test.js
- tests/unit/__snapshots__/Procedure.test.js.snap
- tests/unit/data/Procedure.test.json
DOP-2763
[Guides staging](https://docs-mongodbcom-integration.corp.mongodb.com/DOP-2763/guides/raymundrodriguez/DOP-2763/cloud/account/#nested-procedure-test)
* The `Procedure` component now dives into `include` nodes to look for additional steps to maintain order of steps.
* `Procedure` and `Step` components are now in the same folder.
> DOP-2763: Render nested steps with correct step numbers

- .github/pull_request_template.md
[DOP-2828](https://jira.mongodb.org/browse/DOP-2828)
> DOP-2828: Add current behavior section to PR template

- src/components/SearchResults/SearchResults.js
- tests/unit/__snapshots__/SearchResults.test.js.snap
[DOP-2955](https://jira.mongodb.org/browse/DOP-2955)
[Landing Behavior with Incorrect Styling](https://docs-mongodbcom-integration.corp.mongodb.com/master/landing/cassidy.schaufele/DOP-2951-staging/search/?q=test) 
[Landing Staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/landing/grace.chong/DOP-2955/search/?q=test)
> DOP-2955: Fix small loading skeleton issue

- src/components/DeprecatedVersionSelector.js
[DOP-2985](https://jira.mongodb.org/browse/DOP-2985)
[Landing Production](https://www.mongodb.com/docs/legacy/)
[Landing Staging Legacy](https://docs-mongodbcom-integration.corp.mongodb.com/master/landing/grace.chong/DOP-2985/legacy/)
> DOP-2985: Fix legacy dropdown for latest versions

- src/components/Code/Code.js
- src/components/Code/Output.js
- src/utils/get-language.js
[DOP-3004](https://jira.mongodb.org/browse/DOP-3004)
[Atlas Staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/grace.chong/DOP-3004/driver-connection/#driver-examples) - go to Python examples to see unknown language on input/output
> DOP-3004: Fix output directive to be able to handle unknown languages

- package-lock.json
- package.json
DOP-3067
[Realm](https://www.mongodb.com/docs/realm/) 
[Realm Staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/realm/grace.chong/DOP-3067/)
> DOP-3067: Bump consistent nav version

- src/components/OpenAPI/whitelist.js
CLOUDP-110876
Adding our internal bucket to be able to preview from our CI/CD
> CLOUDP-110876: Allow a staging version of PR changes to be created to  help reviewers

- package-lock.json
- package.json
- src/components/OpenAPI/whitelist.js
- src/components/Tabs/index.js
This reverts commit 77cbaea06b5c23a5d29eea4b9451bdcfff24923f.
as discussed during planning, will include these changes, off a new branding-base-branch (name tbd)
> Revert "Update leafygreen-ui/tabs to v8 (#656)"

- package-lock.json
- package.json
- src/components/Banner/styles/bannerItemStyle.js
- tests/unit/__snapshots__/Banner.test.js.snap
- tests/unit/__snapshots__/CTABanner.test.js.snap
[DOP-2579](https://jira.mongodb.org/browse/DOP-2579)
[figma design (see Banners under Presentation tab)](https://www.figma.com/file/PctpWXNmlv0khZahanOsU7/FY22-New-Brand?node-id=143%3A18389)
[datalake docs](https://www.mongodb.com/docs/datalake/)
[atlas docs](https://www.mongodb.com/docs/atlas/reference/api/custom-roles-create-a-role/)
[server docs](https://www.mongodb.com/docs/manual/core/queryable-encryption/)
[datalake docs](https://docs-mongodbcom-integration.corp.mongodb.com/master/datalake/seung.park/DOP-2579/)
[atlas docs](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/seung.park/DOP-2579/reference/api/custom-roles-create-a-role/)
[server docs](https://docs-mongodbcom-integration.corp.mongodb.com/master/docs/seung.park/DOP-2579/core/queryable-encryption/)
> DOP-2579: update banner component

- tests/unit/__snapshots__/Operation.test.js.snap
Failed run on branding-master branch due to latest merge from [this PR](https://github.com/mongodb/snooty/pull/683)
https://github.com/mongodb/snooty/runs/8078085157?check_suite_focus=true
- this PR updates failing unit tests (3 snapshot failures, updated snapshots)
> DOP-2581: update tests

- package-lock.json
- package.json
- src/components/Banner/styles/bannerItemStyle.js
- tests/unit/__snapshots__/Banner.test.js.snap
- tests/unit/__snapshots__/CTABanner.test.js.snap
- tests/unit/__snapshots__/Operation.test.js.snap
Includes current sprint's (Q3S3) work in progress to test builds against master branch
> Branding master branch

- package-lock.json
- package.json
- tests/unit/__snapshots__/Role.test.js.snap
DOP-2582
[Create Atlas Account](https://www.mongodb.com/docs/atlas/tutorial/create-atlas-account/)
[Staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/caro.obregon/inline-def/tutorial/create-atlas-account//)
Upgraded inline definition component to new Leafygreen standard to comply with new branding guidelines
> DOP-2582 - Working inline component

- src/components/Link.js
- src/components/Literal.js
- tests/unit/__snapshots__/BreadcrumbContainer.test.js.snap
- tests/unit/__snapshots__/Breadcrumbs.test.js.snap
- tests/unit/__snapshots__/Button.test.js.snap
- tests/unit/__snapshots__/CardRef.test.js.snap
- tests/unit/__snapshots__/Chapter.test.js.snap
- tests/unit/__snapshots__/DefinitionList.test.js.snap
- tests/unit/__snapshots__/Field.test.js.snap
- tests/unit/__snapshots__/FieldList.test.js.snap
- tests/unit/__snapshots__/GuideNext.test.js.snap
- tests/unit/__snapshots__/GuidesLandingTree.test.js.snap
- tests/unit/__snapshots__/InternalPageNav.test.js.snap
- tests/unit/__snapshots__/Line.test.js.snap
- tests/unit/__snapshots__/Link.test.js.snap
- tests/unit/__snapshots__/Literal.test.js.snap
- tests/unit/__snapshots__/Procedure.test.js.snap
- tests/unit/__snapshots__/Step.test.js.snap
- tests/unit/__snapshots__/Target.test.js.snap
- tests/unit/__snapshots__/VersionModified.test.js.snap
[DOP-3259](https://jira.mongodb.org/browse/DOP-3259)
[DOP-3255](https://jira.mongodb.org/browse/DOP-3255)
- fixing links spacing issue: remove flex property from links (causing child items to compress)
- if code is child of link, inherit link color (overwrite LG's [InlineCode color](https://github.com/mongodb/leafygreen-ui/blob/main/packages/typography/src/InlineCode.tsx#L40))
[shell commands](https://www.mongodb.com/docs/mongodb-shell/reference/methods/#administration-methods)
[atlas - link is not spaced](https://www.mongodb.com/docs/atlas/atlas-search/tutorial/cross-collection-tutorials/)
[atlas - link is not spaced 2](https://www.mongodb.com/docs/atlas/atlas-search/tutorial/lookup-with-search/#connect-to-your-cluster-in-.)
[shell …
> DOP-3259 DOP-3255

- src/templates/product-landing.js
[DOP-3228](https://jira.mongodb.org/browse/DOP-3238)
[prod realm](https://www.mongodb.com/docs/realm/)
[prod server docs](https://www.mongodb.com/docs/manual/)
[staged realm docs](https://docs-mongodbcom-integration.corp.mongodb.com/42d5ec303ec60950a7fa78150c25572394e31562/master/realm/seung.park/DOP-3228/)
[staged server docs](https://docs-mongodbcom-integration.corp.mongodb.com/master/docs/seung.park/DOP-3228/)
minor change to add grid-column and max-width to ul's as same as paragraph tags in PLP
> DOP-3238: style ul in plp

- src/templates/product-landing.js
[DOP-3238](https://jira.mongodb.org/browse/DOP-3238)
This is a follow up to [previous pr](https://github.com/mongodb/snooty/pull/700)
introduced [a bug to Guides PLP](https://docs-mongodbcom-integration.corp.mongodb.com/master/guides/seung.park/master/) (not live yet so staged it on master branch)
[fixed new bug on guides PLP](https://docs-mongodbcom-integration.corp.mongodb.com/master/guides/seung.park/DOP-3238-followup/)
[kept previous fix on realm PLP](https://docs-mongodbcom-integration.corp.mongodb.com/master/realm/seung.park/DOP-3238-followup/)
> DOP-3238 follow up

- package-lock.json
- package.json
- tests/unit/__snapshots__/Operation.test.js.snap
DOP-2585
The modal component used in our lightbox component has been updated to the latest leafygreen branding version. Notable changes are to the close modal button and the degree of curvature at the modal corners.  
https://docs-mongodbcom-integration.corp.mongodb.com/master/docs/cris.newsome/branding-master/
> DOP-2585 updating to latest version of lg modal component

- gatsby-node.js
- src/components/AssociatedVersionSelector/index.js
- src/components/RootProvider.js
- src/components/Select.js
- src/components/Sidenav/Sidenav.js
- src/components/Sidenav/TOCNode.js
- src/components/Sidenav/VersionSelector.js
- src/components/Tabs/TabSelectors.js
- src/components/VersionDropdown/index.js
- src/context/toc-context.js
- src/context/version-context.js
- src/hooks/use-current-url-slug.js
- src/init/DocumentDatabase.js
- src/layouts/index.js
- src/templates/document.js
- src/utils/setup/fetch-manifest-metadata.js
- src/utils/setup/toc-test-data.json
- src/utils/url-utils.js
- tests/context/toc-context.test.js
- tests/context/version-context.test.js
- tests/unit/__snapshots__/SearchResults.test.js.snap
- tests/unit/__snapshots__/Select.test.js.snap
DOP-3266
DOP-3267
This PR is a feature branch from previous PR's for [3266](https://github.com/mongodb/snooty/pull/710) and [3267](https://github.com/mongodb/snooty/pull/714)
Each PR has been reviewed and approved by 1dev + designer before merge
staging links should be the same from staging links from here https://github.com/mongodb/snooty/pull/714
> Dop 3266 3267 feature branch

- src/components/Procedure/Step.js
- tests/unit/__snapshots__/Procedure.test.js.snap
- tests/unit/__snapshots__/Step.test.js.snap
DOP-2596
* **Connected with unconnected**: [https://docs-mongodbcom-integration.corp.mongodb.com/master/guides/heli/master/atlas/account/#create-your-mongodb-account.](https://docs-mongodbcom-integration.corp.mongodb.com/master/guides/heli/master/atlas/account/#create-your-mongodb-account.)
* **Unconnected**: [https://docs-mongodbcom-integration.corp.mongodb.com/master/guides/heli/master/atlas/network-connections/#select-my-local-environment.](https://docs-mongodbcom-integration.corp.mongodb.com/master/guides/heli/master/atlas/network-connections/#select-my-local-environment.)
* **Connected**: [https://docs-mongodbcom-integration.corp.mongodb.com/master/docs/heli/DOP-2596-original/#import-your-data](https://docs-mongodbcom-integration.corp.mongodb.com/master/docs/heli/DOP-2596-original/#im …
> DOP-2596: Only add top margin in connected steps

- src/components/GuideNext/Content.js
- tests/unit/GuideNext.test.js
- tests/unit/__snapshots__/GuideNext.test.js.snap
DOP-3321
https://www.mongodb.com/docs/guides/atlas/account/
https://docs-mongodbcom-integration.corp.mongodb.com/master/guides/cassidy.schaufele/DOP-3321/atlas/account/
Effectively copies the Link fix that we performed for PLP's.
Making this fix more generic should be preferred, but in the interest of making this fixed in production, should be addressed separately.
> DOP-3321: Fix broken 'Whats Next' Button

- src/components/OpenAPIChangelog/OpenAPIChangelog.js
DOP-3737
Tiny PR to ensure that selected resources for the resources list gets cleared when the resources list changes. Edge case for when there is more than one diff.
> clear selected resources on change

- src/components/OpenAPIChangelog/components/FiltersPanel/components/FiltersPanel.js
DOP-3757
From feedback on User testing:
Changes empty Resource Combobox message to provide more clarity.
> DOP-3757: 

- src/hooks/use-marian-manifests.js
DOP-3657
https://www.mongodb.com/docs/manual/
https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/bianca.laube/DOP-3657/index.html
- There should be no changes in anything you can see, they only change would be to the console for when it catches an error on the fetch call
> [DOP-3657] moving the fetch to a try catch

- src/components/SearchResults/MobileFilters.js
- src/components/SearchResults/SearchResults.js
- tests/unit/SearchResults.test.js
- tests/unit/__snapshots__/SearchResults.test.js.snap
[DOP-3926](https://jira.mongodb.org/browse/DOP-3926)
The copy for the UI elements for filtering search results is currently "Specify your search". A small vocabulary change was made so that it is now "Refine your search" instead. 
([search example with term "atlas"](https://www.mongodb.com/docs/search/?q=atlas))
[Staging Link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/anabella.buckvar/DOP-3926-b/search/)
> DOP 3926 changed copy specify to refine for search

- src/components/Widgets/FeedbackWidget/FeedbackTab.js
- tests/unit/__snapshots__/Presentation.test.js.snap
[DOP-3957](https://jira.mongodb.org/browse/DOP-3957)
Changes font color of Share Feedback card from #00A35C to #00684A.
[Staging environment](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/maya/DOP-3957/)
> DOP-3957: changed font color of feedback button

- src/components/Sidenav/IA.js
- src/components/Sidenav/IALinkedData.js
- tests/unit/IA.test.js
- tests/unit/__snapshots__/IA.test.js.snap
- tests/unit/data/IA.test.json
DOP-3993
[Homepage](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/newhomepagewhodis/landing/raymundrodriguez/DOP-3993/index.html)
[Search page](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/newhomepagewhodis/landing/raymundrodriguez/DOP-3993/search/index.html)
* Most of the line changes are due to test snapshots / sample data. 🙂 
* Not sure why the C++ icon is acting up in the staging link, but this seems to be limited to the staging site.
* Please ensure that styles match as desired (font, focus, hover, etc.)
> DOP-3993: Render IA-linked data on side nav

- src/components/ComponentFactory.js
- src/components/LandingIntro/index.js
- src/templates/landing.js
DOP-3987
[current landing](https://www.mongodb.com/docs/)
[updated staging link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/0d97de230b999231e0e7339da9596bf9c4a4502d/newhomepagewhodis/landing/seung.park/DOP-3987/index.html)
- used [this branch](https://github.com/mongodb/docs-landing/pull/131) from docs-landing
- used this [parser branch](https://github.com/mongodb/snooty-parser/pull/521) to add properties for the hero
> DOP-3987: style hero for new landing

- src/components/LandingIntro/index.js
DOP-3987
[Last iteration of hero](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/8e6dc3a1382530699c81e9146bfe3e202df61314/newhomepagewhodis/landing/seung.park/DOP-3987/index.html)
[staged changes](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/newhomepagewhodis/landing/seung.park/DOP-3987-use-flexbox/index.html)
- there should be no difference in output styling, just converting from a Grid layout with absolute positioned elements to a Flexbox layout, with assumptions of input AST
> DOP-3987 use flexbox for hero

- src/components/LandingIntro/index.js
DOP-4038
[The image is smol](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/newhomepagewhodis/landing/allison/master/index.html)
[The image is less smol and left column is vertically centred](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/newhomepagewhodis/landing/allison/DOP-4038/)
> DOP-4038: embiggen hero image

- package-lock.json
- package.json
- src/components/ChatbotUi.js
DOP-4040
[Earlier staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/newhomepagewhodis/landing/allison/DOP-4024/)
[Staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/newhomepagewhodis/landing/allison/master/index.html)
> DOP-4040: bump chatbot to v0.0.6

- src/templates/landing.js
follow up to DOP-3987.
Both examples have been parsed with latest parser version v0.14.9
[Current homepage](https://www.mongodb.com/docs/)
[Staged changes with docs-landing master branch parsed on with feature flag off](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/seung.park/DOP-3987-feature-flag-styling/index.html)
[Staged changes of new homepage (docs-landing feature branch with feature flag turned on)](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/newhomepagewhodis/landing/seung.park/DOP-3987-feature-flag-styling/index.html)
> styling behind feature flag

- src/components/DocumentBody.js
[DOP-4085](https://jira.mongodb.org/browse/DOP-4085)
[Current behavior
](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/anabella.buckvar/master/index.html)
[Staging link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/anabella.buckvar/DOP-4085/index.html)
> DOP-4085 updated chinese smartling footer url

- src/components/DocumentBody.js
> Smartlingslug

- src/components/DocumentBody.js
> fix pathing again

- package-lock.json
- package.json
- src/components/Header/index.js
- tests/unit/__snapshots__/Presentation.test.js.snap
DOP-4137
www.mongodb.com/docs
N/A, reconciling between 0.15.1.1 and `master` branch.
Already present in tag 0.15.1.1b - this is just to get the bump present in `master` for the next tag.
> DOP-4137: Universal Nav to 2.0.3-rc.11

- src/components/DeprecatedVersionSelector.js
[DOP-4176](https://jira.mongodb.org/browse/DOP-4176)
[Old PR](https://github.com/mongodb/snooty/pull/977) was messed up, oops. That has been fixed.
[Staging link (defaulting to build-time data - content should appear in the dropdown + an error should appear in the console)](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/maya/DOP-4176/legacy/index.html)
> DOP-4176 once again

- src/components/Widgets/ChatbotWidget/ChatbotFab.js
None
https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/newhomepagewhodis/landing/matt.meigs/chatbot-focus/legacy/index.html
Quick cleanup. `InputBarTrigger` is not needed, and so the component and the extra styling has been removed.
> Clean Chatbot of unnecessary component & style

- package-lock.json
- package.json
- src/components/Header/index.js
- tests/unit/__snapshots__/Presentation.test.js.snap
DOP-4523
Updating consistent nav version as well as Presentation snapshot.
[Current homepage production behavior](https://www.mongodb.com/docs/) (can see "Realm Documentation" in search dropdown)
[Landing staging link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/maya/DOP-4523/index.html) (Cannot see "Realm Documentation")
[Realm docs staging link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/realm/maya/DOP-4523/index.html)
> DOP-4523: Update consistent nav to 2.0.3-rc23

- src/components/CommunityPillLink.js
- src/components/ComponentFactory.js
- src/components/Roles/CommunityPillLink.js
- tests/unit/CommunityPillLink.test.js
- tests/unit/__snapshots__/CommunityPillLink.test.js.snap
- tests/unit/data/CommunityPillLink.test.json
Jira: DOP-4511
This is net new!
*new* https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master2/landing/allison/DOP-4511/languages/example/index.html
> DOP-4511: add link with community-build badge component

- .github/workflows/test.yml
- package-lock.json
- package.json
- src/components/Widgets/ChatbotWidget/ChatbotFab.js
- tests/unit/__snapshots__/Button.test.js.snap
- tests/unit/__snapshots__/CodeIO.test.js.snap
- tests/unit/__snapshots__/GuideNext.test.js.snap
- tests/unit/__snapshots__/OpenAPIChangelog.test.js.snap
- tests/unit/__snapshots__/QuizWidget.test.js.snap
- tests/unit/__snapshots__/SearchResults.test.js.snap
- tests/unit/__snapshots__/Video.test.js.snap
[DOP-4515](https://jira.mongodb.org/browse/DOP-4515)
https://www.mongodb.com/docs/database-tools/
https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/database-tools/brandonly/DOP-4515-c/database-tools/brandonly/master/index/
This PR updates the Chatbot to include changes to reduce the blocking time and improve page load speeds. Thanks @nlarew for your help!
Before:
After: 
> [DOP-4515]: Update chatbot version

- package.json
DOP-4597
[Staged Commit](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/ffed23c032d24e703f2312d00bee9173b88f12b7/master/docs/caesarbell/DOP-4597/)
This just updates the pakcage.json `engines.npm` to support npm version 9.x. When using `npm v9.5` local builds succeed, all tests pass, and staging commit builds succeed. Everything seems to work as expected.
> :package: DOP-4597 update the engines dependency version

- tests/unit/Chatbot.test.js
DOP-4781
N/A
N/A
- Updates the description for the Chatbot test, this bubbled over from a previous ticket.  
> :white_check_mark: DOP-4781 changes the description of the Chatbot test

- src/components/Widgets/index.js
> DOP-4759: Raise AI chatbot button z-index and apply hideFeedback to the openapi template

- package-lock.json
- package.json
- tests/unit/__snapshots__/Admonition.test.js.snap
[Link to conversation](https://mongodb.slack.com/archives/C018UTGP23T/p1721317266952749)
> hotfix: Downgrade Callout

- package-lock.json
- package.json
[(DOP-4836) Upgrade Chatbot to v0.8.1](https://jira.mongodb.org/browse/DOP-4836)
> DOP-4836: Upgrade Chatbot to v0.8.1

- src/components/ActionBar/ActionBar.js
DOP-4990
[datalake docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/datalake/seung.park/DOP-4990-actionbar/index.html)
[realm docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/realm/seung.park/DOP-4990-actionbar/index.html)
[(regression check) landing docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/seung.park/DOP-4990-actionbar/index.html)
> DOP-4990: remove feedback from actionbar for specific projects

- plugins/gatsby-source-snooty-prod/gatsby-node.js
- src/components/DocumentBody.js
- src/utils/structured-data.js
DOP-4915
This PR adds TechArticle Structured Data to each page by using different properties of metadata (namely facets and pageTitle).
It has been discussed with SEO team that arrays containing multiple values for a single field is preferred over multiple structured data JSON. see [thread](https://mongodb.slack.com/archives/C0366FYTK5Y/p1726861205901969).
[PD](https://docs.google.com/document/d/1gUBbcchLLwH7ytvNGQIyVIeSVDMTYPlBr7475m6Qu-w/edit#heading=h.yhwh093m3w1i)
[Parser PR to add display_name to facets](https://github.com/mongodb/snooty-parser/pull/621)
- [Atlas CLI Docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4915-multiple-genre-sample/atlas-cli/seung.park/DOP-4915/index.html)
- [rich results showing no …
> DOP-4915: Add Tech Article Structured Data to page

- src/components/ActionBar/ActionBar.js
- src/components/ActionBar/SearchInput.js
- src/components/ActionBar/SearchMenu.js
DOP-5026 - Disable navigation in search menu when chatbot is hidden
DOP-5045 - Initialize conversation on focus in search input
[on prod, conversation is not initialized until search menu is shown](https://www.mongodb.com/docs/)
No network calls to `https://knowledge.mongodb.com/api/v1/conversations` until Menu is shown:
The netlify link [below](https://github.com/mongodb/snooty/pull/1259#:~:text=https%3A//app.netlify.com/sites/mongodb%2Dsnooty/deploys/66fc6bbac08c5e0008fafd07)!
[docs qa](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/DOP-5026/) - must be connected to VPN to connect to staging chatbot API. This will fail (gracefully) and not show the chatbot option, as well as disabling navigation via keyboard (DOP-5026). Key difference is that the request is being made …
> DOP-5026 and DOP-5045

- src/components/Collapsible/index.js
- src/components/Procedure/index.js
- src/components/Section.js
- src/components/Tabs/index.js
- src/context/heading-context.js
- src/utils/get-plaintext.js
- src/utils/structured-data.js
- tests/context/heading-context.test.js
- tests/unit/__snapshots__/Procedure.test.js.snap
- tests/unit/utils/__snapshots__/structured-data.test.js.snap
DOP-5040
Staged link from previous PR:
[Staged link from previous PR:](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/seung.park/DOP-4919/atlas-search/index.html)
[Schema validation of above is missing HowTo.name and HowTo.image](https://validator.schema.org/#url=https%3A%2F%2Fdocs-mongodb-org-stg.s3.us-east-2.amazonaws.com%2Fmaster%2Fcloud-docs%2Fseung.park%2FDOP-4919%2Fatlas-search%2Findex.html)
[Example of Procedure within tab on Atlas product landing page](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/seung.park/DOP-5040/index.html)
[Schema validator for above](https://validator.schema.org/#url=https%3A%2F%2Fdocs-mongodb-org-stg.s3.us-east-2.amazonaws.com%2Fmaster%2Fcloud-docs%2Fseung.park%2FDOP-5040%2Findex.html)
[Staged …
> DOP-5040 - add image and name to How To structured data

- src/components/Banner/CTABanner.js
- src/components/Banner/OfflineBanner.js
- src/components/Banner/styles/bannerItemStyle.js
- src/components/DocumentBody.js
- src/components/OfflineNotAvailable.js
- src/templates/changelog.js
- src/templates/document.js
- src/templates/drivers-index.js
- src/templates/instruqt.js
- src/templates/product-landing.js
- tests/unit/Banner.test.js
- tests/unit/__snapshots__/Banner.test.js.snap
- tests/unit/__snapshots__/CTABanner.test.js.snap
DOP-5105
[Prod page with video](https://www.mongodb.com/docs/atlas/atlas-search/view-query-analytics/)
[Prod page with instruqt lab](https://www.mongodb.com/docs/atlas/atlas-search/tutorials/)
[atlas landing page](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/seung.park/DOP-5105/index.html)
["Staged offline docs" for the same video example as above](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/seung.park/DOP-5105/atlas-search/view-query-analytics/index.html) - the resulting HTML is also found [here](https://us-east-2.console.aws.amazon.com/s3/buckets/docs-mongodb-org-stg?region=us-east-2&bucketType=general&prefix=master/cloud-docs/seung.park/DOP-5105/atlas-search/view-query-analytics/&showversions=false) 
[Instruqt lab …
> DOP-5105: add offline banner

- package-lock.json
- package.json
DOP-5236
N/A
N/A
* no test, just need to make sure /test-deploy okay and its still passing the pr tests
> DOP-5236: Upgrading gatsby

- README.md
N/A
* Updates the README as discussed during engineering sync. Just highlighting a couple of the warnings!
- - [x] This PR introduces changes that should be reflected in the README, and I have made those updates.
> Highlight release warnings

- package-lock.json
- package.json
DOP-5536
[Current](https://www.mongodb.com/docs/)
[Staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/matt.meigs/DOP-5536-chatbot-upgrade/)
Upgrade. Adds "Scroll to latest" button.
> DOP-5536: Upgrade chatbot to v0.13.0

- src/components/SEO.js
- src/html.js
DOP-5472 & DOP-5473
N/A
https://deploy-preview-1390--docs-frontend-stg.netlify.app/
All the listed meta tags should now be present
> DOP-5472 & DOP-5473: Add SEO meta tags

- src/components/Tabs/tab-context.tsx
- src/hooks/use-hash-anchor.tsx
DOP-301
Switching of single tab:
Link to tab in [Atlas - Connect to your Cluster](https://www.mongodb.com/docs/atlas/getting-started/#connect-to-your-cluster.) (first make sure this page is set to the Atlas CLI tab OR clear your local storage)
[Atlas - Deploy Cluster](https://www.mongodb.com/docs/atlas/tutorial/deploy-free-tier-cluster/#create-a-database-user.) (first make sure this page is set on one of first two tabs OR clear local storage)
Switching of language selector:
[Atlas - Driver Connection](https://www.mongodb.com/docs/atlas/driver-connection/#mongoid-example) (first make sure this page is set to NOT Ruby OR clear your local storage)
Switching of multiple tabs:
Atlas - [Select a Cluster Type](https://www.mongodb.com/docs/atlas/tutorial/create-new-cluster/#select-a-cluster-type.- …
> Fix hash scroll

- src/components/ActionBar/ActionBar.js
- src/components/Contents/index.js
- src/components/Heading.js
- src/components/RightColumn.js
- src/components/Widgets/FeedbackWidget/FeedbackButton.js
- src/components/Widgets/FeedbackWidget/FeedbackCard.js
- src/components/Widgets/FeedbackWidget/FeedbackContainer.js
- src/components/Widgets/FeedbackWidget/FeedbackForm.js
- src/components/Widgets/FeedbackWidget/components/StarRating.js
- src/components/Widgets/FeedbackWidget/constants.js
- src/components/Widgets/FeedbackWidget/handleScreenshot.js
- src/components/Widgets/FeedbackWidget/index.js
- src/components/Widgets/FeedbackWidget/styles.css
- src/components/Widgets/FeedbackWidget/views/CommentView.js
- src/components/Widgets/FeedbackWidget/views/RatingView.js
- src/components/Widgets/FeedbackWidget/views/SubmittedView.js
- src/components/Widgets/index.js
- src/templates/document.js
- src/templates/product-landing.js
- tests/unit/ActionBar.test.js
- tests/unit/FeedbackWidget.test.js
> Revert "DOP-5544 and DOP-5543:  Moving rating component to the page level"

- README.md
DOP-5715
- update readme, add npm login to install section
--
--
- - [x ] This PR introduces changes that should be reflected in the README, and I have made those updates.
> DOP-5715 update README -- add npm login to install section

- src/components/UnifiedSidenav/UnifiedConstants.ts
- src/components/UnifiedSidenav/UnifiedSidenav.js
- toc_data/toc.ts
DOP-5856
* simple change to the tocItem[] type to have the contentSite variable be explicit in the toc.ts 
> DOP-5856: Have contentSite be explicitly declared  

- README.md
- netlify.toml
- src/components/Link.js
- src/components/UnifiedSidenav/AccordionNav.js
- src/components/UnifiedSidenav/DoublePannedNav.js
- src/components/UnifiedSidenav/UnifiedSidenav.js
- src/components/UnifiedSidenav/UnifiedTocNavItems.js
- src/components/UnifiedSidenav/styles/SideNavItem.tsx
- src/pages/404.tsx
- src/utils/is-active-toc-node.js
- src/utils/is-unified-toc-active.ts
> Revert "DOP-5922: preview builds with working unified toc "

- src/components/ActionBar/ChatbotModal.tsx
- [(EAI-1185) Remove "experimental" from disclaimer text in chatbot](http://jira.mongodb.org/browse/EAI-1185)
- Updates `ChatbotModal` from using hardcoded string to importing the disclaimer text from our package
> (EAI-1185) Remove "experimental" from disclaimer text in chatbot

- plugins/utils/banner.js
> banner content fix
